### ISSUE TITLE
Fail to deploy image to Azure App Service in Docker Hub Registries

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1243]
**OS:** All
**Build Version:** [20190902.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=9351)
**Regression:** Previous release

**Steps to reproduce:**

1. Create an Express App and open it in VS Code.
2. Command Palette->Add Docker files to workspace->Node.js->Enter port.
3. Right click Dockerfile->Build image.
4. Push the image to Docker Hub registry.
5. Right click the image in registry->Deploy Image to Azure App Service.
![image](https://user-images.githubusercontent.com/45614674/64242994-26a5db00-cf39-11e9-9a3d-4e1ae88ea953.png)

**Expect Experience:**
The wizard to create web app without any error.

**Actual Experience:**
An error dialog pops up.
![image](https://user-images.githubusercontent.com/45614674/64242393-01fd3380-cf38-11e9-9512-57c471d8a389.png)

**Comment by philliphoff** [comment]
@v-ruizh What version of VS Code are you using? I'm on the latest (1.38) and cannot repro that error message.  I notice in your screenshot that it appears that the repository node is selected even though the context menu shown should be for the tag node.  I could imagine this to be a problem, but no combination of keyboard or mouse selection repros that configuration.

That said, I encountered another issue: not dismissing the (I believe new to 0.7.1) dialog displayed about adding a web hook results in the deployment not being reported complete.  (That is, it *is* complete, but still shows as deploying in VS Code.) I was able to track down why this happens, but not sure of the resolution yet.

**Comment by philliphoff** [comment]
Notes regarding the other issue:

This is because the wizard isn't completed until all of the steps are complete, and the web hook step isn't complete until the notification is dismissed.

The problem is that VS Code will shift informational messages from the shell to the notification pane after some period of time, effectively hiding it.

So the only message left on the shell is the "deploying..." message, which never shows completion (because the user would have to go open the notification pane and dismiss it).

Since the web hook notification isn't actually displayed until deployment is complete (i.e. a few seconds after it starts), the user may never notice that it was displayed and then hidden, and therefore think deployment is taking forever.

I think the simplest fix is to not tie completion of the wizard to dismissal of the web hook notification. That is, to make that part of the web hook step totally async and not awaited.

**Comment by v-ruizh** [comment]
@philliphoff, sorry for submitting this invalid issue. This issue does not reproduce after updating the VS Code Insider and Docker Desktop.

**Comment by bwateratmsft** [comment]
@v-ruizh No problem! We were able to find another bug while investigating :)
