### ISSUE TITLE
Edit-refresh doesn't work after adding dockerfile to mvc web application

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1302]
**OS:** Win10 & Mac
**Build Version:** [20190924.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10388)
**.NET Core Version:** 2.2.402
**Regression:** Not a Regression

**Repro Steps:**

1. Create an empty folder and open it in VS Code.
2. Create a new ASP.NET MVC app to the opened folder by "dotnet new mvc --no-https --name test1".
3. Select "Yes" when asked whether add the required assets to build and debug or not.
4. F1 --> Type and select "Docker: Add Docker Files to Workspace" --> ASP.NET Core -->Linux -->Port : 80.
5. Go to the Debug tab --> Select the Docker launch profile --> Debug.
6. **Don't stop the debugging**, go to File Explorer->Home, edit 'Privacy.cshtml'.
7. Go to the opened web page and refresh the 'Privacy' page.
8. Check whether the edit-refresh works well or not.

**Expect:**
Edit-refresh works well, the change is available.

**Actual:**
Edit-refresh doesn't work.

**More Info:**
This issue does not reproduce without Docker.

**Comment by bwateratmsft** [comment]
@v-ruizh It seems the story for edit-refresh is changing. Since this test was for 2.2, can you try refreshing a few times to see if that works?

Here's what @pratiksanglikar said we have for VS:

.NET Core 2.1 -> Works on both Linux and Windows containers.

.NET Core 2.2 -> Runtime compilation APIs are obsoleted, it works, but may take multiple refreshes to actually see the changes on both Linux and Windows containers.

.NET Core 3.0 -> Runtime compilation support is disabled in default templates. To enable it, 
 - Add `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` nuget package.
 - In the Startup.cs, add `services.AddRazorPages().AddRazorRuntimeCompilation();`
 - After making the above mentioned changes, Edit and refresh works for both Linux and Windows containers.

**Comment by v-ruizh** [comment]
@bwateratmsft Thanks for your update. This issue also **reproduces** after refreshing the web page a few times. (.NET Core 2.2)

**Comment by bwateratmsft** [comment]
The root cause is that we aren't using `DOTNET_USE_POLLING_FILE_WATCHER=1` in the environment variables. Created #1306 to solve this.
