### ISSUE TITLE
Actions involving the terminal do not preserve remote host settings

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-docker#1315]
Testing https://github.com/microsoft/vscode-remote-release/issues/1516

VS Code Insiders 1.39.0-insider, 695ee74864ef93d10f5de0861cb66af190e76211
Docker Extension 0.8.1

1. Go through the setup in https://github.com/microsoft/vscode-remote-release/issues/1516
 to create a remote docker machine and configure `docker.host`, `docker.certPath` and `docker.tlsVerify` to point to it
2. Check that the Containers tree shows containers running remotely
3. Right click one of them and click `View Logs`

A terminal will pop up and fail to find the container since it fails to set up the right environment for the remote machine.

![image](https://user-images.githubusercontent.com/22350/66038881-a3fe4480-e513-11e9-871d-51de7a7aa2fd.png)

cc @chrmarti

**Comment by joaomoreno** [comment]
Same for `Attach Shell`

**Comment by bwateratmsft** [comment]
Looks like our code just creates a VSCode terminal and sends it `docker` commands, hence the values in settings would not be picked up. As a workaround, the corresponding environment variables (e.g. `DOCKER_HOST`) _should_ still work.

**Comment by bwateratmsft** [comment]
@EricJizbaMSFT, I noticed that runAzureCliImage in particular uses vscode.window.createTerminal, whereas all the others use ext.terminalProvider.createTerminal; is that intentional?

**Comment by bwateratmsft** [comment]
@joaomoreno I'm not able to reproduce the issue on either Mac or Windows, at least on 1.38. What shell are you using?

Is it possible there's a bug in the insiders build relating to settings, in particular `vscode.workspace.onDidChangeConfiguration`? We have a settings listener that will cause dockerode to be refreshed if those `DOCKER_*` settings are changed--if dockerode was not refreshed, it would be displaying the containers/images/etc. on the local machine (or whatever was configured previously), not on the remote Docker machine. But when we run the commands, we copy in the values for `DOCKER_HOST` etc. before creating the terminal, so that code path would not depend on `onDidChangeConfiguration`.

Note, `runAzureCliImage` would definitely be affected but the rest of the commands seemed to work fine for me.

**Comment by EricJizbaMSFT** [comment]
> I noticed that runAzureCliImage in particular uses vscode.window.createTerminal, whereas all the others use ext.terminalProvider.createTerminal; is that intentional?

No idea

**Comment by bwateratmsft** [comment]
I finally found where it was originally authored, #304. @tfenster @StephenWeatherford Do you know why `runAzureCliImage` uses `vscode.window.createTerminal` instead of `ext.terminalProvider.createTerminal`? Is that intentional?

**Comment by tfenster** [comment]
@bwateratmsft very likely just a mistake when I did this

**Comment by joaomoreno** [comment]
@bwateratmsft I'm on zsh.

**Comment by bwateratmsft** [comment]
@joaomoreno I cannot reproduce this on ZSH on Mac either. What are your config settings? For instance, mine look like this:
![image](https://user-images.githubusercontent.com/36966225/66136262-2d238300-e5c9-11e9-81ba-563b61715539.png)

**Comment by joaomoreno** [comment]
Never mind, this is my fault. I use a special shell which was breaking this. Sorry for the hassle.
