### ISSUE TITLE
Consider slowing down refresh speed on explorer window

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#1351]
Related to #1292 , #1225.

@philliphoff @BigMorty @EricJizbaMSFT @StephenWeatherford @fiveisprime How would you guys feel about slowing down the explorer window's refresh rate from the current 1 second to something longer? Two? Three? Five?

**Comment by bwateratmsft** [comment]
Mainly, CPU usage: #1225 , and significant DNS traffic: #1292.

We can't control either of those problems but we can slow down the default refresh rate. Anybody who needs it to be faster can always speed it up.

**Comment by bwateratmsft** [comment]
> stopping the auto-refresh when not in focus, is that something we can do as well?
Yes, planning to: #1352

**Comment by BigMorty** [comment]
Great! 👍

**Comment by karolz-ms** [comment]
My 2 cents: we should make the refresh rate a configuration parameter, incl. allowing auto-refresh to be turned off (there is option to manually refresh already).

**Comment by EricJizbaMSFT** [comment]
@karolz-ms there's already a [setting](https://github.com/microsoft/vscode-docker/blob/master/package.json#L1093) `docker.explorerRefreshInterval`

Regarding the motivation of this issue, another mitigation could be to collapse the network/volume explorers by default. I bet plenty of people leave those open, causing us to poll on them, but only actually use the containers/images explorers. Unfortunately, not sure if VS Code lets us specify a default expanded/collapsed state

**Comment by philliphoff** [comment]
We might also consider switching to a "push" model rather than a "pull/poll" model.  We do this for CTW in VS where the containers/images trees are refreshed only when relevant events are reported by Docker, rather than on any specific polling interval.  (The refresh is further throttled so that refresh only happens x number of milleseconds after no more relevant events have been received.) This may not work for all nodes in the tree, but it might reduce the total number of calls to Docker that need to be made during a refresh.

**Comment by bwateratmsft** [comment]
Dockerode does support this with the getEvents method. It returns JSON that could probably tell us which _section_ to refresh, or let us avoid refreshing entirely if we want to get more advanced.
