### ISSUE TITLE
Fail to hit the breakpoint and pop up an error in "Debug Console" window

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#1401]
**OS:** Win10
**Build Version**: [20191106.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12147)
**Regression:** Previous Build [[20191106.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12124)]

**Repro Steps:**
1. Install .NET Core SDK 3.1 .
![image](https://user-images.githubusercontent.com/34729092/68381749-579aca00-018d-11ea-9602-f1ede947bab4.png)
2. Create a new .NET Core project by "dotnet new mvc --name test".
3. Open this project in VS Code.
4. Select "Yes" when asked whether add the required assets to build and debug or not.
5. F1 --> "Docker : Add Docker Files to Workspace" --> Set a breakpoint in Controllers/HomeController.cs in the Index() method.
6. Click "Docker .NET Core Launch" --> Check the result.

**Expect:**
Succeed to hit the breakpoint and launch the browser.

**Actual:**
Fail to hit the breakpoint and pop up an error in "Debug Console" window.
![image](https://user-images.githubusercontent.com/34729092/68382179-22db4280-018e-11ea-8b60-41e9f9ec8b6d.png)

**Comment by bwateratmsft** [comment]
This may be a 3.1 compat issue but we need to investigate ASAP.

**Comment by bwateratmsft** [comment]
@v-dantch I was able to get it to work. There's a couple things to check:

1. What image is in use in the `base` stage of your Dockerfile? By default, it scaffolded `mcr.microsoft.com/dotnet/core/aspnet:3.1` for me, which works without changes since 3.1 preview2 is publicly available (so the image is as well).
1. Can you try pulling the latest 3.1 public image with `docker pull mcr.microsoft.com/dotnet/core/aspnet:3.1`?
1. We checked in some stuff a little early on Wednesday that only works in VSCode 1.40, which is available today but maybe was not when you tested, can you try again with 1.40?

**Comment by v-dantch** [comment]
Hi @bwateratmsft , thanks for your quick response and sorry for my late reply. We verified this issue on the latest nightly build [20191116.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12517&view=results), this issue does not reproduce for now. And we will close this bug for now.
