### ISSUE TITLE
How to install Nightly version of Docker extension

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#1408]
The latest nightly build of the Docker extension can be installed by anybody. To do so:

1. Download the VSIX from the "Published Artifacts" link here (in the `vsix` artifact, looks like `vscode-docker-1.26.0.vsix`): [![Build Status](https://dev.azure.com/ms-azuretools/AzCode/_apis/build/status/vscode-docker?branchName=main)](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=63609&view=results)

> <img src="https://github.com/microsoft/vscode-docker/assets/59073590/fb4d06df-cfd5-4708-8cfb-55fbc3539082" width="50%" height="50%">

2. In VSCode, open the command palette (<kbd>F1</kbd> by default) and type "Extensions: Install from VSIX...", hit enter
3. It will open up a file picker; choose the downloaded vscode-docker-x.y.z.vsix. The extension will be installed and may require a reload of VSCode.

For more information on installation, see here: https://aka.ms/azCodeInsiders

**Comment by eine** [comment]
IMHO, this content might better fit in the README, instead of being an issue.

**Comment by philliphoff** [comment]
@eine Point taken but, if I remember correctly, we explicitly decided *not* to add it to the `README.md`, as that file is used verbatim in the VS extension marketplace and we didn't want to potentially confuse users by having instructions for installing the nightly alongside the official extension installation process.  I'd expect most users wishing to install a nightly are doing so to test an update related to an issue they've submitted, hence keeping the instructions close to the Issues page.

**Comment by eine** [comment]
@philliphoff, that's a fair point, but I believe that the current solution is falling short to achieve it. Users that are wishing to install some *nightly* to test an update related to an issue, are unlikely to want the version that is linked in the shield/badge above. Conversely, they should go to the PR they want, check the tests/checks/jobs of that specific PR and get the artifacts from there. I'm saying this because I have done it several times before.

Therefore, I think that a good compromise is to move the content from this issue to a markdown file in the codebase. Then, that file can be linked from the "Contributing" section of the README, from this pinned issue and/or from any other place where it might be useful (whenever a user asks how to test a specific feature which is WIP).

**Comment by bwateratmsft** [comment]
Was hoping that locking would prevent unpinning.

**Comment by bwateratmsft** [comment]
Maybe replace this with an Insiders build of the extension: https://github.com/microsoft/vscode/issues/15756#issuecomment-967006890

**Comment by bwateratmsft** [comment]
> Maybe replace this with an Insiders build of the extension: [microsoft/vscode#15756 (comment)](https://github.com/microsoft/vscode/issues/15756#issuecomment-967006890)

I looked and we have at most 3 external users with a nightly build installed, and odds are at least some of those 3 are actually internal. IMO the interest just is not there, not enough to justify working on a proper version using the new pre-release extension feature.

**Comment by bwateratmsft** [comment]
I think we should take another look at using VSCode's preview release feature. At the time this issue was authored it didn't exist, but I think it's a good fit. I'm going to remove the milestone from this issue so we can retriage it.

**Comment by dbreshears** [comment]
Not planned
