### ISSUE TITLE
dockerServerReadyAction does not work if verbatim URL is used (.NET Core debugging)

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode-docker#1448]
**Repro steps**

1. Create .NET Web API app (`dotnet new webapi --no-https`). When asked about port to listen on, specify 5000.
2. Add Docker files to project
3. In the Dockerfile, ensure that ASPNETCORE_URLS is set in the `base` stage:
```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.0 AS base
WORKDIR /app
EXPOSE 5000
ENV ASPNETCORE_URLS=http://*:5000
...
```
4. In `tasks.json` make sure that port 5000 is used to expose the app on the host network:
```json
        {
            "type": "docker-run",
            "label": "docker-run: debug",
            "dependsOn": [
                "docker-build: debug"
            ],
            "dockerRun": {  
                "ports": [
                    {
                        "containerPort": 5000,
                        "hostPort": 5000
                    }
                ]              
            },
            "netCore": {
                "appProject": "${workspaceFolder}/netcorerest.csproj",
                "enableDebugging": true
            }
        },
```
5. In `launch.json` add the following (to use correct URL for the Web API)
```json
            "dockerServerReadyAction": {
                "uriFormat": "http://localhost:5000/WeatherForecast"
            }
```
6. F5

**Expected**

Browser opens using the URL specified in `launch.json`

**Actual**

Browser tries to open `http://localhost:5000/WeatherForecast%20http%205000` and fails

**Notes**

Seems like the `dockerServerReadyAction expects to always substitute something into the given value. The following works:
```json
            "dockerServerReadyAction": {
                "uriFormat": "%s://localhost:%s/WeatherForecast"
            }
```

Setting explicit startup URL for container debugging is a common need.

**Comment by philliphoff** [comment]
The issue is [here](https://github.com/microsoft/vscode-docker/blob/c521d3d855aff1e180ba9b717c4c5e89343ad1f5/src/debugging/DockerServerReadyAction.ts#L142), likely due to `util.format()` being semantically different than .NET's `String.format()`.  In the case of Node.js, it will simply concatenate arguments (separated by spaces) if the format string does not contain enough substitution tokens.  Whereas, in .NET, arguments which do not have a matching substitution token in the format string are simply ignored.
