### ISSUE TITLE
nvidia-docker from within VS code? (devcontainer json)

### ISSUE THREAD

**Issue by dvirginz** [microsoft/vscode-docker#1457]
Is there a way to run nvidia-docker from vs code remote docker extention?
The docker instructions are

`nvidia-docker build -t detectron2:v0 .`
`nvidia-docker run -it --name detectron2 detectron2:v0`
But vs code runs docker build/ docker run and it is not configurable.
The one thing that is configurable is the devcontainer.json with the structure

```
{
    "name": "Existing Dockerfile",
    "context": "..",
    "dockerFile": "../Dockerfile",
    "runArgs": [
    ],
    "settings": {
        "terminal.integrated.shell.linux": null
    },
    "extensions": []
}
```
I see that by adding --runtime=nvidia is equaivalent to nvidia-docker run, but how can I also control the build process?

**Comment by philliphoff** [comment]
@dvirginz The `vscode-docker` extension isn't part of the VS Code remote (container) development feature--that's probably better reported at the [vscode-remote-release](https://github.com/microsoft/vscode-remote-release).  That said, I don't know of a way to set the `runtime` argument for Docker image builds performed by VS Code for the purposes of creating a dev container.  That argument also cannot be set via a Docker Compose YAML file (which can be used with dev containers and is an alternative way to customize the build of the Docker image).

One approach could be to pre-build the Docker image, push it to a repository, and then reference that image from the `devcontainer.json` rather than have VS Code build the image itself.
