### ISSUE TITLE
Unable to debug a .net core web workspace

### ISSUE THREAD

**Issue by ravipal** [microsoft/vscode-docker#1474]
Repro steps:
1. Open an empty folder and launch terminal
2. Create a mvc app ('dotnet new mvc')
3. Save it as a workspace.
4. 'Docker: Add docker files to workspace'. Docker debugging related tasks are added to workspace file.
5. F5 show error
Attaching the repro folder
[WebApp4.zip](https://github.com/microsoft/vscode-docker/files/3941264/WebApp4.zip)

Action: docker-launch
Error type: Error
Error Message: To debug with Docker you must first open a folder or workspace in VS Code.

Version: 0.9.0
OS: win32
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:324:65436extension.bundle.js:324:65436
Object.<anonymous> extension.bundle.js:1:434228
extension.bundle.js:1:432316extension.bundle.js:1:432316
n extension.bundle.js:1:432090
Object.t.callWithTelemetryAndErrorHandling extension.bundle.js:1:434146
DockerDebugConfigurationProvider.resolveDebugConfiguration extension.bundle.js:324:65364
extensionHostProcess.js:729:964extensionHostProcess.js:729:964
```

</details>

**Comment by philliphoff** [comment]
I can repro this; the immediate issue is our misunderstanding of (and a bit of VS Code inconsistency in) how VS Code indicates whether a task/debug configuration is being executed in a workspace context (vs. a folder context).  In the case of debugging, VS Code passes `undefined` for the workspace folder.  Our debug configuration provider should fallback to the root workspace folder in that case rather than failing with the above error.  In the case of a task, VS Code passes the enumerated value `TaskScope.Workspace` for the scope rather than an actual workspace folder.  Our task provider should, again, fallback to the root workspace folder in that case.

While those are relatively simple fixes, the larger issue is that, as of `1.40.2`, VS Code does not appear to execute debug configurations defined as part of the workspace.  (That is, VS Code will resolve them but execution fails without error or exception, for both .NET and Node.js adaptors.) This appears to be resolved in the `1.41.0` build of the VS Code Insiders edition.  However, it appears there's still an [issue](https://github.com/microsoft/vscode/issues/83992) with workspace-defined debug-configuration `preLaunchTask`s that we will likely have to wait for, as we rely on pre-launch property to perform the Docker build/run chain of tasks.

The current workaround would be to put the task/debug configuration in the `.vscode/[launch|task].json` files rather than the workspace `.code-workspace` file.

**Comment by dbreshears** [comment]
@ravipal , after next VSCode release, please validate this is fixed and close

**Comment by ravipal** [comment]
Now the error is different in VS code version 1.41.1
![image](https://user-images.githubusercontent.com/1775825/73898666-fb544e80-483e-11ea-969f-bd3e0a831edc.png)

**Comment by bwateratmsft** [comment]
@philliphoff the C# extension adds the tasks as workspace folder tasks irrespective of whether you have a workspace open. When we add the debug tasks, we're adding them as workspace tasks. The result is that it never runs dotnet build (because that task is defined somewhere other than workspace), doesn't show a warning or error that it didn't execute a dependent task (thanks VSCode), and fails at time of launch. I can't repro the new error @ravipal is seeing.

We should add the tasks as workspace folder tasks always.

**Comment by bwateratmsft** [comment]
Update: if I move the dotnet build task down to workspace tasks, everything works. So we have two options:

1. Always use workspace folder tasks/debug, never workspace tasks/debug
2. Tell the C# extension they need to use workspace tasks/debug when a workspace is open
