### ISSUE TITLE
Mark outdated images

### ISSUE THREAD

**Issue by eine** [microsoft/vscode-docker#1493]
The tags of some of the images in the "Images" tree view are likely to get outdated when maintainers push new versions to the corresponding registries. Similarly to how modifications are marked in git repos, I think it would be useful to have a symbol added to outdated images.

Related to #1313, this feature would help users decide when they need to explicitly pull the image.

**Comment by bwateratmsft** [comment]
I've been investigating this some. I can't find any documentation about the Docker Hub API (the old one, not the Registry V2 API). The Registry V2 API is a non-starter for this purpose because it requires authentication, even to access public images.

There is a JSON endpoint, e.g. https://hub.docker.com/v2/repositories/library/nginx/tags/latest, but the `last_updated` time in that result is unreliably far away from the actual manifest time of the image (e.g. for this `nginx:latest`, 54 minutes; for `alpine:latest`, 2 hours 22 minutes). IMO this is too far and too variable to be dependable.

**Comment by bwateratmsft** [comment]
Interestingly I found that you do not need to provide anything in the `Authorization` header to get a valid token from the `auth.docker.io/token` endpoint; at least for public scopes like `repository:library/nginx:pull`. With that token you can get a proper manifest from `https://registry-1.docker.io/v2/library/nginx/manifests/latest` to do an exact check.

**Comment by bwateratmsft** [comment]
We have released Docker 1.4.0 which contains this feature. It can be disabled by unchecking "Docker: Images: Check For Outdated Images" in settings.
