### ISSUE TITLE
"Run Interactive" stopped using the shell command specified on the settings (docker.attachShellCommand.linuxContainer)

### ISSUE THREAD

**Issue by Szauka** [microsoft/vscode-docker#1497]
Vs Code version:
```
Version: 1.42.0-insider (user setup)
Commit: 2d2ac8f75b539d505443ac0733b196851c0b218d
Date: 2019-12-16T12:09:59.453Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
```

```
Version: 1.41.0 (user setup)
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-11T18:37:42.077Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
```

Extension info (Insiders & Stable):
```
Name: Docker
Id: ms-azuretools.vscode-docker
Description: Adds syntax highlighting, commands, hover tips, and linting for Dockerfile and docker-compose files.
Version: 0.9.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker
```

Current behavior:
`docker run --rm -it -p 8888:8888/tcp jupyter-lab/demo:v02`
Expected behavior:
`docker run --rm -it -p 8888:8888/tcp jupyter-lab/demo:v02 /bin/sh`

**Comment by philliphoff** [comment]
@Szauka Do you know which version of `vscode-docker` you last saw the expected behavior?  Looking at the codebase, running an image (interactively) does not appear to have ever used the `docker.attachShellCommand` settings, which makes sense, as that would have effectively overridden the image's entry point and the intent, as far as I know, of the "run [interactive]" commands is to simply start the container in whatever way the image defines.

The "attach to container" command, however, uses the `docker.attachShellCommand` settings as the container is presumably already running (the entry point), so the only thing it can do is open a separate shell.

**Comment by Szauka** [comment]
Hi @philliphoff thanks for having a look into this so quickly, you are right I've confused the "Attach Shell" option from the containers with the "Run Interactive" from the images.

I normally start the containers using Docker Compose but yesterday I spent all day starting them trough the "Run Interactive" option and I wanted to override the entry point for my specific use case and that has confused me.

The "Attach Shell" is the one that correctly uses the `docker.attachShellCommand` setting.

**Comment by philliphoff** [comment]
@Szauka A new option with 0.9.0 is to create a VS Code `docker-run` task (in `tasks.json`) that runs the container. The task allows one to [control many of the Docker run arguments](https://github.com/microsoft/vscode-docker/wiki/Extension-Properties-And-Tasks#run-task-reference), such as the command that overrides the entry point.  One can then run the task from the command palette.
