### ISSUE TITLE
The notification message will disappear after removing a container

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1509]
**OS:** All
**Build Version:** [20191221.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13288&view=results)
**Regression:** Not a Regression

**Steps to reproduce:**

1. Navigate to the container explorer in VS Code.
2. Remove a container.
3. Check the notification message.

**Expect:**
There is a notification message after removing the container.

**Actual:**
The notification message will disappear after removing the container.
![image](https://user-images.githubusercontent.com/45614674/71439680-8537d480-2735-11ea-8273-bd16311e6053.png)

**More info:**
There is no output log after removing a container.

**Comment by philliphoff** [comment]
@v-ruizh Since this is listed as not being a regression, is this then just a suggestion? What kind of notification (for successful removal) would you like to see?  For example, since we can't turn the removing-in-progress notification into a standard notification (only just remove it), would you want to see a second "removed" notification in the tray?  Would it be better (or worse) to see removal logged in the (Docker) output window instead (or perhaps *in addition* to the progress notification)?  As the notification tray can get quite busy, making it difficult for users to notice individual messages, we'd need to balance using it vs. other modes of notification.

**Comment by v-ruizh** [comment]
@philliphoff It would be better to see a second "removed" notification in the tray. It's more intuitive. Of course, it's ok to see removal logs in the (Docker) output window instead if it is more easily implement.

**Comment by philliphoff** [comment]
@v-ruizh Thanks for the feedback.  I'll let @BigMorty decide what notification(s) might be most appropriate.

**Comment by BigMorty** [comment]
We have received feedback in general that a lot of "toast" notifications can be distracting so I would not want to put up a second notification. I would be fine with outputting a message to the Docker output window.

**Comment by bwateratmsft** [comment]
We'll leave as is with the progress notification.
