### ISSUE TITLE
Can't navigate to the "docker new issue" page after clicking "Report an issue" button

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1512]
**OS:** All
**Build Version:** [20191221.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13288&view=results)
**Regression:** Not a Regression

**Steps to reproduce:**

1. Don't sign in the GitHub account.
2. Open Docker Explorer in VS Code, create a volume using this command: 
    docker run -d --name devtest --mount source=nginxVol,target=/app nginx:latest
3. There is a nginxVol volume in "VOLUMES" treeView.
4. Right Click the nginxVol volume and remove it.
5. An error occurs in notification.
6. Click the "Report an issue" button from the notification.
7. Sign in the GitHub account.

**Expect:**
Navigate to the "docker new issue" page to open a new issue.

**Actual:**
Can't navigate to the "docker new issue" page and an error occurs. It will skip the Two-factor authentication step when sign in GitHub.
![image](https://user-images.githubusercontent.com/45614674/71442039-24ad9500-273f-11ea-9226-9ccf1fa59ec2.png)

**More Info:**
This bug does not reproduce if you have signed in the GitHub account before "Report an issue".

**Comment by philliphoff** [comment]
This is a [known issue with GitHub auth](https://github.com/microsoft/vscode-azuretools/issues/481).  From my testing, it appears due to some implicit limitation on the length of the parameter passed in the URL to pre-populate the issue body (as it's transformed during the various redirections made due to the 2FA auth flow).
