### ISSUE TITLE
Error: Process exited with code 1

### ISSUE THREAD

**Issue by ukaratas** [microsoft/vscode-docker#1530]
Repro steps:

1 - Trying to build with  my application in vs code with below configuration, built get fail.

*
> Building Docker image...
Sending build context to Docker daemon  266.8kB
Failed to build Docker image: Error: Process exited with code 1
Error: Process exited with code 1
*

```
{
            "name": "Docker: Launch .NET Core",
            "type": "docker-coreclr",
            "request": "launch",
            "preLaunchTask": "container-build",
            "appProject": "${workspaceFolder}/bbt.api.card.csproj",
            "dockerBuild": {},
            "dockerRun": {
                "ports": [
                    {
                        "hostPort": "6000",
                        "containerPort": "80"
                    },
                ]
            }
}
```
2.

Action: debugCoreClr
Error type: 1
Error Message: Process exited with code 1

Version: 0.9.0
OS: win32
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:1:530610
ChildProcess.emit events.js:200:13
maybeClose child_process.js:1021:16
Socket.<anonymous> child_process.js:430:11
Socket.emit events.js:200:13
Pipe.<anonymous> net.js:586:12
```

</details>

**Comment by philliphoff** [comment]
@ukaratas Is this issue repeatable? Are you able to build the image for that project from the command line (e.g. `docker build -f <path to Dockerfile> <path to build context>`?  What version of Docker are you using on Windows?

**Comment by ukaratas** [comment]
Thanks Phillip,
When I try to build on terminal with ```docker build -t ugurkaratas/bbt-card-api:latest .``` i get ```Successfully built 3f290fde9d32
Successfully tagged ugurkaratas/bbt-card-api:latest``` so i get my image successfully and try to run it with ```docker run -d -p 8080:80 --name myapp ugurkaratas/bbt-card-api```,  it runs successfully.

Version information is;
```PS C:\Users\du04664\Desktop\Project\CardAPI> docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
 Kubernetes:
  Version:          v1.17.0
  StackAPI:         Unknown```

**Comment by philliphoff** [comment]
@ukaratas I just noticed that you have a `preLaunchTask` attached called `container-build`?  Is that task intended to build the container prior to debugging?  The debug configuration itself builds the image (customized via the `dockerBuild` object in the configuration object), so that shouldn't be necessary and, perhaps, the image being built twice may be causing the error.

That said, the `debug-coreclr` debug configuration is the "old" way of debugging within a docker container.  You can scaffold configuration/tasks for the "new" way of debugging (introduced in 0.9.0) through the "Docker: Initialize for Docker debugging" command in the command palette.  You might try that and see if you have more success (or let us know if you still have issues).
