### ISSUE TITLE
Node.js Docker Build dialog does not prompt for tagging

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#1536]
In following the [Deploy to App Service with VS Code:](https://docs.microsoft.com/en-us/azure/javascript/tutorial-vscode-azure-app-service-node-02)
Steps to reproduce:

1. npx express-generator myExpressApp --view pug -–git
2. ctrl+shift+p:  add docker files - No docker compose - port 3000
3. ctrl+shift+p: docker build

This command will then run immediately and give no prompting of how to tag the image. 

Is there documentation or clear statements inside of VS Code to tell the user that a tasks.json file is created (for Node.js at least) and the way to create auto-tagging is to add "tag" to the "dockerBuild" section of this file?

**Comment by philliphoff** [comment]
This is intentional.  If the folder has a Docker build task in `tasks.json` associated with the Dockerfile, that build task will simply be executed (to produce the image).  If the task specifies a tag, that tag will be used.  If no task exists, then the extension will generate a generic Docker build command (which currently includes prompting the user for a tag).

There is [documentation](https://github.com/microsoft/vscode-docker/wiki/Extension-Properties-And-Tasks#dockerbuild-object-properties) related to configuring the Docker build task.  Whether that's sufficient is arguable; there's always more we can do.

There may be several options for improving the experience, and it may be a combination of these:

 - Improve the documentation, with more entry points to the task configuration guides.
 - Remove the prompt for tag in the "fallback" case (for the sake of consistency).  It's not required, and you can argue that it's too early for the user to worry about a proper tag for the image (as that's usually a push-time decision).  Doing that may make the experience better for new Docker users, who aren't familiar with the implications of tag names.
 - Scaffold a default tag to build tasks, to make it more apparent as to where one configures tasks, when they decide they want to do so.

**Comment by ucheNkadiCode** [comment]
Those are great suggestions, I believe all 3 should be done. Although properly tagging an image may be a push time decision, tagging an image is a very common use case across most Docker users at some point. For this reason, I believe it's important to have clear discoverability inside VS Code and consistency (in all docs and language selections) across the tagging experience whether it's creating a tasks.json or prompting the user for tagging upon each Docker Build in command pallete.

**Comment by bwateratmsft** [comment]
Related to #1596

**Comment by bwateratmsft** [comment]
@ucheNkadiCode I looked a bit and didn't find anything in those docs inconsistent with the current experience, is there anything left or has it all been updated?

**Comment by ucheNkadiCode** [comment]
I think what it came down to was a user already had a build task in their tasks.json, it would already declare the tag name within it. This was why node.js was not prompting for tagging. I will close this issue
