### ISSUE TITLE
Pushing Image to Registry of Choice

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#1539]
When pushing an image, there is no option or prompt to push the image to a specific registry. Either the image is pushed to default or, in the case of Azure Container Registry, the user is required to tag their image rigidly (someusername.azurecr.io/someexpressapp:latest) to override the default registry selection. I believe it should be made easier for a user push an image tagged in any manner to their registry of choice.

This experience could be improved by having a **"Push Default"** and **"Push to..."** option. "Push Default" would behave just like the current push command. "Push to" would open a dialog to select which registry the user wants to use and optionally set a default.

**Comment by karolz-ms** [comment]
@ucheNkadiCode note that tagging the image before pushing it to a repository is how Docker works. In other words, *tagging is an essential part of sharing an image via a repository*. E.g. see https://docs.docker.com/engine/reference/commandline/tag/ (last paragraph of the topic).

Since a tag is always required, we need to think what *Push to...* operation would exactly entail. I.e. would it always involve creating new tag, or maybe allow the user to choose from a set of existing tags that point to external repositories?
