### ISSUE TITLE
docker-compose.yml not being recognized

### ISSUE THREAD

**Issue by joaocc** [Microsoft/vscode-docker#154]
This happens on v0.0.20, on the latest version of VSCode (1.17.2).
If I select a "docker-compose.yml" or "docker-compose.anything.yml" file, VSCode marks it as "yaml" syntax.
Any suggestion?
Thx

**Comment by chrisdias** [comment]
Nothing has changed here as far as I can tell... what were you expecting?  

The extension adds to the `yaml` language service if the file is named `'**/[dD]ocker-[cC]ompose*.{yaml,yml}'`:

``` javascript
export const COMPOSE_FILE_GLOB_PATTERN = '**/[dD]ocker-[cC]ompose*.{yaml,yml}';
```

In this case, the extension adds completions, including completions for images from DockerHub, as well as hovers.

![image](https://user-images.githubusercontent.com/1487073/31980106-17c92012-b8e6-11e7-81cd-32dcae0003f0.png)

Let me know what you were expecting here. I'll close for now as "by design" and reopen if necessary. Thanks!

**Comment by joaocc** [comment]
Hi,
I'll try to explain.
Right now, when I open a docker-compose.yml file, VSCode detects it as YAML (bottom right) (I would expect it to mention something like Docker, docker-compose)
![image](https://user-images.githubusercontent.com/2837860/31988876-73d0ca2c-b968-11e7-9164-2b23c614cb75.png)

Then, the autocompletion doesn't expand like what you show on your last comment:
![image](https://user-images.githubusercontent.com/2837860/31988923-9c91347e-b968-11e7-8e78-4a4236ce5f1f.png)

From your post, it seems that there may be something wrong with my install or config or VSCode.
Any ideas?
Thx
