### ISSUE TITLE
Docker Build Incorrect Date

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#1556]
Each time I build my Docker image, it successfully build but does not update the date it was last created. Right now it is saying that I built the image 4 days ago. I tried changing the tag from latest to trial, the image successfully built, I can now see both latest and trial, and both are saying I built the image 4 days ago. 

This may have something to do with the fact that I have had this particular VS Code editor open for the past 4 days at least. Is the docker extension date reading from when the instance of VS Code was opened?

![image](https://user-images.githubusercontent.com/20650058/72282911-8486b580-35f2-11ea-80ae-c74ea5f08c99.png)

As you can see I have just built the image on 1/13.

**Comment by philliphoff** [comment]
@ucheNkadiCode Because of the way that Docker caches intermediate layers when building images, if the application itself hasn't changed between builds, "building" an image becomes a no-op as Docker simply reuses the existing layers, so it's not uncommon to see an earlier timestamp on an image that was just "built".  In your case, the Docker build was effectively just a "tag" command on an existing image.
