### ISSUE TITLE
not running in VS code

### ISSUE THREAD

**Issue by madilraza** [microsoft/vscode-docker#1569]
Repro steps:

1.
2.

Action: vscode-docker.images.prune
Error type: Error
Error Message: Failed to connect. Is Docker installed and running? Error: connect ENOENT //./pipe/docker_engine

Version: 0.9.0
OS: win32
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.t.wrapDockerodeENOENT extension.bundle.js:1:389351
processTicksAndRejections task_queues.js:89:5
```

</details>

**Comment by philliphoff** [comment]
@madilraza Is this issue repeatable? If so, can you provide repro steps?  Are you able to use Docker on the command line (e.g. list images, containers, etc.)?

**Comment by josersleal** [comment]
same issue here and docker works fine on cli.
using docker toolbox in windows so that could be the issue
Client:
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.7
 Git commit:        74b1e89e8a
 Built:             Wed Jul 31 15:18:18 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by dbreshears** [comment]
@madilraza ,  please ensure Docker is running correctly on the command line.   If it is and you still have issue with VSCode, please re-activate
