### ISSUE TITLE
[Suggestion] Show the container name rather than image name in 'Containers' view 

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1577]
**OS:** All
**Build Version:** [20200122.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13983&view=results)
**Regression:** Not a Regression

**Repro Steps:**
1. From command line, type "docker pull registry".
2. Images view->registry:latest->Run.
3. Check the container name in "Containers" view.

**Actual:**
Show the image name in container view.
![image](https://user-images.githubusercontent.com/45614674/72893509-27a6a000-3d54-11ea-9cdb-66ae82e4c707.png)

**Suggestion:**
Show the container name in "Containers" view.

**Comment by philliphoff** [comment]
@v-ruizh While I can't be sure, I believe labeling containers by their tag by default was intentional, perhaps because most containers are implicitly named by Docker and so the name is relatively unimportant, whereas the tag helps identify the type of container.  In any case, users have a lot of flexibility in how containers are labled; if they choose, they can configure it (using the "gear" icon at the top of that tree view) to select a new primary label (such as the container name).

**Comment by philliphoff** [comment]
Let us know if you think there's a strong argument for changing that default; if so, feel free to reopen this issue.
