### ISSUE TITLE
Add setting for "--project-name" or COMPOSE_PROJECT_NAME

### ISSUE THREAD

**Issue by cecilemuller** [microsoft/vscode-docker#1593]
I don't see a way to set the project name for Compose (preferably in settings.json) ?

**Comment by philliphoff** [comment]
@cecilemuller Good timing!  We're in the midst of planning a broader effort to allow customization of the various Docker (CLI) commands that we perform. See #1596 for our proposal and let us know if you have any feedback.

**Comment by cecilemuller** [comment]
@philliphoff  Sounds good!

Then in that case, the project name setting could be a token usable in `docker.commands.composeUp` and `docker.commands.composeDown` (I'm guessing there will be a `docker.commands.composeRestart` too although not listed in the proposal).

**Comment by philliphoff** [comment]
@cecilemuller To begin with, until we have more feedback on what a generated or set project name should be in order to justify a specific token, I'd suggest simply adding workspace-level settings with values like:

 - `docker.commands.composeUp`: `docker-compose up --project-name my-project -f ${configurationFile} ${detached} ${build}`
 - `docker.commands.composeDown`: `docker-compose down --project-name -f ${configurationFile}`

Do you think that would work for your scenario?

For restart, the extension actually doesn't issue a `docker-compose restart` command; on restart the extension simply performs a `docker-compose down` and then an immediate `docker-compose up`.  (I'm not sure why it was done this way, to be honest.) That said, I would expect that any additional Docker CLI commands we add to the extension will allow customization in line with the proposal.

**Comment by cecilemuller** [comment]
Sure, that would work too.

**Comment by bwateratmsft** [comment]
Hey @cecilemuller , the command customization is now available in [Docker extension version 1.0.0](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker).

**Comment by cecilemuller** [comment]
Thanks @bwateratmsft
