### ISSUE TITLE
List Application Host ports that are in use to the output window

### ISSUE THREAD

**Issue by dbreshears** [microsoft/vscode-docker#1602]
When  debugging , output the Application Host ports that are currently in use.

**Comment by bwateratmsft** [comment]
So the most appropriate place to put this output is in the Debug Console window, but in order to do that would require a non-read-only `DebugAdapterTracker`. Unfortunately that [isn't supported](https://code.visualstudio.com/api/references/vscode-api#DebugAdapterTrackerFactory) (emphasis mine):
>The method 'createDebugAdapterTracker' is called at the start of a debug session in order to return a "tracker" object that provides **read-access** to the communication between VS Code and a debug adapter.

The only other sensible place to put it the output is in the Docker output window, but this wouldn't be very visible since the Debug Console window is the one that is open.
