### ISSUE TITLE
Fail to execute command "Run as task in Azure" from “taskmulti-multiregistry.yaml”

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1608]
**OS:** Windows
**Build Version:** [20200206.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=14471&view=artifacts&type=publishedArtifacts)

**Steps to reproduce:**
1. Download the [acr-build-helloworld-node](https://github.com/Azure-Samples/acr-build-helloworld-node) project.
2. Open this project in VS Code.
3. Right click the "taskmulti-multiregistry.yaml" file and execute "Run as task in Azure".
4. Check the result.

**Expect:**
Execute the command "Run as task in Azure" successfully from “taskmulti-multiregistry.yaml”.

**Actual:**
Fail to execute command "Run as task in Azure".
![image](https://user-images.githubusercontent.com/45614674/74014603-fd96e400-49c9-11ea-9b28-2a4d5feed943.png)

**More info:**
This issue does not reproduce for "taskmulti.yaml" file.

**Comment by northtyphoon** [comment]
@rosanch

**Comment by rosanch** [comment]
@v-ruizh 
This YAML file requires Tasks set feature which is not supported by the extension. So “Values.regDate” it’s empty and it’s failing to create the image because of bad formatting (starting with '/'). For more information, you can refer to this wiki https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-multistep-task#create-a-multi-registry-multi-step-task

If you wish to use variables with the docker extension. I recommend you to use the custom alias formatting in your YAML file  for more info you can refer to https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-reference-yaml#aliases

**Comment by rosanch** [comment]
@v-ruizh I'm closing the bug, please reopen the issue if you still have any issues.
