### ISSUE TITLE
Unable to debug ASP.NET Core app on Ubuntu 18.04 LTS (client: Windows 10)

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode-docker#1634]
Repro steps:

One needs an Ubuntu 18.04 machine with Docker installed (used Docker engine version 19.03.6). Machine should be accessible via SSH. Also install .NET SDK version 3.1 or newer (used SDK 3.1.101).

1. Use Remote-SSH extension to connect to the Ubuntu machine via SSH
2. Follow ASP.NET quickstart https://code.visualstudio.com/docs/containers/quickstart-aspnet-core and try debugging

Expected: debugging should work
Actual: an error message that says "Unable to acquire the .NET Core debugger"

**Comment by bwateratmsft** [comment]
I'm also able to reproduce; even with having installed the C# and Docker extensions within the SSH session.

**Comment by bwateratmsft** [comment]
I found that the debug download code correctly identified the OS as Linux, and used the following command:
`/home/bwaterloo/.vsdbg/getvsdbg.sh -v latest -r linux-x64 -l "/home/bwaterloo/.vsdbg/linux-x64/latest"`
When I ran that manually it gave an error that `unzip` was not installed. Once I installed `unzip` (and separately, reinstalled the not-snap version of Docker due to https://github.com/moby/moby/issues/34427), everything worked.

IMO this issue probably belongs to the vsdbg team; they can decide whether to auto-install `unzip` or what the official guidance should be.

**Comment by bwateratmsft** [comment]
I sent an email to the debugger folks to see what their guidance is.

**Comment by karolz-ms** [comment]
The guidance is the user should ensure that unzip utility is installed. 

Per @bwateratmsft 
> The “unzip is not here” message was really clear from the output of GetVsDbg.sh when I ran it manually, but our extension does not emit much of anything—no command line, no install output, etc. I think there’s definitely room for us to improve with that. IMO we should move that command execution to terminal, if possible.
