### ISSUE TITLE
Task to execute Docker Images build is undefined

### ISSUE THREAD

**Issue by prateikjaiswal** [microsoft/vscode-docker#1647]
Does this occur consistently? Yes
Repro steps:
1. In Visual Studio Code open Command Palette 
2. Run command => Docker Images: build image
3. Select workspace

Action: vscode-docker.images.build
Error type: 5
Error Message: Task to execute is undefined

Version: 0.10.0
OS: darwin
OS Release: 19.3.0
Product: Visual Studio Code - Insiders
Product Version: 1.43.0-insider
Language: en

**Comment by bwateratmsft** [comment]
Thanks @prateikjaiswal, this looks similar to the later issue found in #1474.

**Comment by bwateratmsft** [comment]
I think the root cause of this particular bug is that calling `vscode.tasks.executeTask` on workspace-defined tasks fails, with that error. Our plan for #1474 was to only ever scaffold workspace folder tasks, which resolves this particular error, but still leaves another problem:

1. Create a workspace with multiple folders, each with a Dockerfile, both called "Dockerfile"
1. Add Docker build tasks for only _one_ of those Dockerfiles
1. Right click > Build Image on the _other_ Dockerfile
    1. Side note: it prompts for workspace folder here, which should be obvious given the selected Dockerfile
1. It will find and execute the build task for the wrong Dockerfile (since the task matches against `${workspaceFolder}/Dockerfile`, and even though it's in a different workspace folder, the `${workspaceFolder}` token gets replaced with the chosen one from above

**Comment by bwateratmsft** [comment]
A fix for this has been released.
