### ISSUE TITLE
The "--rm -f" still appears on the command line when building a Dockerfile

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#1674]
**OS**: Windows, Mac
**Build Version:** [20200227.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15381&view=results)

**Repro Steps:**
1. Open the setting.json  --> Add the setting of "docker.commands.build" with the default value.
2. Remove "--rm -f" from the default value.
![image](https://user-images.githubusercontent.com/34729092/75454555-74206500-592a-11ea-9392-a66faf15f548.png)
3. Open a node.js project --> Build the Dockerfile.

**Expect:**
Succeed to build and don't display "--rm -f" on the command line.

**Actual:**
The "--rm -f" still appears on the command line.
![image](https://user-images.githubusercontent.com/34729092/75454582-800c2700-592a-11ea-8059-d34bd362c91b.png)

**More Info:**
Display an error when building for a go project.
![image](https://user-images.githubusercontent.com/34729092/75454653-9ade9b80-592a-11ea-85ab-b9211625b03a.png)

**Comment by bwateratmsft** [comment]
It looks like this is the official build task running, and therefore doesn't pick up the settings customization. @v-dantch can you confirm if this was a .NET Core or Node app with a tasks.json file generated? If so it is expected to run the task from tasks.json, instead of the settings-specified command line. You can try removing the `docker-build` tasks from tasks.json, and then try doing build again (note, removing those tasks will probably break debugging for that project).

The second issue, with the Go web app, is something else...I'll take a look. That command line looks right to me...

**Comment by bwateratmsft** [comment]
It looks like this is the official build task running, and therefore doesn't pick up the settings customization. @v-dantch can you confirm if this was a .NET Core or Node app with a tasks.json file generated? If so it is expected to run the task from tasks.json, instead of the settings-specified command line. You can try removing the `docker-build` tasks from tasks.json, and then try doing build again (note, removing those tasks will probably break debugging for that project).

The second issue, with the Go web app, is something else...I'll take a look. That command line looks right to me...

**Comment by bwateratmsft** [comment]
I see what's wrong, in my test case notes I'd incorrectly said to remove `--rm -f`, when in fact only `--rm` should be removed. The `-f` is needed before `"Dockerfile"`. I've corrected the notes.

Can you try the above two scenarios again? (for the first issue, try removing the `docker-build` tasks from tasks.json, and for the second, put the `-f` flag back in before `"Dockerfile"`). Thanks!

**Comment by v-dantch** [comment]
Verified again for a .NET Core Console web app: Remove the docker-build tasks in tasks.json --> Add "docker.commands.build" setting --> Remove the --rm from the default value --> Build the Dockerfile.
Then succeed to build and there doesn't display "--rm" in command line.
![image](https://user-images.githubusercontent.com/34729092/75503329-3a7f4680-598a-11ea-8422-bfb56d3c0377.png)

More Info:

1. Work well for node.js projects.
2. Work well for go projects.
![image](https://user-images.githubusercontent.com/34729092/75503551-c2fde700-598a-11ea-931b-6609e26adada.png)

**Comment by bwateratmsft** [comment]
Awesome! Glad it's working now.
