### ISSUE TITLE
how do i deploy a docker image on visual studio code to an app service on azure. I am getting the following errors when i try. Please advice 

### ISSUE THREAD

**Issue by tobioge1** [microsoft/vscode-docker#1702]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.deployImageToAzure
Error type: NoResouceFoundError
Error Message: No matching resources found.

Version: 0.10.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
RegistriesTreeItem.<anonymous> extension.bundle.js:1:706749
o extension.bundle.js:1:700627
```

</details>

**Comment by bwateratmsft** [comment]
@EricJizbaMSFT The `NoResouceFoundError` [sic] is in vscode-azureextensionui. Do you know why it would be getting thrown here?

**Comment by EricJizbaMSFT** [comment]
It's a generic error thrown when showTreeItemPicker doesn't find a matching item. Ravi did some work related to that here for other Docker scenarios: https://github.com/microsoft/vscode-docker/pull/1565

**Comment by bwateratmsft** [comment]
@tobioge1 Due to a bug it is necessary to add the Azure registry provider, so that it appears in the Docker explorer tab. Run command `Docker Registries: Connect Registry...`. It will prompt to choose a provider for the registry, choose "Azure". Follow through any remaining prompts that occur. After that, it should allow you to go through with the `Docker Registries: Deploy Image to Azure App Service...` command.

**Comment by bwateratmsft** [comment]
@EricJizbaMSFT I found one possible fix, I wanted to run it past you. The bug is occurring because of this line, combined with the temp AzureAccountTreeItem created by the command: https://github.com/microsoft/vscode-azuretools/blob/5cac7faf9bf24b7c911dee4aa49e8e74fbcffd9f/ui/src/treeDataProvider/AzureAccountTreeItemBase.ts#L139

The command creates its own AzureAccountTreeItem, because the Azure provider may have been disconnected, but refers to the RegistriesTreeItem as its parent. The line above tells the RegistriesTreeItem to choose a child Azure SubscriptionTreeItem...but since the temporary AzureAccountTreeItem is not an actual child of RegistriesTreeItem, it fails.

So, one fix would be to call `await me.pickChildTreeItem([SubscriptionTreeItemBase.contextValue], context)` instead of `await me.treeDataProvider.showTreeItemPicker(SubscriptionTreeItemBase.contextValue, context)`. This keeps the RegistriesTreeItem out of the picture, so to speak. I tried this and was successful.

Another option would be to first walk them through the process of getting that Azure provider connected if it isn't. I haven't looked yet; I assume this would be a bit more complicated but should work. Arguably it's more "correct" since, if you're deploying to Azure App Service, you should probably have the provider connected anyway.

**Comment by EricJizbaMSFT** [comment]
`showTreeItemPicker` supports passing in a `startingTreeItem`. If you pass in the account tree item as the `startingTreeItem`, would that also "keep the RegistriesTreeItem out of the picture"?

**Comment by bwateratmsft** [comment]
Yes, that works as well. I like your idea better. :smile:

**Comment by bwateratmsft** [comment]
Created https://github.com/microsoft/vscode-azuretools/pull/667.

**Comment by bwateratmsft** [comment]
Wasn't meant to auto-close yet.
