### ISSUE TITLE
The dialog still prompt to install debugger when debugging MVC project at the second time 

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1713]
**OS:** Windows/Mac/Linux
**Build Version:** [20200304.7](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15718&view=results)

**Repro Steps:**
1. Create a .NET Core mvc app by "dotnet new mvc --name mvctest".
2. Open the project in VS Code --> Prompt to add the required assets --> Yes
3. F1 --> Type and select "Docker: Add Docker Files to Workspace" --> ASP.NET Core --> Linux --> Include optional Docker Compose files.
4. Right click the docker-compose.yml --> Select "Compose Up".
5. Open launch.json and click 'Add Configration…', and choose 'Docker .NET Core Attach (Preview)'.
6. Run the above configuration, select the running container from step4 and click yes to allow installing vsdbg on the container.
7. Disconnect this attach, then F5 and connect to the same container.

**Expect:**
There shouldn't be any prompt to install debugger.

**Actual:**
The dialog still prompt to install debugger.

**Comment by bwateratmsft** [comment]
This should be fixed by #1704 (which was not present yet in the tested build), but only as long as that same container is running. Upon compose down / compose up, the new container will not have the debugger installed, so it will have to be reinstalled again.

@ravipal do you want to keep this issue open to investigate if there's any way we can improve the latter part of this (where compose down + compose up means debugger needs to be installed again)?

**Comment by ravipal** [comment]
I will open a separate work item to improve this. This particular test should pass with the latest build.
