### ISSUE TITLE
Fail to run "python manage.py migrate" in Django Python project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1714]
**OS:** Mac
**Build Version:** [20200304.7](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15718&view=results)

**Repro Steps:**
1. Open a Python project (Django) in VS Code.
2. F1->Docker: Add Docker Files to Workspace->Python->include docker compose files.
3. F5, an error log shows during debugging. 
![image](https://user-images.githubusercontent.com/45614674/75890789-cfda7900-5e69-11ea-80e6-520e7a9f555c.png)
4. Stop debugging and run "python manage.py migrate" in this project folder.

**Expect:**
Run "python manage.py migrate" successfully.

**Actual:**
Fail to run "python manage.py migrate".
![image](https://user-images.githubusercontent.com/45614674/75891043-2e9ff280-5e6a-11ea-9de1-3e8a82c54a56.png)

**More info:**
This issue does not reproduce on Windows.

**Comment by haniamr** [comment]
This is kind of out-of-scope given that it's not really something the tooling controls/generates. However, I think the issue is that you installed django using a version of Python that is different than the one you have in the path. Can you try execute "python3 manage.py migrate"?

Here's the StackOverflow link for more info: https://stackoverflow.com/questions/42611593/how-to-solve-syntaxerror-on-autogenerated-manage-py

**Comment by v-ruizh** [comment]
@haniamr Thanks for your guidance. I can execute "python3 manage.py migrate" successfully on Mac.
