### ISSUE TITLE
Process exited with code 9 when debugging .NET Core within a container with Visual Studio Code

### ISSUE THREAD

**Issue by sgdavidw** [microsoft/vscode-docker#1761]
Hi,

I followed this document
https://code.visualstudio.com/docs/containers/debug-netcore
to try Debugging .NET Core within a container with Visual Studio Code, but didn't succeed. The error message directed me to the Github to submit this issue. would you please take a look?

Thank you,

David

Does this occur consistently? 
Repro steps:

1.
2.

Action: docker-launch
Error type: 9
Error Message: Process exited with code 9

Version: 1.0.0
OS: darwin
OS Release: 19.3.0
Product: Visual Studio Code
Product Version: 1.43.0
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:1:549589
ChildProcess.emit events.js:203:13
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment]
Hey @sgdavidw, it looks like this is the same issue as #1744. We changed the error messages to be more useful so that in the future a better message will be presented.

The issue is that the ASP.NET Core development certificate is not quite working. If you run `dotnet dev-certs https --clean` and then `dotnet dev-certs https --trust`, it should fix the problem.

**Comment by sgdavidw** [comment]
Hi, Brandon,

Thank you for the prompt response.
I ran the two commands to reset the development certificate, then tried the debugging again. It is working now.

Thank you,

David

________________________________
