### ISSUE TITLE
Error deploying Container to Azure App Service

### ISSUE THREAD

**Issue by geetika016** [microsoft/vscode-docker#1836]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.deployImageToAzure
Error type: Unauthorized
Error Message: This region has quota of 0 instances for your subscription. Try selecting different region or SKU.

Version: 1.0.0
OS: darwin
OS Release: 19.4.0
Product: Visual Studio Code
Product Version: 1.44.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:218:3620109
s extension.bundle.js:218:111335
s extension.bundle.js:157:30549
extension.bundle.js:157:31793
o extension.bundle.js:164:7083
extension.bundle.js:157:29462
B._callback extension.bundle.js:1:725962
B.t._callback.t.callback.t.callback extension.bundle.js:194:5618
B.emit events.js:203:13
B.<anonymous> extension.bundle.js:194:18478
B.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:194:17310
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by bwateratmsft** [comment]
@geetika016 Does it work in any other regions? I'm wondering if this is due to the recent Azure pressure from COVID-19...

**Comment by geetika016** [comment]
Hi, 
I tried switching regions but no luck !

**Comment by bwateratmsft** [comment]
We should investigate. Which region(s) did you try?

**Comment by geetika016** [comment]
Canada(Central)
Canada East
East US
South Central US

**Comment by bwateratmsft** [comment]
Thanks @geetika016! We'll take a look.

**Comment by geetika016** [comment]
Perfect Thanks!

**Comment by bwateratmsft** [comment]
@geetika016 I was able to deploy in a test. It looks like it could be due to Azure's quotas that are imposed depending on subscription, region, service, and some more factors: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#app-service-limits

Do you know what sort of subscription you are using? e.g. is it a free testing one, something from MSDN, paid subscription, etc.?

**Comment by geetika016** [comment]
The subscription is Pay-As-You-Go.

**Comment by bwateratmsft** [comment]
From what I can tell, there are a max of 10 free app service plans per region (with 10 app services within an app service plan), 10 shared per resource group (100 services per app service plan), and 100 basic/standard/premium/isolated per resource group (unlimited services per app service plan). You would need to look at the Azure Portal to see what is being used and if there are other quotas that are in place.

The Subscription blade has a menu where you can look through quotas and see what is in place:
![image](https://user-images.githubusercontent.com/36966225/78929280-14ac8d80-7a70-11ea-94c8-01ae806d7c1f.png)

Since this appears to be due to Azure's quotas I'll close this issue as external for now. Please let us know if you're able to find what quotas are in place. Thanks!
