### ISSUE TITLE
The image in Dockerfile is 2.1 after adding Docker files to a .NET Core 5.0 console app

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#1856]
**OS:** Windows
**Build Version:**[20200413.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=17741&view=results)
**.NET Core SDK:** 5.0.100-preview.3.20211.8

**Repro Steps:**

1. Create a .NET Core console app by "dotnet new console".
2. Open this project in VS Code-->Prompt to add the required assets-->yes.
3. F1-->Type and select "Docker: Add Docker Files to Workspace"-->.NET: Core Console-->Linux-->Include optional Docker Compose files
5. Check the image in Dockerfile

**Expect:**
The image in dockerfile should be version 5.0.

**Actual:**
The image in dockerfile shows version 2.1.
![image](https://user-images.githubusercontent.com/62053665/79197247-fc6bb280-7e63-11ea-87ac-0c1cb04b23eb.png)

**Comment by bwateratmsft** [comment]
When we implement this, we should put the determined .NET Core version into the scaffold telemetry.

**Comment by bwateratmsft** [comment]
For the fix, I think the right way is to change our regex. We should look inbetween `<TargetFramework>` (or `<TargetFrameworks>`) tags (also using regex), and look for basically `net(coreapp)?\d\.\d`, i.e. either `netcoreappx.y` or `netx.y`.

Something like this (which is probably missing escape characters somewhere):
`<TargetFrameworks?>.*net(coreapp)?(\d+\.\d+).*</TargetFrameworks?>`

It should _probably_ also be a multi-line inspection, because this is valid XML:
```xml
<TargetFrameworks>
    netcoreapp3.1;
    netcoreapp5.0;
</TargetFrameworks>
```

If there are multiple matches, we should take the highest one.

**Comment by bwateratmsft** [comment]
@ravipal can we add telemetry for the resolved .NET Core version?
