### ISSUE TITLE
[Suggestion]Add a "Browse" button after selecting "Install Docker..."

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-docker#1857]
**OS**: Windows
**Build Version:** [20200413.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=17741&view=results)
**Regression:** Not a Regression

**Repro Steps:**
1. Quit Docker Desktop  --> It prompts to install Docker.
![image](https://user-images.githubusercontent.com/34729092/79209358-e23ad000-7e75-11ea-8e1a-d7638ee41d6c.png)
2. Select "Install Docker...".

**Actual:**
Start to downloading Docker installer directly.

**Suggestion:**
Add a "Browse" button after selecting "Install Docker...". In this case, the users can browse the application locally.

**Comment by bwateratmsft** [comment]
@v-dantch Can you clarify what you mean by "browse the application locally"?

**Comment by v-dantch** [comment]
Like the repro steps, the D4W has been installed, but it is running. In this case, the users can browse to existing installation location like below screenshot:
![image](https://user-images.githubusercontent.com/34729092/79293799-23c78b80-7f07-11ea-955a-f3345e2383c4.png)

**Comment by bwateratmsft** [comment]
I understand now. For Docker, I don't think we need this--
- Storage Explorer could be installed in many different, valid locations, and if not detected we can ask the user to find where it is
- Docker has to be installed such that `docker` is on the `PATH` variable. That's how we check for it, and if it isn't present, then the product is not installed. Browsing to an existing installation is invalid in this case, because any such installation is invalid.

**Comment by v-dantch** [comment]
Got it. Thanks for your sharing.
