### ISSUE TITLE
Issue when trying to build a docker image

### ISSUE THREAD

**Issue by pedmands** [microsoft/vscode-docker#1871]
Does this occur consistently? Yes
Repro steps:

1. Add Docker Files to Workspace (successfully)
2. Docker Images: Build Image... (fails after selecting workspace folder)

Action: vscode-docker.images.build
Error type: Error
Error Message: Task not found

Version: 1.0.0
OS: darwin
OS Release: 19.3.0
Product: Visual Studio Code
Product Version: 1.44.1
Language: en

<details>
<summary>Call Stack</summary>

```
file:/workbench.desktop.main.js:3930:286
processTicksAndRejections task_queues.js:85:5
```

</details>

[Dockerfile](https://pastebin.com/rgLZpubu) 
[docker-compose.yml](https://pastebin.com/dZKzCSGP)
[package.json](https://pastebin.com/fAfPJbPF)

#### Project Files

- [Dockerfile](https://pastebin.com/rgLZpubu)
- [docker-compose.yml](https://pastebin.com/dZKzCSGP)
- [package.json](https://pastebin.com/fAfPJbPF)

**Comment by bwateratmsft** [comment]
Hey @pedmands, this looks like the same error as #1781. We think that error might in turn have been due to the same issue as #1647.

Since it prompted you to select a workspace folder I assume that means you have multiple of them. In your workspace file, there should be some tasks related to Docker (build, run), can you try moving them to `yourWorkspaceFolder/.vscode/tasks.json`, can see if this issue still occurs? If you're using debugging as well, there are probably launch configurations in that file that need to move to `.../launch.json`.
