### ISSUE TITLE
An error "EISDIR: illegal operation on a directory, read" occurs when F5ing a .NET Core 2.1 MVC project

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#1874]
**OS:** Mac
**Build version:** [20200413.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=17741&view=results)
**.NET Core SDK:** 2.1

1. Create a .NET Core MVC project by "dotnet new mvc".
2. Open the project in VS Code-->Prompt to add the required asserts-->Yes.
3. F1-->Type and select "Docker: Add Docker Files to Workspace"-->ASP.NET Core-->Linux-->Include optional Docker Compose files.
4. Go to the Debug tab in VSCode, select the "Docker .NET Core Launch"-->F5

**Expect:**
Debug successfully without error.

**Actual:**
The Terminal has an error: EISDIR: illegal operation on a directory, read.
![Screen Shot 2020-04-15 at 7 00 15 PM](https://user-images.githubusercontent.com/62053665/79443400-5c04c200-800c-11ea-82a5-bbef43083233.png)

**More info:**
This bug does not reproduce with .NET Core 3.1/5.0.

**Comment by bwateratmsft** [comment]
@v-mengwe Does this happen consistently on .NET Core 2.1 projects?

**Comment by bwateratmsft** [comment]
It looks like yes, it does. I can repro. I see what's happening.

`GetBlazorManifestLocations` is returning the project directory as the input manifest location, because `$(_GeneratedStaticWebAssetsDevelopmentManifest)` is undefined, because Blazor is only for .NET Core 3.0+. Ideally we would skip the manifest code entirely, because the project directory is not an XML file, but our current check [here](https://github.com/microsoft/vscode-docker/blob/master/src/tasks/netcore/updateBlazorManifest.ts#L71) is only checking if the path exists, not if it's also a file.
