### ISSUE TITLE
[Suggestion] Add a button to trust https certificate

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#1875]
**OS:** Mac
**Build version:** [20200413.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=17741&view=results)
**.NET Core SDK:** 2.1/3.1

1. Create a .NET Core MVC project by "dotnet new mvc".
2. Open the project in VS Code-->Prompt to add the required asserts-->Yes.
3. F1-->Type and select "Docker: Add Docker Files to Workspace"-->ASP.NET Core-->Linux-->Include optional Docker Compose files.
4. Go to the Debug tab in VSCode, select the "Docker .NET Core Launch"-->F5

**Actual:**
There is a dialog about how to trust https certificate, only a 'Learn more' button.
![image](https://user-images.githubusercontent.com/62053665/79445898-fdd9de00-800f-11ea-85b5-1ff7c9fd9591.png)

**Suggestion:**
Add a button to trust https certificate in this prompt dialog, this will convenient for user to trust the certificate.

**Comment by bwateratmsft** [comment]
Unfortunately this is not possible on Mac, we investigated at length when originally implementing it. 😞

**Comment by bwateratmsft** [comment]
I'll add the reasons why--

1. Trusting the cert requires the user to enter their password/fingerprint. We cannot use the OS UI way of doing it from a Node app, and asking them for their password directly in VSCode is unacceptable from a UX perspective, so that leaves only the terminal way.
1. We can't open an external terminal window to do it; there isn't any good way to do so on Mac.
1. We can't use a terminal inside VSCode, because:
    1. It's too easy to miss
    1. We can't await a result, since we can't see the result of anything within those terminal windows
