### ISSUE TITLE
Make constants:configPrefix configurable to support non root VSCode devcontainer on windows

### ISSUE THREAD

**Issue by luuk-codebeez** [microsoft/vscode-docker#1881]
- platform host: Windows 10 pro
- vscode: vscode-insider
- devcontainer: https://github.com/microsoft/vscode-dev-containers/tree/master/containers/docker-in-docker

I have been working with the devcontainers on windows and I prefer to run as a non-root user within the docker container. Quite some work from MS has gone into supporting a non-root user: [vscode-dev-containers]( https://github.com/microsoft/vscode-dev-containers). I have opened and closed a related issue with @Chuxel [vscode-devcontainers:277](https://github.com/microsoft/vscode-dev-containers/issues/277). This issue showed that we need root permission to access the mounted docker socket from within a docker container due to a limitation for bind mounts on windows. Our workaround was to alias `docker` with `sudo docker`.

At the moment the vscode-docker extension is broken in this context as it uses a fixed prefix "docker" for calling docker on the shell. I have not found a way to share my alias across to the context of the extension. 

in `/src/constants.ts`
If I replace:
`export const configPrefix: string = 'docker';`
with
`export const configPrefix: string = 'sudo docker';`

and build/install the extension in my devcontainer it works.

I would like this constant to be configurable via the extension settings to allow the plugin to work on Windows with a vscode devcontainer using a non-root user.

**Comment by Chuxel** [comment]
The core issue here is actually that the Docker extension accesses the Docker socket directly (via the dockerode node module) rather than using the CLI exclusively.  Therefore just doing `sudo docker` is not enough. It might be worth switching away from dockerode for this extension as well.  The Remote - Containers extension abandoned this technique because we found too many pitfalls with the approach which is why the problem does not appear there.

That said, I have a tactical workaround that uses `socat` to proxy the docker socket to address this problem.  The WIP container is here: https://github.com/microsoft/vscode-dev-containers/tree/clantz/dind-v2/containers/docker-in-docker

The README explains the trick: https://github.com/microsoft/vscode-dev-containers/tree/clantz/dind-v2/containers/docker-in-docker#enabling-non-root-access-to-docker-in-the-container

**Comment by bwateratmsft** [comment]
If something is using `configPrefix` for what to put on the command line, that is definitely a bug. `configPrefix` is for accessing the VSCode settings for the Docker extension. Changing it to `sudo docker` would break many of the extension setting lookups we do in code.

**Comment by bwateratmsft** [comment]
> It might be worth switching away from dockerode for this extension. The Remote - Containers extension abandoned this technique because we found too many pitfalls with the approach which is why the problem does not appear there.

Performance just isn't there for the CLI, which is the biggest reason (among many) we use Dockerode.

**Comment by Chuxel** [comment]
No. The problem here is that the docker socket itself is root only and changing it affects the host operating system.  From the README above:

> To enable non-root access to Docker in the container, you use socat to proxy the Docker socket without affecting its permissions. This is safer than updating the permissions of the host socket itself since this would apply to all containers. You can also alias docker to be sudo docker in a .bashrc file, but this does not work in cases where the Docker socket is accessed directly.

I understand the tradeoffs since Remote - Containers used `dockerode` up until the last few releases.  Things like being able to use the `ssh://` protocol required workarounds and didn't mirror developer expectations since things would work from the command line but not in the extension.  Just making you aware of what we ended up deciding here.

**Comment by Chuxel** [comment]
Oh, and on Linux, you can use `alias` to change docker to `sudo docker` across the board for the OS, but that doesn't solve the direct socket access problem in `dockerode`.

**Comment by bwateratmsft** [comment]
But @luuk-codebeez is reporting that changing the `configPrefix` constant to `'sudo docker'` worked; there is no way that should have worked. In fact, it would break any settings related to the explorer view and also the `docker.host`, etc. settings.

**Comment by luuk-codebeez** [comment]
thanks for the input both! It seems the situation is different from what I had in my title. I'll verify my suggestion again offline. For now I will close this ticket until I zoomed in on the issue.

In the meantime I'll also have a look at the workaround from @Chuxel.
