### ISSUE TITLE
How can we make users more aware of the features this extension offers

### ISSUE THREAD

**Issue by BigMorty** [microsoft/vscode-docker#1904]
Maybe provide links to docs/videos when new users edit Dockerfile and have not discovered other features?

**Comment by bwateratmsft** [comment]
I vote skywriting, but like, planet-sized.

**Comment by bwateratmsft** [comment]
@dbreshears Aside from skywriting and the toast for Dockerfile-edit-only users do we have any concrete ideas of what we want to do?

**Comment by karolz-ms** [comment]
Love the skywriting idea, I can help with that ☺️

**Comment by BigMorty** [comment]
Stop with the skywriting! The current idea is to prompt a small amount of users that edit a Dockerfile in hopes to raise awareness of other features the extension offers. We have heard from many users they don't know what else they can do with the extension.

**Comment by bwateratmsft** [comment]
@BigMorty - do you have specifics in mind for who to show it to (what are the activity criteria), and what to show?

**Comment by wjgeorge** [comment]
Awesome presentation at Dockercon by Brian Christner (https://github.com/vegasbrianc)

https://docker.events.cube365.net/docker/dockercon/content/Videos/4YkHYPnoQshkmnc26

**Comment by PavelSosin-320** [comment]
Everybody today can open **Youtube** and find several dozens of presentations talking about what can be done by means of manipulations with Dockerfile, compose-files, charts, etc. The issue is always what should be done correctly to solve a certain problem in a certain scenario.  This is the art of software development. De-facto Youtube is the best advertising channel but it can't replace **good professional contextual on-line documentation in the style explain-selected.**

**Comment by bwateratmsft** [comment]
Discussed offline.

Criteria: 3+ days of activity, 0 days of non-edit activity.
Show: a toast

@BigMorty will provide an aka.ms link and text for the toast and button.
