### ISSUE TITLE
Can't select other registry to push if there is a registry connected in Docker view

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1919]
**OS:** Windows
**Build Version:** [20200427.9](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=18373&view=results)

**Repro Steps:**
1. Connect "Azure Container Registry" in Docker view.
2. F1->Docker Images: Push->Select an image.
3. Check if there is a "Connect Registry..." to select other registry.

**Expect:**
There is a "Connect Registry..." to select other registry.

**Actual:**
There is no "Connect Registry..." to select other registry, the default registry is Azure Container registry. Can't select other registry to push unless disconnect the "Azure Container Registry" from Docker view.
![image](https://user-images.githubusercontent.com/45614674/80471259-c0f9d980-8975-11ea-8ca6-003902595736.png)

**Comment by bwateratmsft** [comment]
@ucheNkadiCode I think this behavior is fine since most people would have only one registry connected. It happens because the registries view has only one root node--Azure--so it doesn't need to ask, and therefore doesn't.

What do you think?

**Comment by ucheNkadiCode** [comment]
@bwateratmsft, So I understand the use r is saying if they haven't connected to both Azure and say Dockerhub, then during the push command they only receive the options to connect to Azure registries. I think this was intented so that users don't see connect a registry during the push flow, (however I wouldn't be opposed to this behavior). The user is still able to add an extra connection from the treeview. I think as you've mentioned most users interact with the treeview where possible

**Comment by bwateratmsft** [comment]
Yes, I expect most (all?) people using registries use the tree view. The "Connect Registry" command is always available in the tree view and the command palette.

I'll resolve this one as by-design. Most people would use only one registry, so skipping the "Connect Registry" prompt will save them a step.
