### ISSUE TITLE
registry conected but eror 405

### ISSUE THREAD

**Issue by NA3** [microsoft/vscode-docker#1927]
push image ok with left click on image by adding (Kore) project to the uri
using ssh-remote

![Sans titre4](https://user-images.githubusercontent.com/3059879/80600178-4d66d380-8a2c-11ea-911b-b5f07fc514ca.png)
![Sans titre](https://user-images.githubusercontent.com/3059879/80599868-e6e1b580-8a2b-11ea-8bcb-31b6ae7c1aec.png)
![Sans titre2](https://user-images.githubusercontent.com/3059879/80599929-f52fd180-8a2b-11ea-8a90-236fc95b874a.png)
![Sans titre3](https://user-images.githubusercontent.com/3059879/80599941-f8c35880-8a2b-11ea-9842-f380bd0603f7.png)
![chad](https://user-images.githubusercontent.com/3059879/80599359-17751f80-8a2b-11ea-8dd5-333348b6b662.png)

but have eror 405 on registry .
Regard.

**Comment by bwateratmsft** [comment]
`harbor.korporate.org` looks like a monolith registry with namespaces (similar to Docker Hub and GitHub). Because these registries are not fully [Registry V2 API](https://docs.docker.com/registry/spec/api/) compliant (they do not implement the `_catalog` endpoint), we cannot connect to them with the generic provider.

Support for these is being tracked in #869, but you would need to file an issue to the maintainers of `harbor.korporate.org` to support that `_catalog` endpoint.
