### ISSUE TITLE
Syntax is not working if the name is not "Dockerfile"

### ISSUE THREAD

**Issue by riveryc** [Microsoft/vscode-docker#193]
Hi, as reading the file https://github.com/Microsoft/vscode-docker/blob/fb97733640fae72d4098c021dbf08198a0a3e13b/dockerExtension.ts#L43-L44

I think if I'm using "Dockerfile-centos" it should also give me the syntax highlighting for it, however it didn't happen to me:
![image](https://user-images.githubusercontent.com/12391265/34140230-6a1290c0-e4cd-11e7-812a-157cb30a579f.png)

Please correct me if I'm wrong, or maybe I got something didn't setup correctly?
The version for this extension I'm using is 0.0.22

Thx
R

**Comment by chrisdias** [comment]
We've gone back and forth on this (see #134) issue unfortunately. Perhaps the right answer is to make the DOCKERFILE_GLOB_PATTERN and COMPOSE_FILE_GLOB_PATTERN configurable so that users can set up how they want to do it.

@riveryc in the meantime, you could add something like this to your workspace or user settings:

``` json
    "files.associations": {
        "Dockerfile-centos": "dockerfile"
    }
```

**Comment by riveryc** [comment]
@chrisdias Thanks so much for this workaround. It's working now as expected. :)

River
