### ISSUE TITLE
“Docker Container: Restart” using command palette should only show running containers

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1942]
**OS:** All
**Build Version:** [20200505.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=18767&view=results)

**Repro Steps:**
1. Run "docker run hello-world" --> Make sure there is a stopped "hello-world" container .
2. Check the context menu of the stopped "hello-world" container --> Make sure there is no "Restart".
3. F1 --> Type "Docker Container: Restart" --> Check the listed result.

**Expect:**
There is no stopped "hello-world" container.

**Actual:**
Still list stopped “hello-world” container.
![image](https://user-images.githubusercontent.com/45614674/81156242-528dca80-8fb8-11ea-9ce9-bc79c50befd3.png)

**Comment by bwateratmsft** [comment]
This is by-design. In the context menu, it shows only "Start" because only the one container is selected (and it is stopped, so "Start" is the right term). In the palette quick pick list, it shows both, because the running container can be restarted and the stopped one can be "restarted" (but really that means started).
