### ISSUE TITLE
Succeed to remove an image which is being used by a running container

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#1944]
**OS:** All
**Build Version:** [20200505.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=18767&view=results)

**Repro Steps:**

1. From the command-line, type: docker run -d -p 5000:5000 registry:latest
2. Check have a running container
3. Image--> Right click "registry"--> Remove

**Expect:**
Fail to remove this image with an error "it is being used by a running container".

**Actual:**
Succeed to remove this image without any error.

**Comment by bwateratmsft** [comment]
This is by-design due to the change for #1529. In the past we removed images by ID, which would remove the image and all of its tags, but would fail if there child images or running containers. Since the user is choosing the image by _name_, we changed to remove the image by name. With that change, only the selected tag is removed (and if there are no tags left, no child images, and no containers, then the image will be removed). The tag can be removed without needing to stop a container.
