### ISSUE TITLE
Initial debugging is still performed after canceling it by selecting "×" in notification

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#1945]
**OS:** All
**Build Version:** [20200505.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=18767&view=results)

**Repro Steps:**

1. Create a .NET Core MVC project by "dotnet new mvc".
2. Open the project in VS Code --> Prompt to add the required assets --> Yes
3. F1 --> Type and select "Docker: Add Docker Files to Workspace" --> ASP.NET Core -->linux--> Include optional Docker Compose files.
4. Delete some of the Docker ones from tasks.json and launch.json
5. F1-->Docker: Initialize for debugging…--> ASP.NET Core
6. Pop up a notification--> click "×" to cancel this action.
![image](https://user-images.githubusercontent.com/62053665/81168136-026b3400-8fc9-11ea-9695-9d8469495cbf.png)

**Expect:**
The tasks.json and launch.json is unchanged.

**Actual:**
Initial debugging is still performed, the deleted sections are added for tasks.json and launch.json.

**More Info:**
Choose "No" when pop up the prompt, all deleted tasks will also be recreated.
![image](https://user-images.githubusercontent.com/62053665/81168225-2d558800-8fc9-11ea-84d6-561cb4af80ee.png)

**Comment by bwateratmsft** [comment]
This is partly by design. There are multiple tasks / launch configs to create, and we decide if there are existing ones based on label--if one exists with the same label, we will prompt. However, if nothing exists with the same label, we will add it regardless--this is intentional, otherwise the user could end up with tasks we expect but are not present. So, clicking "No" will not overwrite existing tasks, but it will add back any tasks that are removed.

Clicking X should probably result in a `UserCancelledError`, but currently does not. However I don't think that is very serious.

**Comment by bwateratmsft** [comment]
We discussed this internally and we think that the current behavior (where 'x' is equivalent to 'No') is correct here. Cancelling could have unpredictable end results, because the user could end up with a half-scaffolded project.

In any case, there is no risk of unintended data loss, so the severity is very low.
