### ISSUE TITLE
Explorer is not responsive for newly created remote SSH Docker Context

### ISSUE THREAD

**Issue by BigMorty** [microsoft/vscode-docker#1947]
I then tried to use the command line to SSH into the machine directly, that is when I got this prompt:

![image](https://user-images.githubusercontent.com/947510/81219657-f2d1f800-8f94-11ea-8120-a3357807a436.png)

I answered 'yes' and the SSH connection was made. I was then able to use the Context in VS Code and the panels refreshed as expected. I found the following StackOverflow item that discuss this, it has to do with the ~/.ssh/known_hosts file.
https://stackoverflow.com/questions/3663895/ssh-the-authenticity-of-host-hostname-cant-be-established

Is there a way we can alert the user to this issue?

**Comment by bwateratmsft** [comment]
@karolz-ms we should put a timeout on Dockerode requests; they shouldn't take forever...

**Comment by bwateratmsft** [comment]
It looks like `StrictHostKeyChecking` is [_not_ enabled by default](https://github.com/mscdex/ssh2/issues/471), so I'm guessing it must be a system default. There's no option we can give to `ssh2` to disable it. The best we can do is a timeout error, and show a hint if it's an SSH host that it may be due to this.

That said, this issue would have existed since 0.9.0 when SSH support was first added, and nobody has raised it, so I wouldn't try to rush something into 1.2.0. @BigMorty

**Comment by karolz-ms** [comment]
I chatted about this with @BigMorty earlier today, definitively not a 1.2.0 issue.

Disabling `StrictHostkeyChecking` is out of question as it pretty much opens the door wide for MITM attack.

Like @bwateratmsft said, we need a timeout for Dockerode requests, plus a user warning, plus maybe some sort of back-off for the refresh rate when things go south. This should help not only with this issue, but also with other intermittent-network-connectivity issues.

**Comment by bwateratmsft** [comment]
Refresh backoff might even be overkill, but I agree.

**Comment by BigMorty** [comment]
Agree not a 1.2 issue but we should do at least the timeout and message for 1.3. Can we check to see if the remote host is in the known_hosts file?

**Comment by bwateratmsft** [comment]
Yes, that should work.

**Comment by bwateratmsft** [comment]
The fix for this is now released in 1.3.0.
