### ISSUE TITLE
Require secondary authentication on MFA enabled account

### ISSUE THREAD

**Issue by conradwt** [microsoft/vscode-docker#1953]
When I enter `Docker ID` and `Access Token`, I'm seeing the following message:

Incorrect Authentication Credentials

**Comment by conradwt** [comment]
I was able to resolve the issue that I was having authenticating to the Docker Hub registry by using the `person access token` instead of the `access token`.  There should be some additional guidance here.  For example, the modal looks this way today:

![Screen Shot 2020-05-07 at 2 45 32 PM](https://user-images.githubusercontent.com/20219/81347893-e374ac80-9071-11ea-9dda-7b64e1381e61.png)

Thus, I recommend changing the wording to something similar to the following to cover the case where people are using MFA:

Enter your password or personal access token (Press 'Enter' to confirm or 'Escape' to cancel)

**Comment by bwateratmsft** [comment]
Similar to #1968 (which is for GitLab)

**Comment by conradwt** [comment]
@bwateratmsft Actually, this issue relates to Docker and not Gitlab.  Thus, these extensions shouldn't be considered the same because we are trying to authenticate against two different systems here.  Next, I can use my `personal access token` with the VS Code Docker extension but the interface needs to change to be clear to the user.  I'm sure that Gitlab extension has its own client UI and flow but I wouldn't consider the two issues the same.

**Comment by bwateratmsft** [comment]
They're definitely not the same--as you say, this one is for Docker Hub, the other for GitLab--but both deal with using access tokens as the secret to authenticate with instead of passwords. We probably need changes to deal with that scenario better; for example, if no username is present we will not try to authenticate at all, but access tokens often do not need a username associated.
