### ISSUE TITLE
The Docker view in local instance can’t switch to remote Docker assets after using remote context

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#1958]
**OS:** Windows
**Build Version:** [20200507.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=18907)

**Repro Steps:**
1. Create an Ubuntu 18.04 LTS machine with SSH access--as a remote machine.
2. Install Docker in this Linux machine.
3. In local machine, install Remote-SSH extension in VS Code local instance.
4. Connect to the remote Ubuntu machine via SSH in VS Code.
5. Switch to the VS Code local instance use 'docker context' command to create a context for connecting to the remote machine:
docker context create --docker "host=ssh://username@machineIP" one
6. Switch Docker context to the remote machine one.
7. Check the Docker view in the VS Code local instance and check the image and container from Terminal.
_docker ps
docker images_

**Expect:**
Docker view in the VS Code local instance shows Docker assets on the remote machine.

**Actual:**
Docker view in the VS Code local instance shows the local Docker assets.
![test1](https://user-images.githubusercontent.com/45614674/81399250-4a22c480-915d-11ea-8b97-d4034d06df36.png)

**Comment by bwateratmsft** [comment]
We should investigate for 1.2.0.

**Comment by karolz-ms** [comment]
Based on the error from `docker images` command (vide the screenshot) looks like there is some connectivity issue with the remote machine Docker endpoint.

**Comment by karolz-ms** [comment]
What I found out was the client machine (Windows) was in a weird state, where `ssh` and `docker` CLI were able to connect to the server machine, but VS Code Docker extension was not. 😕 

Debugging into Docker extension I noticed that SSH handshake timeout was occurring because `ssh2` lib could not negotiate a common authentication mechanism. SSH agent did have a client identity for the server machine, but **it was wrong identity**. Once I added correct identity, everything started to work as expected.
