### ISSUE TITLE
docker compose ports should map local and host

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-docker#1974]
Issue Type: <b>Bug</b>

when generating a docker-compose file for a node app, you get:

``` yaml
ports:
  - 3000
```

When trying to browse the running app I have to inspect the container to figure out what port it was mapped to on the host.

Suggest to simply map `3000:3000` so that the user can easily access the running app. 

``` yaml
ports:
  - 3000:3000
```

Extension version: 1.2.0
VS Code version: Code - Insiders 1.46.0-insider (e88b8d32aa7233f6cb3665f6dae9fa78b1e8aafb, 2020-05-13T08:04:48.706Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (4.59GB free)|
|Process Argv|. -r|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bwateratmsft** [comment]
This is intentional. We avoid this wherever possible because of port conflicts. In VS, one of the number one causes of failure was port conflicts (a couple percent of all F5s failed due to this). It was easier and way higher success to just use `-P` (for single Dockerfile) or the container-side port alone (for Compose). When we made that change, port conflict errors dropped essentially to zero.

As far as the UX goes after that, we have features in the VSCode extension to abstract away the "what is the port?" problem:
1. In debugging the browser is opened automatically
1. "Browse Container" command to enable right-click open-a-browser

**Comment by chrisdias** [comment]
Ok, I didn't see the "Open in Browser" command on the container, so I guess that's the best compromise. Thanks!
