### ISSUE TITLE
How can I include the .net core debugger in docker? 

### ISSUE THREAD

**Issue by liang2zhu1** [microsoft/vscode-docker#2008]
Basically I want to avoid the need to run below every time I rebuild image, is there a base image I can use or a specific step I can include in Dockerfile? 

```
Attaching to container requires .NET Core debugger in the container. Do you want to copy the debugger to the container?
```

**Comment by bwateratmsft** [comment]
Related to #1717

**Comment by bwateratmsft** [comment]
So, if you have only one project to run, you're best off using the "Docker .NET Core Launch" instead of the attach configuration. Otherwise, up'ing `docker-compose.debug.yml` instead of `docker-compose.yml` will volume map the debugger from the local machine into the container, and the prompt will not happen.

If you haven't already done it, the easiest way to get the debugger in the right place is to run "Docker .NET Core Launch" once. This will download and install vsdbg into your user profile, along with a magic script that deals with the Alpine vs. not-Alpine debuggers. The folder will look like this:
![image](https://user-images.githubusercontent.com/36966225/82590951-94983e00-9b6c-11ea-81fe-5c656f538ee2.png)

It would also be reasonable to create your own base image that contains the appropriate debugger pre-installed at `/remote_debugger/vsdbg`; then you would use `docker-compose.yml` instead of `docker-compose.debug.yml`. However, the debugger is not small, so you'd want to remove it before going to production.

**Comment by bwateratmsft** [comment]
Aside from that, all we can do is add a "Don't ask me again" option, so I'll dupe this to #1717.
