### ISSUE TITLE
Adding external source/pdb files for debugging with "Docker .NET Core Attach (Preview)"

### ISSUE THREAD

**Issue by curiousdev** [microsoft/vscode-docker#2038]
When trying out the previewed `Docker .NET Core Attach (Preview)` with the following out of box configuration (see below snippet), tooling automatically (if approved) copies the debugger into the container.

Can we have a similar "copy into running container" support for pdb and src files?

Perhaps, this is already possible? My apologies, we point me to the correct documentation. Effectively, I'm trying to get as close as possible to that F5 debug experience we had but for containers.

```
{
   "name": "Docker .NET Core Attach (Preview)",
   "type": "docker",
   "request": "attach",
   "platform": "netCore",
   "sourceFileMap": {
      "/src": "${workspaceFolder}"
   }
}
```

Perhaps something like this could be supported:
```
{
   "name": "Docker .NET Core Attach (Preview)",
   "type": "docker",
   "request": "attach",
   "platform": "netCore",
   "sourceFileMap": {
      "externalSrc": "....path...to...src...outside...the...container...",
      "externalPdb": "....path...to...pdb...outside...the...container..."
   }
}
```

**Comment by bwateratmsft** [comment]
Yes, you can copy things into containers. Depending on your requirements you may also be able to use volume mapping. If you want the cleanest F5 experience, though, your best bet is to use the `docker` `launch` configuration, not `attach`. This configuration and tasks are created when you do "Add Dockerfiles...", and also when you do "Docker: Initialize for debugging...".

Can you tell me more about your project? Is it a single project, or docker-compose with multiple projects? Do the source files actually need to be copied into the container or just source mappings for debugging?

**Comment by bwateratmsft** [comment]
I think that for both scenarios, the `docker` `launch` configuration that is created when doing "Add Dockerfiles..." or "Initialize for debugging..." is definitely gonna be the best experience--fastest, fewest clicks, etc. With `attach`, the debugger either needs to be volume mapped or copied in. The first (volume mapping) requires some user work, the second (copy) is slow every time. With `launch`, it's done via volume mapping without any user work.

You can also make [compound debugging configurations](https://code.visualstudio.com/docs/editor/debugging#_compound-launch-configurations) that would launch multiple containers for debugging, as well.

One additional thing i want to add--for the `docker` .NET Core configurations, the entirety of what you enter as config is passed-through up to a `coreclr` configuration, with certain properties overridden to enable the scenario. That means any extra properties on `coreclr` are still available (not all of them may work, due to the differences of debugging locally vs. container, but all of them can at least be tried :smile:). For example, properties like `sourceFileMap`, `suppressJITOptimizations`, etc. can be passed through. You'll still get yellow squiggles from Intellisense because these properties don't technically exist on the `docker` launch configuration, but you can ignore that.
