### ISSUE TITLE
ASP.NET Core - Unable to configure launchUrl for debugging

### ISSUE THREAD

**Issue by snerks** [microsoft/vscode-docker#2039]
It appears that there are not configuration options to control the browser launch parameters, in a way similar to VS2019.

If Docker support is added to a VS2019 ASP.NET Core WebApi Project (for example), the launchSettings.json file has a section like this:

```   
    "Docker": {
      "commandName": "Docker",
      "launchBrowser": true,
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}/weatherforecast",
      "publishAllPorts": true,
      "useSSL": true
    }
```

**Observations**
1. `launchBrowser` controls whether a browser is launched at all
1. `launchUrl` can be edited, to point to an endpoint/Controller of interest
1. VS2019 appears to launch Chrome (even when it is not the machine's default browser) - which is a personal preference

I couldn't find similar settings for the above configuration items.

I see that there appears to be some support for this type of configuration, so perhaps I need to dig deeper in the documentation:
https://github.com/microsoft/vscode-docker/issues/764

**Comment by bwateratmsft** [comment]
Yes, you can set the URL. It is important to know that VSCode does not make any use of `Properties\launchSettings.json`--not just the Docker extension, but no part of VSCode will make use of it. Instead, VSCode uses launch configurations and tasks, in `.vscode/launch.json`, and `.vscode/tasks.json`, respectively. Launch configuration controls what happens when you hit F5, and can use tasks as prerequisites. Tasks can include things like build, deploy, anything really. In the case of Docker with .NET Core, it includes the .NET Core build, then Docker build, then Docker run.

Probably the easiest way to see the tasks and launch config in action would be to create a new .NET Core app, use the C# extension's "Generate assets for build and debug" command (or, wait for the prompt which will ask you to do the same), and then do "Add Dockerfiles to workspace". This "Add Dockerfiles" command will create the Dockerfile and .dockerignore, and also create tasks and launch configuration.

In the particular case of launch URL, you can edit the Docker launch configuration like so, adding the `"dockerServerReadyAction"` property with `"uriFormat": "%s://localhost:%s/weatherforecast"`:

```json
    {
        "name": "Docker .NET Core Launch",
        "type": "docker",
        "request": "launch",
        "preLaunchTask": "docker-run: debug",
        "netCore": {
            "appProject": "${workspaceFolder}/MyNetCoreProject.csproj"
        },
        "dockerServerReadyAction": {
            "uriFormat": "%s://localhost:%s/foo"
        }
    }
```

In that `uriFormat`, the first `%s` is replaced with the protocol (`http` or `https`), the second with the mapped port (by default, randomly assigned by Docker).

Can you try this out and see if it works for you? Thanks!

**Comment by snerks** [comment]
@bwateratmsft - Thanks for looking at this.

I am experimenting with the .NET core `webapi` template, which scaffolds a `WeatherForecastController`.

I found this page very helpful too:
https://code.visualstudio.com/docs/containers/debug-netcore

I used this setting in the ~/.vs/launch.json file (in the section with name: "Docker .NET Core Launch"):

```json
      "dockerServerReadyAction": {
        "uriFormat": "%s://localhost:%s/weatherforecast"
      }
```

Worked first time!

Do you happen to know whether it is possible to control the browser to launch (I prefer to use Chrome for debugging web apps)?

Are there any other docs/examples on "uriFormat"?

**Comment by bwateratmsft** [comment]
Nothing beyond the Intellisense, unfortunately. It supports 0 or 2 replacements for "%s". If zero, obviously nothing about the URL gets changed. If two, the first gets replaced with `http` / `https`, depending on what the line output by the program is. The second gets replaced by the host-side port tied to the emitted container-side port.

For example, in ASP.NET Core, it outputs something like "Now listening on: https://+:443;http://+:80". The `%s` gets replaced with `https`, because that output line contains `https`. The second `%s` gets replaced with whatever host-side port maps to container port 443. By default we let Docker choose a random port so it might be, for example, 32768.

**Comment by snerks** [comment]
@bwateratmsft - Thanks for the additional info.
