### ISSUE TITLE
Fail to debug Python flask project

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2048]
**OS:** Mac
**Build Version:** 20200604.7

**Repro Steps:**

1. Open a python project(Flask) in VS Code.
2. F1 -> Docker: Add Docker Files to Workspace -> Python: Flask -> Include docker compose files.
3. F5.

**Expect:**
Debug successfully without any error.

**Actual:**
Fail to debug Python flask project with errors.
There are two different results:

1. Pop up a dialog when debugging this project for the first time.
![Screen Shot 2020-06-08 at 6 43 55 PM](https://user-images.githubusercontent.com/62053665/84024826-243b4a80-a9bd-11ea-84e7-65d60fc3bee7.png)

2. There is an error "no such option: --host 0.0.0.0" when debugging this project more than once.
![Screen Shot 2020-06-08 at 6 45 12 PM](https://user-images.githubusercontent.com/62053665/84025383-0c17fb00-a9be-11ea-93b1-7bf4713331ec.png)

**Comment by bwateratmsft** [comment]
No repro for me on Widnows, I'll try on Mac.

**Comment by bwateratmsft** [comment]
@v-mengwe What version of Python are you using on the Mac? I am able to reproduce the first error, but only with Python 2.7.16 (installed by default on OS X). The Python extension shows quite a few notifications discouraging the use of the preinstalled version.

I installed 3.8.3 and the first error no longer occurs, but the second error still occurs.

**Comment by bwateratmsft** [comment]
@haniamr I'm a bit confused about something. The Python `docker-run` task provides options for `python`, e.g. `args`, `module`, etc. but these are not used by the run task for anything. Instead, they get used by the debug task, but the debug task already has many of the same options. Why was it done this way?

Additionally, can you investigate the above two errors? The first one (about "debugLauncherPath") only repros for me when using Python 2.7 on Mac; the second repros for me with 3.8 on Mac and prevents debugging.

**Comment by haniamr** [comment]
@bwateratmsft the reason is to make sure existing projects run fine on different versions of the extension, where on version A these properties have to be defined in the `docker-run` task while on version B they don't. The other minor reason is not to add confusion to users who are already using those options on the run task (i.e. now we have to say we override the entry point to `python `and then use a custom launcher to call the actual launcher and....). 

The user have an option to define those properties on the debug task (though not documented yet), so in a way they only have 1 place for those options which is the `docker-run` task.

For the issue reported here, first one for sure is caused by Python 2.7, since I saw it early and chatted with Pavel about that. The second one I'll have to look and see what is happening.

**Comment by bwateratmsft** [comment]
Ah, so we had it done differently in prior versions of the extension?

**Comment by haniamr** [comment]
Yes, earlier versions (pre 1.3) we used to override the entry point with something like "python /pydbg/ptvsd -m {module}|{file}", so we had to know these prior to executing the docker-run command.

**Comment by haniamr** [comment]
For the second issue, please update the args under the docker-run task to be:
```
"args": [
	"run",
	"--no-debugger",
	"--no-reload",
	"--host", "0.0.0.0",
	"--port", "5000"
]
```

Previously, this works fine because we form the entry point by concatenating the list of args as a string, however in this new model we pass in the args as a list to the custom launcher, which apparently works well on Windows, however on Mac (and I guess Linux as well) it expects every argument/value to be its own entry.

The downside here is that existing Flask projects on Mac/Linux will need to be updated. I'll check with Pavel and see if there's anything we can do to avoid this side effect.
