### ISSUE TITLE
It opens 2 webpages when debugging Django project with hot reloading enabled on Windows

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2050]
**OS:** Windows 10
**Build Version:** 20200604.7

**Repro Steps:**
1. Open a Django app in VS Code.
2. F1 -> Docker: Add Docker Files to Workspace -> Python: Django -> Include docker compose files.
3. Enable hot reloading.
4. F5.

**Expect:**
Debug successfully and open 1 webpage.

**Actual:**
Debug successfully and it opens 2 webpages.

**More Info:**
1. This issue does not reproduce with hot reloading disabled.
2. This issue does not reproduce in Flask project.
3. This issue does not reproduce on Mac.

**Comment by bwateratmsft** [comment]
@haniamr I thought we couldn't get hot reloading working?

**Comment by haniamr** [comment]
@bwateratmsft turns out it was an issue in my machine, but it does seem to work fine, however with this described side effect for Django apps. I'll take a closer look into this, but at a glance it seems to happen because there are 2 different processes that execute and spit out the logs we expect to launch the browser, so we launch it twice.

**Comment by bwateratmsft** [comment]
I've found what is going wrong. The Python extension sets up an inner and outer debug session, both of them get the message to open the browser, so it is opened twice. I will make a change so that only one tracker is created in this scenario, and thus only one browser tab will be opened.
