### ISSUE TITLE
There is no webpage opening when debugging Django/Flask project with host network

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2062]
**OS:** All
**Build Version:** 20200608.1

**Repro Steps:**
1. Open a Django/Flask project in VS Code.
2. Add Docker support for it.
3. In the task "docker-run: debug", add the host network in the dockerRun property:
_"dockerRun": {
	       "network": "host"
             }_
4. F5.

**Expect:**
Debug successfully with the webpage opening.

**Actual:**
There is no webpage opening when debugging with 'host' network.

**More Info:**
1. This issue does not reproduce with 'bridge' network.
2. An error occurs when debugging with 'none' or 'macvlan' network.
![image](https://user-images.githubusercontent.com/45614674/84378149-47146b80-ac16-11ea-88a4-3b91594e3ea2.png)

**Comment by bwateratmsft** [comment]
@haniamr this is probably expected, right?

**Comment by haniamr** [comment]
@bwateratmsft when using the "host" network, the "dockerServerReadyListener" is trying to get the host port that maps to the found container port, however when using host networking there are no port mappings and you can access the container port directly from the host.

When using "none", it's expected to not work since there is no network connectivity in the container. For "macvlan", I'm not 100% sure, but on the Docker docs it is advised to use "bridge" instead and "macvlan" seems to need some prerequisites to be configured (i.e. _Your networking equipment needs to be able to handle “promiscuous mode”_), so I wouldn't worry too much about it.

**Comment by bwateratmsft** [comment]
"host" could be solved then using the built-in `serverReadyAction`, rather than `dockerServerReadyAction`. Our code is already smart enough to not do `dockerServerReadyAction` if `serverReadyAction` is present. Seems like we can resolve this one as by-design then.
