### ISSUE TITLE
[Suggestion] Add a warning message to remind to use the port 443 if use the https certificate

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2076]
**OS:** Mac
**Build version:** 1.3.1-alpha
**.NET Core SDK:** 2.1

**Repro Steps:**

1. Create a .NET Core MVC project by "dotnet new mvc".
2. Open the project in VS Code --> Prompt to add the required asserts --> Yes.
3. F1 --> Type and select "Docker: Add Docker Files to Workspace" --> ASP.NET Core --> Linux --> Include optional Docker Compose files --> Port: 80.
4. Go to the Debug tab in VSCode, select the "Docker .NET Core Launch"-->F5

**Actual:**
It doesn't launch the browser and open the web page without any warning.

**Suggestion:**
Add a warning message to remind to use the port 443 if use the https certificate.

**Comment by bwateratmsft** [comment]
Hm, I'd expect it to still launch the browser. I'll investigate.

**Comment by PavelSosin-320** [comment]
I think that it would better to have the global configuration "Use HTTPS"  which assumes port 443 to avoid numerous Chrome and Internet security warnings. Even in the case of "local deployment", yet another image or local proxy can be deployed to the same engine/host which does or doesn't do SSL termination by developer's will.

**Comment by bwateratmsft** [comment]
Ok, I can reproduce. If you add `"configureSsl": false` to the `docker-run` task in the `netCore` section, the issue goes away and the browser is launched to the port mapped to 80 as expected:

![image](https://user-images.githubusercontent.com/36966225/85042474-42d9d800-b159-11ea-8991-c8a80fa1f08a.png)

Without that flag, the ASP.NET Core server is still listening on 443, so it still outputs the `Now listening on: https://[::]:443` message, and it happens to be the first one output as well. The server ready action handler captures that but can't find anything mapped to 443, so it fails. Flipping around the listen socket order in the `ASPNETCORE_URLS` environment variable also results in the browser being launched (though ASP.NET Core tries to redirect you to the SSL port which fails because it's not defined and not open anyway).

I think the best solution is to set `"configureSsl": false` automatically if only port 80 is chosen. The necessary information can be obtained during scaffolding.

**Comment by karolz-ms** [comment]
@bwateratmsft is `configureSsl` documented anywhere? I could not find any mention of it in the [OmniSharp docs](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md)

**Comment by bwateratmsft** [comment]
It's not an Omnisharp property since they can do SSL config with basically zero effort, unlike us. It *should* have been documented here but never was: https://code.visualstudio.com/docs/containers/debug-common

**Comment by karolz-ms** [comment]
OK. Can you take an action item to update the doc, please? I can help you with that if you send me the description for the missing property--your choice.

**Comment by bwateratmsft** [comment]
I'd be happy to add it! I'll include that as part of this work.

**Comment by PavelSosin-320** [comment]
I know that some Windows "Corporate" images block any insecure HTTP access via port 80 outside localhost because all developed products use only HTTPS. This is Corporate security policy. Every server listening to port 80 is placed behind either Corporate proxy or proxy pre-installed in the image.  When the browser is used for debugging it can be started for HTTPS access unless it is started with **localhost URL.**. Developers don't care about it: does the application itself support HTTPS or not because SSL termination happens outside the development environment. Imagine System environment variable "UseHTTPS"

**Comment by karolz-ms** [comment]
🤦‍♂️ thanks @bwateratmsft
