### ISSUE TITLE
Python debug fails with "Unable to find the debugger in the Python extension"

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#2080]
![image](https://user-images.githubusercontent.com/36966225/85034002-96472880-b14f-11ea-9db8-5aa92b22392d.png)

**Comment by bwateratmsft** [comment]
A fix for this is now released in Docker extension version 1.3.1.

**Comment by kbroughton** [comment]
I have Docker extension v 1.3.1 and I'm still seeing this.

Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:17:14.222Z (2 days ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
```
    > Executing task: docker-run: debug <
    Unable to find the debugger in the Python extension.
    The terminal process failed to launch (exit code: 1)
    Terminal will be reused by tasks, press any key to close it.
```

launch.json
```
{
    "version": "0.2.0",
    "logToFile": true,
    "configurations": [
        {
            
            "name": "Docker: Python - General",
            "type": "docker",
            "request": "launch",
            "preLaunchTask": "docker-run: debug",
            "python": {
                "pathMappings": [
                    {
                        "localRoot": "${workspaceFolder}",
                        "remoteRoot": "/code"
                    }
                ],
                "projectType": "general"
            }
        }
    ]
}
```

**Comment by kbroughton** [comment]
I'm not too familiar with vscode but here is a bit more context on what i see locally:

It looks like the code in launcher.py in the commit to fix the bug is applied.

When I grep for "Unable to find the debugger" in .vscode, I get

/.vscode//extensions/ms-azuretools.vscode-docker-1.3.1/dist/extension.bundle.js

<snip>
||void 0===e?void 0:e.debug)||void 0===n?void 0:n.getDebuggerPackagePath());if(s)return s;throw new Error(a.localize("vscode-docker.tasks.pythonExt.noDebugger",
"Unable to find the debugger in the Python extension."))} ,e.getPythonExtension=getPythonExtension}(n.PythonExtensionHelper||(n.PythonExtensionHelper={}))},function(e,n,i){"use strict";Object.defineProperty(n,"__esModule",{value:!0}),n.nodeDebugHelper=n.NodeDebugHelper=void 0;const s=i(367),o=i(368),a=i(193);class NodeDebugHelper{async provideDebugConfigurations(e){return[{name:"Docker Node.js Launch",type:"docker",request:"launch",preLaunchTask:"docker-run: debug",platform:"node"}]}async resolveDebugConfiguration(e,n){const i=n.node||{},l=s.NodeTaskHelper.inferPackagePath(i.package,e.folder),u=await o.readPackage(l),c=await o.inferPackageName(u,l),p=a.inferContainerName(n,e,c),d={containerName:p,dockerServerReadyAction:a.resolveDockerServerReadyAction(n,{containerName:p},!0),removeContainerAfterDebug:n.removeContainerAfterDebug},m={...i,name:n.name,dockerOptions:d,preLaunchTask:n.preLaunchTask,request:"attach",type:"node2"};return void 0===m.localRoot&&(m.localRoot="${workspaceFolder}"),void 0===m.port&&
<snip>

The commit appeared to have removed that in the .ts file. Perhaps the new build of the js bundle isn't getting forced in the update?

**Comment by bwateratmsft** [comment]
@kbroughton What version of the Python extension do you have?

**Comment by luabud** [comment]
The issue is in the Python extension, it's the same root cause of https://github.com/microsoft/vscode-python/issues/12481. It's fixed in [our Insiders build](https://code.visualstudio.com/docs/languages/python#_insiders-program), and we'll release the fix as soon as we can.  
The workaround out of the Insiders build [is here](https://github.com/microsoft/vscode-python/issues/12481#issuecomment-647266379).

**Comment by bwateratmsft** [comment]
It looks like this might also be what @ddurham2 is hitting in https://github.com/microsoft/vscode-python/issues/12484

**Comment by kbroughton** [comment]
The extension says v2020.6.89148 @bwateratmsft

**Comment by bwateratmsft** [comment]
Thanks @kbroughton. I think that it should be fixed now from the Python extension side (without needing to upgrade). I tried it out and I can no longer reproduce the issue. Can you give it a try? I'm not sure how the experimentation framework is implemented in the Python extension--perhaps @luabud can answer that--but it might take a bit of time to download the new experiment data before it starts working again.

**Comment by kbroughton** [comment]
nether docker nor python extensions show an update available for VS code. How do I try it out? @bwateratmsft

**Comment by haniamr** [comment]
@kbroughton the fix in the Python extension shouldn't require an update since it is already pulling the information about the experiments from the server, restarting VS Code didn't help?

You can try add those settings as mentioned by Pavel [here](https://github.com/microsoft/vscode-python/issues/12481#issuecomment-647266379):
```
    "python.experiments.optInto": [
        "DebugAdapterFactory - experiment",
        "PtvsdWheels37 - experiment"
    ],
```

**Comment by kbroughton** [comment]
I did restart VSCode, but get the same error.
Here is my launch.json

{
// Use IntelliSense to learn about possible attributes.
// Hover to view descriptions of existing attributes.
// For more information, visit:
https://go.microsoft.com/fwlink/?linkid=830387
"version": "0.2.0",
"logToFile": true,
"configurations": [

{
"name": "Docker: Python - General",
"type": "docker",
"request": "launch",
"preLaunchTask": "docker-run: debug",
"python": {
"pathMappings": [
{
"localRoot": "${workspaceFolder}",
"remoteRoot": "/code"
}
],
"projectType": "general"
}
}
],
"python.experiments.optInto": [
"DebugAdapterFactory - experiment",
"PtvsdWheels37 - experiment"
]
}

**Comment by bwateratmsft** [comment]
That `python.experiments.optInto` section needs to go into your settings.json, not launch.json.

**Comment by bwateratmsft** [comment]
I'll close this issue again since it appears to be fixed on the Python extension side.
