### ISSUE TITLE
String prompt input is not triggered in docker-build tasks

### ISSUE THREAD

**Issue by vglushkov** [microsoft/vscode-docker#2105]
- VSCode Version:  1.46.1
- OS Version: MacOS 10.15.5

Steps to Reproduce:

1. Create a task with "docker-build" type
2. Use an input variable with the "promptString" type for a task property value
3. Select Tasks: Run Task in Command Palette
4. Select the newly created task

Expected: user prompted for input
Actual: the task is executed without the input variable being resolved

Example tasks.json

``` json
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "docker-build",
            "label": "Build Image", 
            "platform": "node",
            "detail": "Build Docker image",
            "dockerBuild": {
                "dockerfile": "${workspaceFolder}/Dockerfile",
                "tag": "${input:projectName}:latest"
            }
        }    
    ],
    "inputs": [
        {
            "id": "projectName",
            "type": "promptString",         
            "description": "Project Name",
            "default": "my-new-project"
        }
    ]
}

```

**Comment by bwateratmsft** [comment]
Fundamentally this is the same as #1961; since we cannot use the built-in variable resolver with CustomExecution it isn't possible for things like this to work. I'll resolve this one as dupe. @vglushkov, can you comment on https://github.com/microsoft/vscode/issues/81007 to encourage the VSCode team to implement this so we can make this scenario work? :smile:
