### ISSUE TITLE
Support creating a new ACI context from the Contexts panel

### ISSUE THREAD

**Issue by BigMorty** [microsoft/vscode-docker#2114]
Similar to the + sign in the Networks panel we should support creating an ACI context. Once we support ACI and SSH context creation the + sign icon should prompt user for type of context. For ACI we should then sign into Azure if needed, then show list of subscriptions, then list of resource groups or ability to create a new resource group.

**Comment by bwateratmsft** [comment]
@BigMorty I've started working on this. For now, I'm implementing just a palette command--wanted your input on whether it should show up in the contexts tray or not. If we want it to show up in the contexts tray--what icon should we use? I don't think the usual "+" icon is would really be appropriate since it's not for adding any context--just ACI in particular.

**Comment by BigMorty** [comment]
I think + icon is find, we can have hover text that says "Create ACI context".

**Comment by bwateratmsft** [comment]
Closing since #2151 is not needed.

**Comment by bwateratmsft** [comment]
We have released Docker 1.4.0 which contains this feature.
