### ISSUE TITLE
Feature request: Filter to only show project's Containers

### ISSUE THREAD

**Issue by ScottHarrisonDev** [microsoft/vscode-docker#215]
Is there any way for Docker Explorer to only show Containers related to the currently open project in VS Code? If not, this may be a worthwhile feature? 

I find myself having to look through 10+ containers to find the ones related to the current project. Is there anyway to read from the `docker-compose.yml` and only show the containers related to that?

I understand I can right click the yml file and docker up or down but this runs the command with the build parameter which I don't want to.

**Comment by nickasd** [comment]
I agree that there should be an option to filter the containers and show only those appearing in the project's `docker-compose.yml`. I guess most people are not interested in seeing containers relating to other projects. Perhaps another option to always show running containers would be nice, so that one knows if there are still containers from other projects that were not shut down.

**Comment by StephenWeatherford** [comment]
Could you tell us more about the number of containers you have, how they're grouped, what kinds of filters might be useful, etc.?  Thanks!

**Comment by nickasd** [comment]
I have a couple of containers that I use at my regular job, then for my private projects I have one project which has 5 containers that all need to be started with `docker-compose up` from the command line, and 2 other projects which have 1 container that I usually started from Kitematic (a GUI for Mac).

Personally I would like an option to filter out all containers that do not appear in the Docker file, so that pressing some Start All button would just start those containers listed. Or maybe, which could be even a better solution, having a "Start all relevant containers" button that runs `docker-compose up` or some other (customisable) command? This would even be faster because you don't have to press a button to filter first and then start those containers. In this scenario all running containers would be listed at the top, so you could always check that all the right containers were started.

Sometimes I forget to stop the containers for one of the projects (that's why I suggested to also include all running containers even if they are not related to the project), but I guess in this case I could just list them all (unless you opt for the second option above where there is no filter necessary) and stop them manually (or perhaps a shortcut to stop all containers would be nice).

**Comment by bwateratmsft** [comment]
This is very similar to #1846, and probably would be enabled by it. With the containers grouped, you can use the existing filter logic to search based on compose project name.

Considering how similar they are, I'll mark this for 1.2 and give to @ravipal; Ravi can you take a look at this and see if you feel it's fixed by #1876?

**Comment by ravipal** [comment]
#1846 is about ability to group containers by compose project name. This feature request is about identifying/filerting the containers associated with the the current open project, similar to how VS Containers Tools Window groups containers belongs to current project vs other projects. If the current project/workspace uses compose then group by compose project name will help user to locate the group of containers easier than before.

**Comment by bwateratmsft** [comment]
It seems like all of the users mentioned compose, though, which makes me think it's what they need.

**Comment by ravipal** [comment]
#1846 shows the containers grouped by the compose project name. Though this change didn't filter current project with rest of the projects, it at least gives the ability to easily locate the set of containers belongs to a compose project.
@ScottHarrisonDev & @nickasd Please reopen if this change didn't address your issue.

**Comment by bwateratmsft** [comment]
The "group by Compose project" feature is now available in version 1.2.0 of the [Docker extension](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker).
