### ISSUE TITLE
The state is not changed for the outdated image "hello-world:latest" after pulling the image again

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2161]
**OS:** All
**Build Version:** 20200714.2

**Repro steps:**
1. Open Docker view, if the image "alpine:latest" is present, remove it: docker rmi alpine:latest.
2. Pull any image, and tag it as "alpine:latest": docker pull hello-world:latest && docker tag hello-world:latest alpine:latest.
3. Remove the "hello-world:latest" image: docker rmi hello-world:latest.
4. Restart VS Code, the state of the image "alpine:latest" is changed to "Out of date" after refreshing the image view.
5. Pull image: docker pull hello-world, the "hello-world:latest" image is "Out of date" now.
6. Right click the outdated image "alpine:latest" and pull new version for it, the warning icon and "Out of date" text is disappeared.
7. Right click the outdated image "hello-world:latest" and pull it again, then check its state.

**Expect:**
The warning icon and "Out of date" text should disappear for the image "hello-world:latest".

**Actual:**
The state of the image "hello-world:latest" is still "Out of date".
![image](https://user-images.githubusercontent.com/45614674/87518022-4c9c2000-c6b2-11ea-8fe9-e9792609fb30.png)

**More info:**
Restart VS Code can fix this issue.

**Comment by bwateratmsft** [comment]
This is by design but it's sort of hard to explain. For performance reasons we cache a list of image IDs that we find are out of date, at the time of extension activation. In this example the `alpine:latest` image ID locally does not match Docker Hub, so that image is flagged as out of date.

However, when `hello-world:latest` is pulled during the same session, its image ID is in the out-of-date list, so it also gets flagged. This shouldn't be a real problem for customers since they won't tag `hello-world:latest` as `alpine:latest`, but doing so is useful for easier testing.

When VSCode is restarted, that outdated image cache is cleared, and since the local `hello-world:latest` matches Docker Hub it is not flagged.
