### ISSUE TITLE
An error occurs when executing "Run/Run Interactive/Pull/Push..." commands for Docker image

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2177]
**OS:** Mac
**Build Version:** 20200720.3

**Repro Steps:**
Right click one Docker image and execute "Run/Run Interactive/Pull/Push..." commands.

**Expect:**
Succeed to execute these commands "Run/Run Interactive/Pull/Push...".

**Actual:**
An error "Cannot read property 'uri' of undefined" occurs.
![Screen Shot 2020-07-22 at 5 54 57 PM](https://user-images.githubusercontent.com/45614674/88163957-01e84e00-cc46-11ea-99fd-0b66dd9f69a7.png)

**More Info:**
This issue does not reproduce on Windows.

**Comment by bwateratmsft** [comment]
I am able to reproduce on Windows as long as no workspace is open. I'm still looking as the error doesn't appear to originate in our code...

**Comment by bwateratmsft** [comment]
Can confirm this is happening in VSCode somewhere, not in our code. I found one issue that blocks execution from happening at all that we can work around. Still working on finding the source of the "Cannot read property 'uri'..." error.

**Comment by bwateratmsft** [comment]
Talked to @alexr00. There are two parts to this--
1. Some task stuff that she understands far better than me :smile: (should be fixed in https://github.com/microsoft/vscode/commit/8c1aba0d95fe745fa71e7a9dd44b540beb37e86d -- should eliminate the "Cannot read property 'uri' of undefined" popup)
1. When `cwd` is undefined, the task system tries to use the workspace folder, but that is also undefined so execution fails. This prevents the task from running at all.

We can fix the second issue by passing in `os.homedir()` as `cwd` if there is no workspace folder opened. When I tried that, the task successfully executed (though the error still pops up).

FWIW, we're kind of in unsupported territory, running tasks outside of a workspace.

**Comment by bwateratmsft** [comment]
The fix is in on our side, tomorrow I will test with Insiders to ensure that the VSCode-side is also fixed.

**Comment by bwateratmsft** [comment]
Verified this is now fixed in the latest VSCode Insiders build.
