### ISSUE TITLE
Enable use off compose down, restart and up on shortcuts.

### ISSUE THREAD

**Issue by pablostellet** [microsoft/vscode-docker#2192]
As I work on multiple projects that have each one it's own docker-compose.yml file, I want to take advantage of vscode folder workspace structure with a folder that contains all docker-compose.yml shortcuts.

**Comment by bwateratmsft** [comment]
What are your shortcut files called?

**Comment by pablostellet** [comment]
I name them docker-compose.[project_name].yml**.ink** (extension .ink are for windows shortcuts).
Right clicking on this file shows me the options:

Composer up
Composer down
Composer restart

but it will try to execute on the shortcut path instead the original file path

**Comment by karolz-ms** [comment]
@pablostellet you could try to [NTFS links](https://en.wikipedia.org/wiki/NTFS_links) instead of Windows shortcuts ([`mklink` command](https://docs.microsoft.com/windows-server/administration/windows-commands/mklink)). NTFS links are transparent to applications and should work with VS Code Docker extensions, unlike Windows shortcuts.

**Comment by bwateratmsft** [comment]
I agree, Windows shortcuts aren't the best for this. Symbolic links are one option but you'd have to figure out ways to ensure the correct build context is used. In general, I would suggest keeping one "project" to one workspace folder, so that in any given workspace folder only one `docker-compose.yml` is present (or even, one per workspace).
