### ISSUE TITLE
while pulling image

### ISSUE THREAD

**Issue by kushJay-Official** [microsoft/vscode-docker#2227]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.pullRepository
Error type: 1
Error Message: Command failed: docker login  --username kush2020jay --password-stdin
WARNING: Error loading config file: /home/jay/.docker/config.json: stat /home/jay/.docker/config.json: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/auth: dial unix /var/run/docker.sock: connect: permission denied

Version: 1.4.1
OS: linux
OS Release: 5.4.0-42-generic
Product: Visual Studio Code
Product Version: 1.47.3
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.exithandler child_process.js:308:12
ChildProcess.emit events.js:203:13
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by karolz-ms** [comment]
@kushJay-Official are you able to log in to your registry and pull images using Docker CLI from terminal pane inside VS Code (non-sudo)?

**Comment by kushJay-Official** [comment]
@karolz-ms Sir I am unable to use Visual Studio code with Docker or any other plugins. Even I face problem while login with Github. Sir please help me to resolve this. And one more problem microsoft authentication get always failed

**Comment by karolz-ms** [comment]
@kushJay-Official Sir I can help you with VS Code extension for Docker, but it sounds like the issues you are seeing are related to Docker engine installation on your machine.

1. I would start with making sure Docker is properly installed. Instructions on Docker website are pretty good: https://docs.docker.com/engine/install/ Please choose the version appropriate for your Linux distribution.

2. Please make sure you set up Docker so that you can use it as normal user (not-sudo): https://docs.docker.com/engine/install/linux-postinstall/

3. Once you have everything Docker working from command line, please try Docker extension again.

Hope this helps!
