### ISSUE TITLE
Fail to execute "Run" command for a .NET Core MVC image

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2228]
**OS:** Win10
**Build Version:** 20200807.6

**Repro Steps:**

1. Create a .NET Core MVC project by "dotnet new mvc".
2. Open the project in VS Code --> Prompt to add the required assets --> Yes.
3. F1 --> Type and select "Docker: Add Docker Files to Workspace" --> ASP.NET Core --> Linux 
--> Include optional Docker Compose files.
4. Right click the Dockerfile --> Select "Build Image...".
5. Navigate to "Images" view --> Right click the "mvc" image --> Select "Run".
6. Check the result.

**Expect:**
There is a running container in the "Containers" view without any error.

**Actual:**
There is a stopped container in the "Containers" view with an error.
![image](https://user-images.githubusercontent.com/62053665/89771035-432b9980-db32-11ea-8bed-842853377783.png)
![image](https://user-images.githubusercontent.com/62053665/89771009-33ac5080-db32-11ea-936e-b64c549e7ec9.png)

**More Info:**

1. This issue also reproduces when creating a .NET Core MVC project by "dotnet new mvc --no-https".
2. This issue also reproduces when executing "Run Interactive".
3. Please get the details from below:

   OS | Run | Run   Interactive
   -- | -- | --
   Mac | Not Repro | Not Repro
   Linux | A container in the "Containers" view for a   short time then it is automatically removed. | There is a stopped container in the "Containers" view.

**Comment by karolz-ms** [comment]
The Docker scaffolding for MVC apps is non-terminally, but annoyingly broken in more than one way.

1. The immediate cause of the issue above is that Windows HTTP service (HTTP.sys, PID 4) will grab the port 80 by default. This can happen if the user installs IIS, but will also happen for machines that have Windows Management service running. So it is a common scenario and we probably should not offer port 80 as default during Dockerfile scaffolding. Port 80 is also problematic on Linux, for the reason that low-range ports are reserved for system processes by default.

2. Unfortunately, choosing a different port during Docker scaffolding (say, 8023) does not result in runnable image. The reason is, we `EXPOSE 8023` as a hint that this is the port that needs to be used to talk to the application, but we don't set `ASPNETCORE_URLS` environment variable to actually tell ASP.NET to use the exposed port. As a result, ASP.NET uses the default from the base image (ASP.NET Core Docker image), which is port 80, as the container port. When we run the image, we do `-p 8023:8023`, which is going nowhere because the app is listening on port 80 inside the container.

    Incidentally, the ASP.NET Core Docker image default is **different** from ASP.NET Core default, which is port 5000

    To get out of this mess we should set `ASPNETCORE_URLS` environment variable in the Dockerfile, to override the base image port and make the run command behave correctly. 

3. For reasons not entirely clear, when HTTPS is enabled during scaffolding, the "Open in browser" command will attempt to use URL that has no port included (`https://localhost`). It should include the port, and should probably default to non-HTTPS URL.

**Comment by karolz-ms** [comment]
Moving to the next milestone. Several issues need to be decided and discussed within the team, and probably also with the .NET team:

- Do we allow the user to customize exposed ports, or just always use defaults. What are the default ports in either case.
- Should we ask the user to choose HTTP vs HTTPS ports (instead, like today, only ask for "exposed" ports)
- Should we offer to use HTTPS at all, given that in most cloud environments there are separate facilities for handling HTTPS/certificates, and it is almost never the job of the app container to terminate HTTPS
- If we decide to offer HTTPS as an option, how do we provide certificates to the container? Rely only on F5 logic that volume-maps these to the container? Rely on custom task? Rely on command customization (workspace-level)?
- Should we continue 1:1 port mapping via `-p` option, or rely on auto-assigned ports (`-P`). If we use `-P`, is it OK that HTTP --> HTTPS auto-redirection will fail?
- Should we scaffold ASPNETCORE_URLS variable.

So far we only seem to mostly agree on the last two points (advantages of using `-P` outweigh disadvantages, and scaffolding ASPNETCORE_URLS is required for most discussed solutions)

**Comment by bwateratmsft** [comment]
(As noted in email) IMO we leave the existing behavior alone and dupe this to #1311.

**Comment by v-ruizh** [comment]
The same error occurs when executing "Compose Up" action for docker-compose.yml file in MVC project. (Docker extension build 20200909.2)
![image](https://user-images.githubusercontent.com/45614674/93083141-c0fc3b00-f6c4-11ea-80ed-22f4c24badae.png)

**Comment by bwateratmsft** [comment]
Collapsing this issue into #1835. The solution for this and that are really the same.
