### ISSUE TITLE
Fail to execute command "Pull" for an Express App image

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2232]
**OS:** Win10/Mac
**Build Version:** 20200807.6

**Repro Steps:**

1. Create an Express App project and open it in VS Code.
2. Command Palette -> Add Docker files to workspace -> Node.js -> Enter port.
3. Right click Dockerfile -> Build image.
4. Navigate to "Images" view -> Right click this image -> Select "Pull".
5. Check the result.

**Expect:**
Execute command "Pull" successfully without any error.

**Actual:**
Execute command "Pull" failed with an error.
![image](https://user-images.githubusercontent.com/62053665/89868898-1f299000-dbe6-11ea-8028-46244879ae1b.png)

**More Info:**

1. This issue also reproduces for a .NET Core MVC/Python image.
2. This issue does not reproduce for a hello-world/registry image.

**Comment by karolz-ms** [comment]
This is by design. When one executes a "pull" on a local image (e.g. `myexpressapp:latest`), that is interpreted as a request to pull from `hub.docker.com/myexpressapp:latest` (Docker Hub being the default, implicit container registry). Since there is no such repository on Docker Hub, the pull fails. 

We don't know that such repository does not exist, so we will always attempt a pull when requested.
