### ISSUE TITLE
Fail to run 'Docker .Net Core Attach (Preview)' configuration which using docker-compose.debug.yml to compose-up

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2233]
**OS:** Ubuntu 18.04
**Build Version:** 20200807.6
**.NET Core SDK:** 3.1.302

**Repro Steps:**
1. Create a .NET Core MVC project by "dotnet new mvc --no-https".
2. Open the project in VS Code --> Prompt to add the required assets --> Yes
3. F1 --> Type and select "Docker: Add Docker Files to Workspace" --> ASP.NET Core --> Linux --> Include optional Docker Compose files.
4. Right click the docker-compose.debug.yml --> Select "Compose Up".
5. Open launch.json and click 'Add Configration…', and choose 'Docker .NET Core Attach (Preview)'.
6. Run the above configuration, select the running container from step4.

**Expect:**
It will not prompt to copy the debugger to the container, and run the configuration successfully without any error.

**Actual:**
It prompts a dialog to copy the debugger to the container. Click "Yes" to allow copying vsdbg to the container, an error "The pipe program 'docker' exited unexpectedly with code 126" occurs.
![image](https://user-images.githubusercontent.com/45614674/89884578-57d46400-dbfc-11ea-9a74-4536f24a258b.png)
![image](https://user-images.githubusercontent.com/45614674/89885198-450e5f00-dbfd-11ea-8e8a-18b54780848a.png)

**More Info:**
1. This issue does not reproduce on Windows and Mac.
2. This issue does not reproduce if execute "Compose Up" command for docker-compose.yml.

**Comment by karolz-ms** [comment]
So far what I have found is that the `docker-compose.debug.yml` will try to volume-map the debugger into the container. If the debugger has not been installed on the host machine yet, the volume map will silently fail and VS Code will offer to install the debugger into the container. This is **correct** behavior.

After the user indicates the debugger **should** be copied into the container, we attempt to download the debugger. On my machine this fails with EACCESS error, somewhere in `vsdbgClient.ts`, I believe it is the `ensureVsDbgFloderExists()` method that throws an exception. This will need to be looked at & fixed.

I am going to install the debugger manually now to see if I can get further into the scenario and reproduce the behavior that @v-ruizh observed

**Comment by karolz-ms** [comment]
Just for future info, the command to manually install vsdbg is

```shell
cd
mkdir .vsdbg
curl -sSL https://aka.ms/getvsdbgsh | /bin/bash /dev/stdin -v latest -l ~/.vsdbg -u
```

 (Ubuntu 20.04 LTS)

**Comment by karolz-ms** [comment]
After installing the debugger manually, but without `compose down` (the container still has the invalid volume mount), I can reproduce the reported behavior. I believe it is due to the fact that the container has invalid volume mount and copying the debugger into the container silently fails--but need to verify

**Comment by karolz-ms** [comment]
Verified that if the debugger is installed locally before `compose up` is executed, the attach gesture works

**Comment by BigMorty** [comment]
We should also remove the "(Preview)" from the name of the configuration we scaffold.

**Comment by bwateratmsft** [comment]
@karolz-ms I have an idea on how to solve this. On both Windows and Mac--hopefully Linux too but didn't try yet--if I volume map a folder on the host that doesn't exist, Docker creates that folder, empty, with myself as the owner. If I add files into that folder after the container is started, naturally they "appear" inside the container.

If we ensure installation of the debugger on the _host_ during the resolve attach config, _before_ checking if the debugger is inside the container, then I think this problem goes away.

@BigMorty I've mentioned this elsewhere but I'm reluctant to remove the "Preview" from the name because the whole experience of getting the debugger into the container is still not great. Doing what I'm describing above would help--it would make it so using the `docker-compose.debug.yml` to launch _should_ always result in a working debug config--but it seems error-prone.

I'm getting to the point that I'd really prefer there be a .NET image that has the debugger built-in. I think we can use build arguments in the Dockerfile to use that image if the goal is a debug build. I know one of the stated goals of .NET 5 is to have smaller, single executables; that would be a huge win for VSDBG which is about 200 MB per runtime right now. If it can be shrunk down to a few MB, maybe it could just be bundled into the regular image.
