### ISSUE TITLE
No way to set `--ip` flag on `docker-run` tasks

### ISSUE THREAD

**Issue by ForceConstant** [microsoft/vscode-docker#2259]
I want to use the docker-run task type to start a container, but would also like to set the ip address? How can I do this, I don't see anything in the reference.
Thanks.

**Comment by PavelSosin-320** [comment]
What do you mean by saying Container IP? On which network? Please, read about [Docker networking](https://docs.docker.com/network/). You can find detailed explanation there. This is not 5 min reading but absolutely necessary.

**Comment by ForceConstant** [comment]
@PavelSosin-320 This is how I would do something like this on the command line: `docker run --rm  --net my_container_net --ip 10.120.100.2 -it -p 22:22/tcp my_container:latest`  Static IP, and not just hostname is necessary due to the applications that are being run.

**Comment by bwateratmsft** [comment]
The `--ip` flag does not exist currently on the `docker-run` task. We can consider adding it.

**Comment by PavelSosin-320** [comment]
Static IP exists in a single scenario: standalone container running on a standalone node. The real IP can be derived from docker node inspect. Docker endpoint can be provided in many ways: Standalone docker, Cloud Instance. Swarm, Docker stack deployed to Kubernetes. It will be very disappointing to get such a limitation - single scenario compatibility: Docker-provided-by-Docker-desktop-without-Kubernetes-installed-withuot-Swarm activated.
If somebody needs static IP the option of network type=host and Host with static IP or localhost doesn't require any development.

**Comment by PavelSosin-320** [comment]
P.S. static IP of the Docker container is impossible because Docker engine governs containers' lifetime and replication.  It can't ask "Say me which IP to assign?" every time when it instantiates, restarts, attaches to a network, replicates containers.  docker run has nothing common with run application.

**Comment by PavelSosin-320** [comment]
@bwateratmsft Taking into account that the default of docker network create is attachable = true today the static coupling between network and port in one parameter will be extremely inconvenient because it produces a huge number of combinations. It also eliminates using of -P (in capital).
Docker networking is one of the best-designed concepts in Application development and hardly requires improvement.

**Comment by bwateratmsft** [comment]
This is now fixed in Docker extension version 1.7.0.
