### ISSUE TITLE
There are 2 notifications during executing prune action

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2308]
**OS:** Win10
**Build Version:** 20200909.2

**Repro Steps:**
F1 -> Docker Images: Prune... -> Click 'Remove' to confirm remove all dangling images -> Check the notification during this action.

**Expect:**
There is only one notification 'Pruning images...' during executing prune action.
![image](https://user-images.githubusercontent.com/45614674/93060843-4a9c1080-f6a5-11ea-8bf5-5f7d4c6d9281.png)

**Actual:**
There are 2 notifications during executing prune action.
![image](https://user-images.githubusercontent.com/45614674/93060806-3ce68b00-f6a5-11ea-80e7-4d48eee668c9.png)

**More Info:**
This issue also reproduces when prune containers/volumes/networks.

**Comment by bwateratmsft** [comment]
This is by design although the timing of the toasts is a little weird sometimes. The first toast, "Pruning images...", shows while the prune operation is happening. We added this because we saw in telemetry a lot of people would try to prune multiple times and fail if one is in progress. There wasn't really any way to tell that the prune operation was underway if it took some time.

However, when it happens nearly-instantly like it might in the case where nothing is removed, they both show up at roughly the same time. The "Pruning images..." one should go away _almost_ immediately but they both can appear at the same time.
