### ISSUE TITLE
There is no option to overwrite existing files when repeatedly executing 'Add Docker Compose Files to Workspace…' command

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2310]
**OS:** All
**Build Version:** 20200909.2

**Repro Steps:**

1. Open an existing .Net Core project workspace that has a Dockerfile.
2. Run 'Add Docker Compose Files to Workspace…' command.
3. Repeat the step 2 again.
4. Check the result.

**Expect:**
It should provide an option to overwrite an existing file or create a new file.

**Actual:**
There is no option to overwrite existing files or create a new file.

**More Info:**

1. This issue also reproduces for Python project.
2. Only provide the option to overwrite the existing files or cancel for Node.js Project, but no option to create a new file.
 ![Screen Shot 2020-09-14 at 6 50 00 PM](https://user-images.githubusercontent.com/62053665/93079885-69a79c00-f6bf-11ea-95d2-e682e979ba53.png)

**Comment by bwateratmsft** [comment]
This is by design. I made a change to match the behavior we have in Visual Studio--if the file we are going to scaffold is identical to what is already there, we won't do anything since it isn't necessary. We will only prompt if we encounter a file that is different from what we want to scaffold. Even if only one such file exists, we will still show the "Overwrite All" button, but in that case its behavior won't be different from "Overwrite".

I updated the test case "P0 Add Docker Files - Node.js" to mention that you'll need to change one of the scaffolded files in order to get the overwrite prompt to show.
