### ISSUE TITLE
Debug with Console.ReadLine

### ISSUE THREAD

**Issue by bwfilms** [microsoft/vscode-docker#2406]
I have a simple .NET Core C# console app running inside a Linux docker.

string message = Console.ReadLine();
Console.WriteLine(message);

When debug, I see no way of entering data for the Console.ReadLine().

I've done searches and using "console": "integratedTerminal" in the launch.json file only works for non-docker-hosted app.

**Comment by bwateratmsft** [comment]
I'm not sure if this will be possible because stdin and stdout are used by vsdbg to do the actual debugging.

@philliphoff do you have any ideas on how to do this?

**Comment by bwateratmsft** [comment]
@gregg-miskelly do you know if this is possible?

**Comment by gregg-miskelly** [comment]
Here is how I think we could do this --

First, we need to add a little helper program to the container which will relay Debug Adapter Protocol. This will need to:
   * Create a unique UNIX domain socket name
   * Open a domain socket with that name, and wait for a connection
   * Send the name back to your code
   * Once vsdbg connects: forward on traffic until disconnect

To launch we:
1. Tell the VSDebugAdapterHost to launch, but instead of of supplying a command line, instead we need a custom stream
2. The custom stream will scape the first line of output (the name of the domain socket), but otherwise just relay the adapter protocol
3. When it sees the domain socket name, it:
   * Spawns off a new visible Console
   * Run something like: `docker exec <path-to-vsdbg>/vsdbg/vsdbg --connection={domain-socket-name-from-relay}` make sure to enable pseudo-terminals in this instance

**Comment by bwateratmsft** [comment]
Would all this be code changes or is this something the user could do?

**Comment by gregg-miskelly** [comment]
I just realized that this issue was about VS Code (sorry, I was thinking VS).

If you use remote extension support I would have thought that `"console": "integratedTerminal"` would just work. If not, this feels like a bug in the VS Code remote extension support. I just verified this work with WSL, so I would assume it also works for Docker.

If you can't use remote extension support (ex: if you can't build in the remote containers), here is how to get a poor man's version of this as a user -- 
1. Open up a terminal (a.k.a. console), and `docker exec` '/bin/sh' in your container
2. Run `tty` which should print the pseudo-terminal device in the running container
3. Run `sleep <big-number>` which should park that terminal in a spot where nothing is messing with the standard I/O handles
4. Go back to VS Code, open your launch.json file, and modify `args` to redirect stdin/out/err to the pseudo-terminal. Ex: `"args": ">/dev/pts/0 2>/dev/pts/0 </dev/pts/0"`
5. Start debugging
6. Expected result: all stdin/out/err text should appear in the terminal that was started in step 1

**Comment by PavelSosin-320** [comment]
The name of the trick is socat to / from STDIN and STDOUT. Everybody can do it. Unfortunately, socat is in /out from distros and containers due to security considerations.

**Comment by bwateratmsft** [comment]
@bwfilms does @gregg-miskelly's suggestion above work? I don't think this is a common enough scenario for us to make code changes but we do want to help you work around it if possible.
