### ISSUE TITLE
crash over!

### ISSUE THREAD

**Issue by phpreza** [microsoft/vscode-docker#2426]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.contexts.inspect
Error type: 1
Error Message: Process 'docker context inspect default' exited with code 1
Error: 'docker' is not recognized as an internal or external command,
operable program or batch file.

Version: 1.7.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:46:91411
ChildProcess.emit events.js:223:5
maybeClose child_process.js:1021:16
Process.ChildProcess._handle.onexit child_process.js:283:5
```

</details>

**Comment by bwateratmsft** [comment]
@phpreza is Docker installed?

**Comment by PavelSosin-320** [comment]
@phpreza OS Release: 10.0.19041 looks too old! Please update Windows 10 to 2004 and then upgrade Docker desktop. You missed many updates.

**Comment by bwateratmsft** [comment]
I think 19041 is 2004

**Comment by PavelSosin-320** [comment]
Winver shows Windows 10 2004 as Version 2004 (build 20..........
The current Docker Desktop Ege is 2.4.2. .....
Windows [Version 10.0.20231.1005] - may be dev **pre-release but 10.0.20** is important because WSL2 Linux Kernel 4.9 came with 10.0.20  something
  **Client Version:           19.03.3** !!!! - this is the correct Docker CLI spec for Docker context support
 API version:       1.40
You can use WINGET Docker Desktop which has come with 2004 to save time on upgrades.

**Comment by bwateratmsft** [comment]
I'm not following. The [wiki page](https://en.wikipedia.org/wiki/Windows_10_version_history#Channels) with version history has 2004 (aka 20H1) as 19041; 20H2 as 19042 which matches what I have:

![image](https://user-images.githubusercontent.com/36966225/97186392-9bf4f080-1777-11eb-8a22-5160835a2c61.png)

The user has 10.0.19041 which is Win10 2004.

**Comment by PavelSosin-320** [comment]
2004 was planned to have the name 20H2 but in fact, was rolled out in late May and had several maintenances upgrades. If you have Docker Desktop EE license you or your DevOps can call Mirantis. Otherwise, try to roll updates forward. My Docker CE 2.4.2.0 is pretty stable and conformant to the Docker 19.03 spec.

**Comment by PavelSosin-320** [comment]
Look at 2004 (aka 20H1). Microsoft missed April 2020, i.e. 2004 release target. 2004 was released at the end of May.
I see you have Windows 10 Enterprise. From my experience as an Enterprise developer Enterprise versions are behind Pro and Dev Pre releases for several months. I afraid, You have to wait until all maintenance updates for Windows will be installed and tested by your company IT.
All my Docker Desktop CE releases until 2.4.1 were absolute junk unable to start or caused WSL VM crash.

**Comment by bwateratmsft** [comment]
This issue has been closed because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/azcodeissuereporting) guidelines.

Happy Coding!
