### ISSUE TITLE
Extension fails to load with latest Docker edge

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode-docker#2452]
Repro steps:

1. Install latest Docker Edge candidate:  
      https://desktop-stage.docker.com/win/edge/49266/Docker%20Desktop%20Installer.exe
      https://desktop-stage.docker.com/mac/edge/49266/Docker.dmg
2. Overwrite Docker executable with the one from https://github.com/docker/compose-cli/releases/tag/v1.0.0
   On Mac you might need to do `sudo xattr -rc /Applications/Docker.app` to disable signature checking and the "application is damaged" error.
3. Open Docker extension

Expected: extension works

Actual: extension does not load with `Cannot read property 'Name' of undefined` error

The issue is in ContextManager.ts line 222: the output of `context ls --format "{{json .}}"` is now a single line of JSON, not one line per context, for example:

```shell
[{"Current":false,"Description":"rg-aci-play@westus2","DockerEndpoint":"","KubernetesEndpoint":"","Type":"aci","Name":"acictx","StackOrchestrator":""},{"Current":true,"Description":"Current DOCKER_HOST based configuration","DockerEndpoint":"unix:///var/run/docker.sock","KubernetesEndpoint":"","Type":"moby","Name":"default","StackOrchestrator":"swarm"},{"Current":false,"Description":"rg-guestbookexpress@westus2","DockerEndpoint":"","KubernetesEndpoint":"","Type":"aci","Name":"gbexpress","StackOrchestrator":""}]
```

**Comment by gtardif** [comment]
Looking into the best way to fix this to avoid breaking VSCode existing deployments. 
We'll discuss the best way to make this more robust in the long term in VSCode Docker extension.

**Comment by bwateratmsft** [comment]
@gtardif folks upgrade VSCode extensions really, really quickly (because they upgrade automatically) so I'm not super concerned about old versions of the extension. I kinda prefer to have the new output format with one single JSON object instead of one-per-line. We can produce a 1.7.1 release in just a few hours if need be.

**Comment by gtardif** [comment]
OK, thanks, I didn't know this could be that quick! I'll keep this in mind next time.
We're still supporting `docker context ls --format "{{ json .}}"` for backward compatibility so it makes sense in this regard to not change the returned multi-line json. 
But we're pushing for a simpler `docker context ls --format json` that returns a single json array, you can use this with this new version. 
Moreover, the json returned includes the context type in the list, with a new field "ContextType" (with the json array or the multi-line json). 

Question : initially we had added a field "Type" but when fixing the issue yesterday I noticed this was also causing issues in the VSCode Docker extension, I think because of https://github.com/microsoft/vscode-docker/blob/master/src/docker/ContextManager.ts#L234. 
I'm not sure where this "Type" comes from, is this related to the default context const (https://github.com/microsoft/vscode-docker/blob/master/src/docker/ContextManager.ts#L35)? 

Note unfortunately that there might still be users with older version of the docker cli that won't support `docker context ls --format json` or the new "ContextType" field, and users have the option in Desktop to disable the cloud integration that brings these things.

**Comment by bwateratmsft** [comment]
@gtardif What was the problem you were seeing on https://github.com/microsoft/vscode-docker/blob/master/src/docker/ContextManager.ts#L234? We intentionally wanted to copy in the `Type` field if it was present, otherwise we have to make an assumption that no type and no Docker endpoint is ACI.
