### ISSUE TITLE
When connecting debugger, breakpoints try to apply to files located in the container.

### ISSUE THREAD

**Issue by ADustyOldMuffin** [microsoft/vscode-docker#2454]
Hello! Thank you for the wonderful add-on.

In my project I'm running `docker-compose build -f {path} --build-args {a bunch of build args}` and then `docker-compose up`. With this I'm trying to debug the container booted from this process with the Docker dotnet container attach which attaches correctly and works. The issue comes from when I try and place a breakpoint, locally it will place the breakpoint and then instantly disappear with the error of not file found at /app/{workspaceFilePath}, but it will hit the breakpoint in the container and show me debug output I just can't walk through in vscode.

I'm working on windows with linux containers and my project file structure looks like 
```
RootFolder
	Project1
		DockerFile
	Project1.Test 
	docker-compose.yml
	.env
```
In the images below, you can see I set a breakpoint, it goes away in vscode but still places it in the container. When I run and hit the breakpoint, it hits it correctly but I can't see it hitting in my file.

![image](https://user-images.githubusercontent.com/41391321/97719987-b986ca80-1a95-11eb-9dfe-322dd3fa4dde.png)
![image](https://user-images.githubusercontent.com/41391321/97720097-db804d00-1a95-11eb-93f5-9c9da891d254.png)

**Comment by bwateratmsft** [comment]
Hey @ADustyOldMuffin, I've seen this issue happen before; it has to do with the source mapping. By default we scaffold (in the "Docker: .NET Core Attach (Preview)" launch config in .vscode/launch.json):
```json
"sourceFileMap": {
    "/src": "${workspaceFolder}"
},
```

In our default Dockerfile, in the build container, the sources are copied into `/src` in the container where they are built:
```dockerfile
# ...

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["DemoSite.csproj", "./"]
RUN dotnet restore "DemoSite.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "DemoSite.csproj" -c Release -o /app/build

# ...
```

This stamps the PDBs with `/src` as being the root location for source files. Since you're debugging remotely, VSDBG wants a mapping of `/src` => `(somewhere)`, so that when the you ask for a breakpoint at `(somewhere)/MyFile.cs#123`, it knows that in the symbol files it will appear as `/src/MyFile.cs#123`.

I think if you change that `${workspaceFolder}` to `${workspaceFolder}/Project1`, it might work. `/src` might also need changing to `/app` but it depends what's in your Dockerfile. Let me know if this (or some other) combination works!

**Comment by ADustyOldMuffin** [comment]
Ah thank you! I wasn't grabbing the idea that `/src` was actually referencing the main file in my build container, I thought it was just saying "where are the source files?". The issue stemmed from that I was working off the dotnet example Dockerfile which uses `/app` as the main location not `/src` so the fix is either change the folder name to `/src` or change the task to use `/app`.
