### ISSUE TITLE
Docker don't update the data in extension but works in terminal

### ISSUE THREAD

**Issue by jifox** [microsoft/vscode-docker#2492]
Issue Type: <b>Bug</b>

Hello

The docker extension is not updating the data   (Containers, Images, ...) but is working without problems in vscode terminal.

Error: write EPROTO 139849010243456:error:1408F10B:SSL routins:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\

KR Josef

Extension version: 1.7.0
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.20257
Remote OS version: Linux x64 5.4.0-53-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (10.55GB free)|
|Process Argv|--crash-reporter-id 33dcbe68-5fb0-4cba-890a-4454b94a0e7e|
|Screen Reader|yes|
|VM|67%|

|Item|Value|
|---|---|
|Remote|SSH: swarm-services|
|OS|Linux x64 5.4.0-53-generic|
|CPUs|Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz (4 x 2400)|
|Memory (System)|5.81GB (1.52GB free)|
|VM|50%|
</details>

**Comment by jifox** [comment]
Also I've already checked that no Docker settings are active in settings.json

**Comment by bwateratmsft** [comment]
@jifox What error is present in the explorer?

**Comment by jifox** [comment]
@bwateratmsft 

What do you mean with "exploerer"?

Error: write EPROTO 139849010243456:error:1408F10B:SSL routins:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\

In the terminal window there is no error

**Comment by jifox** [comment]
![Screenshot 2020-11-16 210941](https://user-images.githubusercontent.com/8406301/99302809-2d73f180-2850-11eb-98fd-68971d98c4be.png)

**Comment by bwateratmsft** [comment]
@jifox You may be using the extension in UI mode which is probably not what you want. If you go to the Extensions tab, does the Docker extension appear as installed in the remote server, similar to in the WSL screenshot below?

![image](https://user-images.githubusercontent.com/36966225/99403399-6ba4fb80-28b8-11eb-8fde-a1383b73c2f6.png)

If it is not installed, can you try installing it and reloading VSCode, and see if that fixes the issue?

**Comment by jifox** [comment]
![Screenshot 2020-11-16 210941](https://user-images.githubusercontent.com/8406301/99424179-b008b980-2901-11eb-92c2-5be1811d85f2.png)

It was already installed in SSH Swarm Service

**Comment by bwateratmsft** [comment]
I've been able to find a handful of threads with similar error messages:
https://discuss.atom.io/t/why-would-i-be-getting-error-write-eproto-when-making-an-https-request-in-an-electron-app/22760
https://github.com/nodejs/node/issues/3692
https://lifesaver.codes/answer/http-https-client-requests-throwing-eproto

It sounds like this is an external issue somehow related to TLS settings. That said, why use `tcp://127.0.0.1:2376` to connect to the local Docker host, rather than using the default (which is `unix:///var/run/docker.sock`)?

**Comment by jifox** [comment]
@bwateratmsft 
The unix:///var/run/docker.sock worked without problem remotly when connected through SSH and on the local teminal

After updating to the latest docker-ce version (Docker version 19.03.13, build 4484c46d9d) the tcp://localhost:2376 worked only locally on the linux host but not through ssh connection.

**Comment by jifox** [comment]
![Screenshot 2020-11-16 210941](https://user-images.githubusercontent.com/8406301/99434844-92425100-290f-11eb-8b4e-c2dff16bee73.png)

**Comment by ljgww** [comment]
After recent update on Ubuntu18 this stopped working. Default configuration looks ok. Lock file is present. Docker service is running (can enter commands from cli). But Docker extension is having a problem.
![image](https://user-images.githubusercontent.com/776581/99512507-d40fdd80-2989-11eb-9ae5-a3c369de0b00.png)

**Comment by bwateratmsft** [comment]
@ljgww Is this is a remote session? Do you have anything set for `DOCKER_HOST` environment variable or `docker.host` VSCode setting?

@jifox I'm not really sure what the problem is. There's any number of reasons that networking can break down. However, I'd recommend just using the default context for `localhost` connections, i.e. `unix:///var/run/docker.sock`. It seems like it adds unnecessary complexity to use a `tcp://` endpoint for local connections.
