### ISSUE TITLE
[Codespaces] The pulled images are outdated before restarting VS Code

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2496]
**OS:** Win 10
**Build Version:** 20201114.1
**Environment:** GitHub Codespaces (Both remote/browser and local)

**Repro Steps:**
1. Enable the setting "Docker > Images: Check for outdated images".
2. Open Docker view, if the image "alpine:latest" is present, remove it: docker rmi alpine:latest.
3. Pull any image, and tag it as "alpine:latest": docker pull hello-world:latest && docker tag hello-world:latest alpine:latest.
4. Expand and check the above images.

**Expect:**
There is no warning icon and text reading "Out of date" for the pulled images.
![image](https://user-images.githubusercontent.com/45614674/99363350-965e7680-28ef-11eb-88b3-c5f6825cbbf1.png)

**Actual:**
The pulled images are outdated before restarting VS Code.
![image](https://user-images.githubusercontent.com/45614674/99362040-e9cfc500-28ed-11eb-8a40-b21eef7f3523.png)

**More Info:**
This issue does not reproduce in non-codespaces environment.

**Comment by bwateratmsft** [comment]
This probably has to do with the logic we added to cache the results of the call on a once-per-day basis...

**Comment by bwateratmsft** [comment]
Just to update, I don't think there is a product bug here. However, I've been using some spare time to work on a helper extension that would allow for manipulating mementos, which would be helpful for me personally in a lot of scenarios, and would also make it easier to test things like this. The memento storage, as-is, is nearly impossible to view or edit. Being able to view (and edit!) values would simplify testing scenarios. For example, in this issue, the memento used for tracking the out-of-date images and last check date could be wiped in order to force a re-check on the next launch.

**Comment by bwateratmsft** [comment]
I have updated the test case notes to explain how to clear the mementos used for caching, which will force a live refresh of outdated images.
