### ISSUE TITLE
enableDebugging seems to overwrite /app in container for dotnet core app

### ISSUE THREAD

**Issue by ADustyOldMuffin** [microsoft/vscode-docker#2527]
I have a Dockerfile that looks like so 

```
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /src

ARG PACKAGE_SOURCE
ARG SOURCE_USERNAME
ARG SOURCE_PASSWORD

RUN dotnet nuget add source $PACKAGE_SOURCE --username $SOURCE_USERNAME --password $SOURCE_PASSWORD --store-password-in-clear-text

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
WORKDIR /src/.
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
EXPOSE 80
EXPOSE 443
WORKDIR /app
COPY --from=build-env /src/out .
ENTRYPOINT ["dotnet", "myapp.dll"]
```
Where I have build arguments for using a private nuget package source, currently I use docker-compose to help with this and a bunch of other setup by passing in the build arguments that way.

I was hoping to use the `Docker .NET Core Launch` launch setting to debug said container, and instead of messing with my docker-compose file use the task values to do this for me.

My tasks look like this

```
{
    "type": "docker-build",
    "label": "docker-build: debug",
    "dependsOn": [
        "build"
    ],
    "dockerBuild": {
        "tag": "myapp:dev",
        "target": "base",
        "dockerfile": "${workspaceFolder}/myapp/Dockerfile",
        "context": "${workspaceFolder}",
        "pull": true,
        "buildArgs": {
            "PACKAGE_SOURCE": "https://asourceurl.com",
            "SOURCE_USERNAME": "ausername",
            "SOURCE_PASSWORD": "password"
        }
    },
    "netCore": {
        "appProject": "${workspaceFolder}/myapp/myapp.csproj"
    }
},
{
    "type": "docker-run",
    "label": "docker-run: debug",
    "dependsOn": [
        "docker-build: debug"
    ],
    "dockerRun": {},
    "netCore": {
        "appProject": "${workspaceFolder}/myapp/myapp.csproj",
        "enableDebugging": true,
		"configureSsl": true
    }
},
```
When I launch debugging everything runs as it should and the build does fine, but originally when the app tries to boot it gives an error saying dotnet cannot find the myapp.dll file. If I set to copy the files into a different file location, like say `/myapp` and change the entry point it'll at least start. 
Unfortunately once started it doesn't load any of the symbols for debugging. 

So originally the issue is that setting `enableDebugging: true` attaches a volume `/app` and `/src` (which I might add is not documented anywhere), which is the current default Dockerfile location for dotnet apps, and when trying to remedy this myself since I can't find settings to change this behavior it seems to not be able to load symbols and I'm not sure why.

Thanks!

**Comment by bwateratmsft** [comment]
I think in a scenario like this your best bet is to use `docker-compose up` to launch the app and use an attach configuration in launch.json:
![image](https://user-images.githubusercontent.com/36966225/100623797-a400fc80-32f0-11eb-8144-a3a3cf867495.png)

The default .NET Docker debugging does a ton of optimizations to make the startup time tolerable--for example, it builds the app locally and maps in the binaries, along with the source and symbols, rather than building in the container. It also builds only the first stage by default but since your Dockerfile doesn't have a `base` stage in it, it is not doing that.

Alternatively, you could try re-scaffolding the Dockerfile using the command palette with "Docker: Add Docker files to workspace...", and then merging in from your existing Dockerfile what is needed to make the custom NuGet source work.

Let me know if one of those approaches works!

**Comment by ADustyOldMuffin** [comment]
I tried with the default dockerfile from the add docker files to workspace and ended with the same result where it just overwrites the `/app` folder when the `enableDebugging` is set to true. 

I had found a way around to halt the starting of the app until a debugger attaches as I needed to debug the entry point of the app so I'm back to using docker-compose commands on my own. 

I was just hoping to set the build steps in vscode for others on the project to ease onboarding.

**Comment by bwateratmsft** [comment]
Right, overwriting `/app` with the source from the host is intentional when `enableDebugging` is `true`. This makes build happen on the host--which is much faster--then starts the container but not doing anything. `vsdbg` is also mapped in. The debug configuration resolves, which uses `docker exec` to start `vsdbg` in the container, which in turn receives the debug configuration which instructs it to start the app itself. This is how we attach from the moment an app is started, so startup code can be debugged.
