### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by aod7br** [microsoft/vscode-docker#2529]
- Issue Type: `Performance`
- Extension Name: `vscode-docker`
- Extension Version: `1.8.0`
- OS Version: `Linux x64 4.15.0-124-generic`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/ms-azuretools.vscode-docker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by bwateratmsft** [comment]
@aod7br does this happen consistently?

**Comment by miversen33** [comment]
When I connect to a running docker instance, I get the following process spawned off 5 times

`/root/.vscode-server/bin/{{container_id}}/node_modules/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/package.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store -g !**/.classpath -g !**/.project -g !**/.settings -g !**/.factorypath -g !**/node_modules/** --no-ignore --follow --no-config --no-ignore-global`

My CPU usage immediately maxes out and my ram consumption quickly moves up to around 6-7GB. Killing the vscode instance that is attached to the container immediately drops my usage down to something more acceptable (2-3% CPU usage <1GB RAM usage).

I am not sure what else I can provide here, but I have seen the following issues raised in relation to this, all unceremoniously closed by the vscode bot.

https://github.com/microsoft/vscode-docker/issues/2471
https://github.com/microsoft/vscode-docker/issues/2419
https://github.com/microsoft/vscode-docker/issues/2373
https://github.com/microsoft/vscode-docker/issues/2281
https://github.com/microsoft/vscode-docker/issues/2276
https://github.com/microsoft/vscode-docker/issues/2237
https://github.com/microsoft/vscode-docker/issues/2230
https://github.com/microsoft/vscode-docker/issues/2088
https://github.com/microsoft/vscode-docker/issues/2027
https://github.com/microsoft/vscode-docker/issues/2522
https://github.com/microsoft/vscode-docker/issues/2023
https://github.com/microsoft/vscode-docker/issues/1937
https://github.com/microsoft/vscode-docker/issues/1225
https://github.com/microsoft/vscode-docker/issues/991
https://github.com/microsoft/vscode-docker/issues/990
https://github.com/microsoft/vscode-docker/issues/912
https://github.com/microsoft/vscode-docker/issues/911

I love the idea of this extension, but it is entirely unusable in its current state. Please let me know what other information I can provide to help out.

>     Issue Type: Performance
>     Extension Name: vscode-docker
>     Extension Version: 1.9.0
>     OS Version: Ubuntu Server 20.04 (LTS) {Linux 5.4.0-58-generic}
>     VSCode version: 1.52.1

**Comment by karolz-ms** [comment]
@miversen33 thank you and sorry for the bad experience. 

The "high CPU load" issues are getting closed because there is usually not enough information in the profile to determine what caused the delay, and people rarely provide any further clues after submitting the issue.

That said, we do take performance seriously and comb through telemetry upon every release. Between version 1.50 and version 1.8.0 we (@bwateratmsft specifically) made several changes that reduced combined load and activation time for the extension by over 50% across all platforms. Our current median load and activation time is approximately 1.1 second on Windows and approximately 0.7 seconds on Mac and Linux.

Regarding the problem you are experiencing, do you see that after doing "Attach Visual Studio to container" command? If so, this is a command that is provided by the remote-containers extension. [This wiki entry](https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory) might work for you as a workaround. If not, feel free to open an issue on the [VSCode Remote Releases](https://github.com/microsoft/vscode-remote-release/issues) repo.

**Comment by miversen33** [comment]
> do you see that after doing "Attach Visual Studio to container" command
That is when this happens. Ill go peek at that repo, though I assumed the issue was related to the vscode-docker extension as that is what I use to connect to the container.
![vscode screenshot](https://user-images.githubusercontent.com/2640668/102660375-8cbf6d00-4140-11eb-98af-e9ef8a4d2bea.png)

**Comment by bwateratmsft** [comment]
The "Attach Visual Studio Code" command is part of the Remote - Containers extension; they have it appear in our context menu though. I'm not really sure what the purpose of that `rg` executable is, it looks like it's searching for a package.json file, but I don't know what for. @miversen33 I'd recommend opening something in their issues repo: https://github.com/microsoft/vscode-remote-release/issues
