### ISSUE TITLE
Enable Tagging with your Docker Username

### ISSUE THREAD

**Issue by justalemon** [Microsoft/vscode-docker#253]
As you can see on the [Push images to Docker Cloud](https://docs.docker.com/docker-cloud/builds/push-images/) guide, if you want to upload the images that you created to the DockerHub, you need to tag them with the format `{USERNAME}/{IMAGENAME}:{TAG}`.

Why is not possible to tag the images with that format directly if we are logged into DockerHub? (via `Docker: Build Image` or `Right Click > Build Image`)

If is possible, add a configuration to toggle this option.

(I could not find any option on the configuration or open issue, so I opened one)

**Comment by chrisdias** [comment]
there are two configuration options for the docker extension that should take care of this for you:

``` json
    "docker.defaultRegistry": "",
    "docker.defaultRegistryPath": "chrisdias",
```

`docker.defaultRegistry` lets you define a custom registry path to prepend to the name when the image is built. For DockerHub, you want to leave this blank. If you were always wanting to push to (for example) an Azure container registry, you would set it to something like `myAzureContainerRegistry.azurecr.io`.

`docker.defaultRegistryPath` is the path within the registry (sometimes called a repository) that you want set by default.  For DockerHub you would put in your username.

Now, when you `tag` the image, the extension will pick up these settings and try to fabricate a name, which you can always override.

I don't pick up these settings for the build command because they seemed to always get in the way during development. I don't want to deal with very long names. Its not until I want to push the image to a registry do i want to set the "full" name. So, do a build, then right click on the image and tag it.

**Comment by justalemon** [comment]
In my `config.json` i have:

```js
"docker.defaultRegistryPath": "justalemon"
```

Because the default config option of `docker.defaultRegistry` is an empty string, there's no need to change it.

Still, i don't get the desired format (in this case `justalemon/plex:latest`):

![imagen](https://user-images.githubusercontent.com/11861253/39106289-1828094a-4691-11e8-91b7-e60eac2847cd.png)

**Comment by justalemon** [comment]
cc @chrisdias

**Comment by Marco98** [comment]
@justalemon it will at least work, if you're tagging an image (Docker: Tage Image)

**Comment by PrashanthCorp** [comment]
@justalemon , I'm unable to repro [your comment](https://github.com/Microsoft/vscode-docker/issues/253#issuecomment-383447518). Does it still repro for you?

**Comment by justalemon** [comment]
@PrashanthCorp Yep:

![image](https://user-images.githubusercontent.com/11861253/44106814-fc32e806-9fcb-11e8-8362-b7c7454a4f91.png)

![image](https://user-images.githubusercontent.com/11861253/44106862-2393190c-9fcc-11e8-8c9e-af091d33297c.png)

![image](https://user-images.githubusercontent.com/11861253/44106880-2ef499ce-9fcc-11e8-9b33-5f4b5cf3d910.png)
