### ISSUE TITLE
Feature Request: View of which Volumes are being accessed by running containers

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#2538]
When I'm running multiple containers whether it be through a compose group or multiple single Docker projects, I want to have some sort of view for all the volumes that are being accessed on my host machine alongside which containers are accessing them.

**Comment by PavelSosin-320** [comment]
@ucheNkadiCode The relation of Container - volume is Multi-to-multi because volumes can be **shared**! You can see only Volumes per given container because Volume is the 1st class Docker artifact and can exist without any container that uses it. But you can see orphaned volumes using docker volume ls -qf dangling=true. Volumes are mounted to the given Container paths but don't know the path.  Please, clarify what is the exact requirement. [Docker volume capabilites](https://docs.docker.com/engine/reference/commandline/volume_ls/). It is recomended to use --label to designate volume usage!

**Comment by bwateratmsft** [comment]
Just to be clear, without a _very_ significant amount of refactoring work, this cannot be done in the Docker Explorer view. This is due to the many-to-many relationship that @PavelSosin-320 points out. However, there are things we can do--for example, a command like "view attached volumes" that would open a text document listing the volumes, or vice versa. There's also the possibility of making a web view but that would also be a very significant amount of work.

**Comment by PavelSosin-320** [comment]
I suppose the volume labeling and volume view filtered by the label is easy and fulfill  90% of practical requirements. The use of metadata is always practical.

**Comment by dbreshears** [comment]
Consider listing volume mounts under containers with links to the actual volume

**Comment by bwateratmsft** [comment]
This could be solved by #2592.

**Comment by bwateratmsft** [comment]
This is now released in Docker extension version 1.10.0.
