### ISSUE TITLE
Unclear error message when context other than default is used with Single, Compose, and Compose Debugging 

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#2548]
Running through the sample of https://github.com/microsoft/python-sample-vscode-django-tutorial/blob/tutorial/README.md

Running the regular Python: Django configuration goes totally fine, but the issue arises when I try to add docker files to workspace and run the same application.
Issues: 
After Adding Dockerfiles to Workspace and **including** Compose:

- When trying to run Docker: Python - Django, we see 
![image](https://user-images.githubusercontent.com/20650058/101461560-ebd6e380-38ef-11eb-8f42-0001d9acc64b.png)

In the terminal I see 
```bash
> docker build --rm --pull -f "C:\Users\...\python-sample-vscode-django-tutorial/Dockerfile" --label "com.microsoft.created-by=visual-studio-code" -t "pythonsamplevscodedjangotutorial:latest" "C:\Users\...\python-sample-vscode-django-tutorial" <

unknown command "build" for "docker"
The terminal process terminated with exit code: 1.
```

If I click "Debug Anyway" I see 
```bash
 cd '.'; & 'c:\Users\...\python-sample-vscode-django-tutorial\env\Scripts\python.exe' 'c:\Users\...\.vscode\extensions\ms-azuretools.vscode-docker-1.8.1\resources\python\launcher.py' '55826' '--' 'manage.py' 'runserver' '0.0.0.0:8000' '--nothreading' '--noreload' 'pythonsamplevscodedjangotutorial-dev' 
docker exec -d pythonsamplevscodedjangotutorial-dev python3 /debugpy/launcher host.docker.internal:55826 -- manage.py runserver 0.0.0.0:8000 --nothreading --noreload
unknown shorthand flag: 'd' in -d
```
Also, another issue is that if I try to select Compose Up on the **docker-compose.debug.yml** file, it seems as though we are still trying to run the regular docker-compose.yml file and both fail with this message:

```bash
Executing task: docker compose -f "docker-compose.yml" up -d <

[+] Running 0/0
panic: runtime error: slice bounds out of range [:-13]

goroutine 40 [running]:
github.com/docker/compose-cli/progress.lineText(0xc0003e0840, 0x26, 0x0, 0x0, 0x0, 0x20bbf96, 0x7, 0x0, 0xbfebee14a3596f78, 0x37412699, ...)     
        github.com/docker/compose-cli/progress/tty.go:154 +0x6dc
github.com/docker/compose-cli/progress.(*ttyWriter).print(0xc0004ae7d0)
        github.com/docker/compose-cli/progress/tty.go:127 +0x6a5
github.com/docker/compose-cli/progress.(*ttyWriter).Start(0xc0004ae7d0, 0x23ac540, 0xc000094010, 0x0, 0x0)
        github.com/docker/compose-cli/progress/tty.go:56 +0x65
github.com/docker/compose-cli/progress.Run.func1(0x0, 0x0)
        github.com/docker/compose-cli/progress/writer.go:95 +0x4e
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0004ad350, 0xc000499560)
        golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57 +0x62
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:54 +0x71
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command docker compose -f "docker-compose.yml" up -d" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
```

Update: It turns out that each of these scenarios have to do with the fact that I was using a context in the Docker Extension other than "default", but could there be clearer messaging so the user knows to switch their context? Maybe an error notification could popup with a button that says "switch to default".

**Comment by karolz-ms** [comment]
@ucheNkadiCode you are probably using ACI Docker context--the tutorial must be run with local Docker context

**Comment by ucheNkadiCode** [comment]
I would like to reopen this issue to promote clearer error messaging for when a user is not using the local Docker context and trying to build build their application. 

This fix did help so thank you!

**Comment by karolz-ms** [comment]
Sounds good @ucheNkadiCode 

This issue is not really specific to Python or Django--I have updated the title accordingly.

I suggest that we approach this comprehensively. That is, 
1. Do a review of all commands exposed by the extension and identify these that do not work with local Docker context, and result with unclear error message.
2. Decide what error message would be better for cases identified in step 1.

Some issues to consider when going down the route of trying to guess what the reason of an error might be (in order to give user a good hint):

1. We currently have 3 types of contexts (or "backends", in Docker parlance): local, ACI, and ECS. Are we, the Docker extension team, up for testing differences between ACI and local **and** ECS and local? There might be other types of backends coming in the future. Are we up for testing and adjusting the error messages for them as well?

2. The capabilities of all backends are a moving target. For example, a couple of months ago a backing Azure file share had to be pre-created to use it as a volume with compose and ACI-type context. Now Docker takes care of creating that volume on demand. The `docker build` command, which fails today with ACI context, and which started this issue, **could conceivably work tomorrow** if Docker decides to leverage ACR container build capabilities. Are we willing to continuously monitor capabilities for all backends and adjust error handling heuristics accordingly?

Answers to questions above might depend on how many commands/errors receive special treatment. If it is only a handful, perhaps these issues are of minor concern.

@bwateratmsft @BigMorty @philliphoff @dbreshears please share your thoughts

**Comment by bwateratmsft** [comment]
I agree with Karol. I think we take these issues piecemeal; if we see a lot of people hitting any particular issue, we'll take steps to mitigate that--I'd like to avoid the premature "optimization" of trying to prevent every possible scenario where a user sees an error message.

**Comment by dbreshears** [comment]
Let's log a bug on the Docker CLI

**Comment by BigMorty** [comment]
I created   ##https://github.com/docker/compose-cli/issues/1096

**Comment by bwateratmsft** [comment]
IMO we can probably close this. Docker has improved the error messages: https://github.com/docker/compose-cli/issues/1096

**Comment by BigMorty** [comment]
Agreed
