### ISSUE TITLE
The notification is confused after pruning the volume

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2583]
**OS:** Windows 10
**Build Version:** 20201223.2

**Repro Steps:**
1. Create a volume using command "docker volume create my-vol".
2. Click the prune button to prune volume.
3. Check the notification message after pruning the volume.

**Expect:**
The notification is clear, such as "Removed **1** volumes and reclaimed **XX MB** of space".

**Actual:**
The notification is confused.
![image](https://user-images.githubusercontent.com/45614674/103076685-44ed8980-4609-11eb-95c6-7db75e05a408.png)

**More Info:**
The volume is removed successfully after pruning.

**Comment by bwateratmsft** [comment]
Should be an easy fix, turn the null into 0.

**Comment by v-ruizh** [comment]
The notification is also confused after pruning several volumes. The notification is always "Removed **0** volumes and reclaimed **0** MB of space" even though removed more than 1 volume.

**Comment by bwateratmsft** [comment]
Turns out this is an external issue: https://github.com/docker/for-mac/issues/5011

The Docker engine API is returning an object completely unrelated to what is expected. Dockerode simply returns the object without trying to coerce it into any shape. When this API bug is fixed, it should automatically start working correctly.
