### ISSUE TITLE
Cannot attach to a container if a container with the same name is already opened using an other docker context

### ISSUE THREAD

**Issue by remss** [microsoft/vscode-docker#2589]
## Context

Local Workstation:
- VSCode 1.52.1
- VSCode Docker extension 1.9.0
- VSCode Remote Development 0.2.0
- Windows 10
- Docker CLI 19.03.12, with 2 contexts "remoteActx" and "remoteBctx"

Remote servers (remoteA and remoteB)
- Ubuntu 18.04
- Docker 19.03.13

## Steps to reproduce

* From each remote servers

	* Start a container using the same container name

          remoteA# docker run -ti --name test-ubuntu ubuntu:20.04 bash
          remoteB# docker run -ti --name test-ubuntu ubuntu:20.04 bash
	
* From the Local Workstation

	* Open VSCode, in Docker panel, use context remoteActx
	* Right click on running container "test-ubuntu" > "Attach Visual Studio Code"
	* Once the second VSCode window is opened and attached to remoteA, go to File > Open Folder and select "/var/www"
	* Back to the first VSCode window, in Docker panel, use context remoteBctx
	* Right click on running container "test-ubuntu" > "Attach Visual Studio Code"
	* 💥 The second VSCode window is focused (attached to remoteA) instead of opening a third VSCode window attached to remoteB.
	
## Additionnal infos

If I use different containers names on each remote, like "test-ubuntuA" and "test-ubuntuB", then it works as expected, the second Attach opens a third VSCode window.

**Comment by bwateratmsft** [comment]
This would be an issue in either the Remote - Containers extension or in VS Code itself. I'm guessing that the command line that would be used to start VSCode decides whether to focus an existing window, or open a new one. Since the command line itself doesn't include any context information, VSCode probably thinks it means the same thing, since it is identical to the other one--and thus, focuses the same window rather than open a new one.

I would start by opening an issue in the [issues repo for the Remote - Containers extension](https://github.com/microsoft/vscode-remote-release/issues), but they may move it into the VSCode repo depending on where it belongs.

**Comment by remss** [comment]
Ok thanks! See https://github.com/microsoft/vscode-remote-release/issues/4266
