### ISSUE TITLE
Look into tree tooltip API

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker#2592]
There's a newish tree tooltip API supporting markdown that looks interesting: https://code.visualstudio.com/updates/v1_52#_markdown-tree-tooltip-api

We should see if there are some interesting ways we could use this API.

**Comment by bwateratmsft** [comment]
Some ideas for containers:

- Container name, ID
- Container status
- Image name, ID
- Ports
- Networks
- Volumes

**Comment by ucheNkadiCode** [comment]
## Ideas for the Panes - not in order of importance. I looked through each of the inspect documents and picked out which attributes I thought might be important

### Containers:
(ones not mentioned)
- Labels (especially if group by label becomes a thing)

### Images:
- Image Name, ID
- List of associated containers (or is there only ever 1?)
- Image size (converted to MB or GB)
- Labels
- Latest Tag Time

### Registries:
(when hovering over registry image):
- Full registry path
- Associated App Services (if applicable)
- Associated Container Instances (if applicable)
- Possibly the other fields for Images (listed above)

### Networks:
- Date/Time Created, 
- Labels
- Containers associated with Network
- Options that may be important such as docker.network.bridge.name (need help determining this)
- Config? Would subnet and gateway be important to know? eg 172.XX.X.X

### Volumes:
- Date/Time Created
- Labels
- Options that may be important
- Where this volume lives on the host (mountpoint I believe)
- List of containers accessing this volume

### Contexts:
Personally, I didn't see any information that looked super important, but if it is...
- Endpoints
  - docker.host
  - kubernetes.host

**Comment by karolz-ms** [comment]
For containers we should look into exposing ports/port mappings and volumes used by the container (and what path are those mounted at)

**Comment by bwateratmsft** [comment]
Depends on https://github.com/microsoft/vscode-azuretools/pull/835.

**Comment by ucheNkadiCode** [comment]
Example of Containers ToolTip:
Name: beautiful_galois (5460373f9bec)
Status: Running (maybe a green play button icon)
Image Name: pythonsamplevscodedjangotutorial:latest (4e7e6992dac5)
Ports: `0.0.0.0:8000->8000/tcp` 
Environment: (table format required)
| Key | Value | Source|
| ------------- |-------------| -----|
| `SA_USERNAME` | sa | Image |
|`SA_PASSWORD` |Admin123|Image|
|`ACCEPT_EULA` | Y | Runtime |

Volumes: (table format required)
| Type | Name/Source | Destination | 
| ------------- |-------------| ------------ |
| Named | pythonVolume | |
| Bind Mount | [/Users/vsCode/project/bin](fakelink) | /var/app |

(The source folder for bind mounts should be openable with a click)
Networks: bridge <-- if one network. Otherwise,
| Name |
|--|
| default |
| bridge | 

Labels: (probably will not be displayed due to size) - Could we just show the first 5?
| Key | Value | Source|
| ------------- |-------------| -----|
| App_Name | pythonDjango | Image |
| Permission_Level | Admin | Runtime |

**Comment by stuartthomson** [comment]
I wonder if it would be possible to make this customisable via a template, similar to the `attach` and `logs` commands? I have some custom container labels that I always want to check and I tend just to inspect via the extension and ctrl+f the output - having this in the tooltip would be brilliant.

I'd be up for prototyping something like that if it was possible.

**Comment by bwateratmsft** [comment]
We're starting some work on that right now, with Handlebars templates being used. I'd certainly be interested in what you want to see in the tooltips; it's pretty likely things we'd all want.

In the interest of performance, I have hardcoded the Handlebars template strings, but it certainly would be possible to make them customizable somehow (files or settings or something).

**Comment by stuartthomson** [comment]
I'd be interested in everything that the current tree item knows honestly. The only thing that seems potentially tricky is the case with specific labels. How should the template render if that label isn't present? Would be cool if the template could have conditions on it, if a certain label is present render differently than if it's absent.

**Comment by bwateratmsft** [comment]
We definitely can't show everything, but we're hoping in general to show a curated subset of what you'd see as an inspection result. Also, nice and neat and markdown-y.

**Comment by stuartthomson** [comment]
Apologies, I only meant that if users can define templates I'd be interested in having access of all the tree item's data.

Also I was making the assumption that this would be done without another API call, so it could only be a subset of the inspect data anyway.

**Comment by bwateratmsft** [comment]
Ah, I understand what you mean. It's not set in stone yet but my thought was to do an inspect, and feed the entire inspection result to Handlebars as the context. Should open up a lot of possibilities.

**Comment by stuartthomson** [comment]
Having the entire inspection contents available to the template could definitely open up some exciting possibilities. I'm interested in what the performance is like from that, having to inspect the container then render into a template seems potentially slow.

**Comment by bwateratmsft** [comment]
Same, especially in remote scenarios it could be slow. The first tooltip is also gonna be a bit extra slow; we lazy-load a lot of larger dependencies, Handlebars included. I'll definitely come up with some perf data when I open my PR.

**Comment by ucheNkadiCode** [comment]
**Suggestions:**

- Show all of the sections regardless of emptiness - "No ports are exposed" "There are no volumes"
- Named Volume: instead of Volume
- Docker Host Endpoint in contexts
- Add associated containers in Images
- Adding None for any default sections that have no Ports, Associated Containers etc

**Comment by bwateratmsft** [comment]
This is now released in Docker extension version 1.10.0.
