### ISSUE TITLE
An error "Unknown parameter structure byName..." occurs in the "Dockerfile Language Server" output panel

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2601]
**OS:** Windows 10
**Build Version:** 20210106.8

**Repro Steps:**
1. Create a .NET Core Console project.
2. Add Docker files to it.
3. Open Dockerfile and check the "Dockerfile Language Server" output panel.

**Expect:**
There is no error in the "Dockerfile Language Server" output panel.

**Actual:**
An error "Unknown parameter structure byName..." occurs in the "Dockerfile Language Server" output panel.

_(node:13968) UnhandledPromiseRejectionWarning: Error: Unknown parameter structure byName
    at computeSingleParam (c:\Users\AzureTest\.vscode-insiders\extensions\ms-azuretools.vscode-docker-1.9.5-alpha\dist\dockerfile-language-server-nodejs\lib\server.js:1:211247)
    at computeMessageParams (c:\Users\AzureTest\.vscode-insiders\extensions\ms-azuretools.vscode-docker-1.9.5-alpha\dist\dockerfile-language-server-nodejs\lib\server.js:1:211410)
    at Object.sendNotification (c:\Users\AzureTest\.vscode-insiders\extensions\ms-azuretools.vscode-docker-1.9.5-alpha\dist\dockerfile-language-server-nodejs\lib\server.js:1:212089)
    at Object.sendDiagnostics (c:\Users\AzureTest\.vscode-insiders\extensions\ms-azuretools.vscode-docker-1.9.5-alpha\dist\dockerfile-language-server-nodejs\lib\server.js:1:292320)
    at c:\Users\AzureTest\.vscode-insiders\extensions\ms-azuretools.vscode-docker-1.9.5-alpha\dist\dockerfile-language-server-nodejs\lib\server.js:1:16962
(node:13968) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13968) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code._

**Comment by rcjsuen** [comment]
See https://github.com/microsoft/vscode-languageserver-node/pull/719.

**Comment by dbaeumer** [comment]
@rcjsuen can you reproduce this when running out of source? From looking at the code it very likely happens when the server sends the configuration request to the client. 

I also noticed that you have this line in your server code

```
import { FoldingRangeParams, SemanticTokenModifiers, SemanticTokenTypes, SemanticTokensParams } from "vscode-languageserver-protocol";
```

which might trick webpack into bundling the `vscode-languageserver-protocol` separately from the `vscode-languageserver/node` which might explain what you are seeing. The import is actually unnecessary. You should reach to these types using the `vscode-languageserver/node` import.

**Comment by rcjsuen** [comment]
> @rcjsuen can you reproduce this when running out of source?

@dbaeumer I haven't noticed this error before...but that is not evidence to imply it is a completely new bug or if it has been around for a while.

> I also noticed that you have this line in your server code
> 
> ```
> import { FoldingRangeParams, SemanticTokenModifiers, SemanticTokenTypes, SemanticTokensParams } from "vscode-languageserver-protocol";
> ```
> 
> which might trick webpack into bundling the `vscode-languageserver-protocol` separately from the `vscode-languageserver/node` which might explain what you are seeing. The import is actually unnecessary. You should reach to these types using the `vscode-languageserver/node` import.

@dbaeumer I've been meaning to clean that up in the past so this is as good a reason as any. I've published a new 0.2.2 release that includes this fix.

**Comment by dbaeumer** [comment]
@rcjsuen the `ParameterStructures` got introduced with the latest 6.0.0 release of vscode-jsonrpc. So if you haven't adopted a next release the error didn't exist before.

**Comment by rcjsuen** [comment]
> @rcjsuen the `ParameterStructures` got introduced with the latest 6.0.0 release of vscode-jsonrpc. So if you haven't adopted a next release the error didn't exist before.

@dbaeumer I was defining `^6.1.1` for `vscode-languageserver` before but two weeks ago I set it to `^7.0.0`.

**Comment by dbaeumer** [comment]
OK. Let me know if the error is solved for you now.

**Comment by bwateratmsft** [comment]
I just realized, this is keeping errors/warnings in the Dockerfile from showing up in the Problems window. This may be needed in 1.9.1.

**Comment by rcjsuen** [comment]
> OK. Let me know if the error is solved for you now.

@dbaeumer It doesn't look like it helped based on https://github.com/microsoft/vscode-docker/pull/2626#issuecomment-759580628. :(

**Comment by bwateratmsft** [comment]
The bug doesn't occur when I'm debugging the Docker extension--which is not webpacked--so whatever is happening probably only happens in the webpacked dockerfile language server.

**Comment by dbaeumer** [comment]
How do I webpack the extension?

**Comment by dbaeumer** [comment]
OK. I looked into it and I think it comes from the fact that the `dockerfile-language-service` bundles another version of the vscode-jsonrpc library. I see why you need this (e.g. `SemanticTokens`) but could you try to copy the interface and see if it works then. What we needs to understand as well is why webpack bundles things weirdly.

**Comment by bwateratmsft** [comment]
There should be an NPM script, `npm run package`, which will webpack and produce a VSIX.

Also, I think you two probably knew this already--you're definitely way ahead of me--but it seems like in the webpacked version of dockerfile-language-server-node, it is both doing a `require("vscode-jsonrpc")`, and webpacking the code within it. I see one part of the webpacked code that looks like it's passing down an object from the `require` and then the code for the switch statement is expecting the singleton from what is webpacked in. So, even though they are "single"tons--they are two singletons.

**Comment by dbaeumer** [comment]
@bwateratmsft thanks I ran `npm run webpack-prod`. Hope it produces the same result :-)

Where exactly do you see this in the webpacked version?

**Comment by dbaeumer** [comment]
Looking at the webpacked code there is one class definition for `ParameterStructures`. The one that references it through the require I think should get it from the export of the definition. 

One question: can you reproduce this in the dev version of the webpack. If so can you give me instructions on how to reproduce. I would like to understand why this is happening.

**Comment by bwateratmsft** [comment]
So I'm looking at the 0.22.0 version of the language server; here's what I'm seeing (bear with me, I don't know a ton about webpack, and needless to say webpacked code is very hard to read)--

Starting from the deepest layer in the call stack:
The error originates at 1:211255:
```javascript
throw new Error("Unknown parameter structure "+e.toString())
```

It's comparing to `a.ParameterStructures.byName` in that `switch` statement (and deciding they are _not_ the same object):
```javascript
case a.ParameterStructures.byName:
```

I found the definition of that `a` up a little bit:
```javascript
a=n(226)
```

Looking at `n(226)`, it appears to be the code of `vscode-jsonrpc`, messages.ts in particular, packed:
```javascript
226:function(e,t,n):
// ...
class ParameterStructures // defined here
```

So that's one of the copies of `ParameterStructures.byName`.

Now, starting from higher in the call stack:
```javascript
sendDiagnostics:e=>s.sendNotification(r.PublishDiagnosticsNotification.type,e)
```

That `r` is `n(32)`:
```javascript
const r=n(32)
```

`n(32)` is a require of `vscode-languageserver-protocol`:
```javascript
32:function(e,t){e.exports=require("vscode-languageserver-protocol")}
```

I also noticed an `n(121)`:
```javascript
121:function(e,t){e.exports=require("vscode-jsonrpc")}
```

Referred to near by `ProtocolNotificationType`, which is what that `PublishDiagnosticsNotification.type` is.

**Comment by dbaeumer** [comment]
Very nice analysis. This is exactly the problem since it ends up having to of those. You can also see that in the VSIX since it ships the `vscode-jsonrpc` bundled and as a separate node module

<img width="352" alt="capture" src="https://user-images.githubusercontent.com/1931590/104501747-6d511e00-55e0-11eb-9c95-3126246bb4d4.png">

**Comment by bwateratmsft** [comment]
I tried out reproducing this with webpack-dev (by changing the `preLaunchTask` for `"Launch Extension (webpack)"` to `npm: webpack-dev`, in launch.json.

Also, I wish I'd done that webpack-dev before, it's so much more readable.

I don't honestly know enough about webpack to know why it is doing this, do you know?

**Comment by dbaeumer** [comment]
Actually I am not a webpack expert (nor a fan :-)). What I noticed when running the `npm run webpack-dev` is that it prints the following

```
Excluded node modules (external node modules plus dependencies) [
  'balanced-match',
  'brace-expansion',
  'concat-map',
  'is-wsl',
  'lru-cache',
  'minimatch',
  'opn',
  'semver',
  'vscode-jsonrpc',
  'vscode-languageclient',
  'vscode-languageserver-protocol',
  'vscode-languageserver-types',
  'yallist'
]
```

I looked into the config file but the `externalNodeModules` array is empty. But what I noticed is that it get some webpack config from `vscode-azureextensiondev`. May be it is excluded there.

**Comment by bwateratmsft** [comment]
Looks like it. I see code/comments about getting the closure of dependencies of `vscode-languageclient`. That code is pretty old though so we've definitely been doing this a while--was there a change in `vscode-jsonrpc` 6.0.0 that would have resulted in this?

**Comment by dbaeumer** [comment]
Yes, `ParameterStructures` are introduced in `vscode-jsonrpc` version 6.0.0. So they didn't exist before. But having two version of jsonrpc being used might result in other problems as well unless they are used completely separately from each other. 

The problem is that due to how send request is implemented the parameter structure can't simply be a enum. I would not be able to decide a string parameter with `byName` from a `ParameterStructure.byName`. Why do you exclude the `vscode-languageclient`. I always fully bundle it as well as `vscode-langaugeserver`. I made both webpack friendly.

**Comment by bwateratmsft** [comment]
@StephenWeatherford set this up a couple years back so I don't know why. Here's the only hint in source:
```typescript
const defaultExternalNodeModules: string[] = [
    // Electron fork depends on file at location of original source
    'vscode-languageclient',
    //...
];
```

**Comment by dbaeumer** [comment]
I would say that this is not necessary anymore since I for example bundle `vscode-languageclient` into the ESLint extension using webpack without any problems.

**Comment by bwateratmsft** [comment]
I'd be inclined to agree. I just tried removing that line and bundling up the VSIX, and I haven't encountered any obvious issues yet..._and_ it seems to fix this bug (#2601).

**Comment by dbaeumer** [comment]
I just tested the same and came to the same conclusion.

**Comment by rcjsuen** [comment]
Thank you @bwateratmsft and @dbaeumer for the detective work!

**Comment by bwateratmsft** [comment]
Hey, I'll never pass up an opportunity to complain about webpack. :rofl:
