### ISSUE TITLE
An error "No containers are available to restart" occurs when restarting a stopped container in the ACI context environment

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2602]
**OS:** Windows 10
**Build Version:** 20210106.8

**Repro Steps:**
1. Right click one ACR image -> Select "Deploy Image to Azure Container Instances..." and create one new ACI.
2. Stop the container in the ACI context environment.
3. F1 -> Docker Container: Restart.

**Expect:**
Wizard to the container option.

**Actual:**
An error "No containers are available to restart" occurs.
![image](https://user-images.githubusercontent.com/45614674/103872457-67070180-5109-11eb-8726-bd93d18c3794.png)

**More Info:**
This issue does not reproduce in default context environment.

**Comment by bwateratmsft** [comment]
Found the root cause. ACI added some new state strings, "Node Pending" (starting), and "Node Stopped" (stopped). Both should be treated as stopped states.

**Comment by bwateratmsft** [comment]
I've found that the container does not always transition to "Node Stopped". Eventually it always ends up at "Terminated", but sometimes it seems to skip "Node Stopped". So far I have not seen it skip "Node Pending", but it's probably safe to assume that is a possibility.

**Comment by bwateratmsft** [comment]
There's one remaining issue. For non-ACI contexts, we allow the user to run the Restart command from the palette, and show stopped containers (however, in context menu, only the Start command is shown). However, for ACI contexts, this behavior is not mirrored. I think the fix is just to allow the "terminated" state in the multi-select regex for restartContainer.
