### ISSUE TITLE
why i am getting this error : Error Message: Azure App service currently only supports running images from Azure Container Registries with admin enabled

### ISSUE THREAD

**Issue by mainul-alam** [microsoft/vscode-docker#2623]
Does this occur consistently? 
Repro steps:

1.
2.

Action: vscode-docker.registries.deployImageToAzure
Error type: Error
Error Message: Azure App service currently only supports running images from Azure Container Registries with admin enabled

Version: 1.9.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
getNewSiteConfig extension.bundle.js:924:171843
processTicksAndRejections task_queues.js:94:5
async deployImageToAzure extension.bundle.js:924:171306
```

</details>

**Comment by bwateratmsft** [comment]
@mainul-alam In order to deploy to App Service from an ACR, currently it is required to enable admin mode on the ACR. This allows a simple username and password to be used to pull the image. There is some future work to enable using a managed service identity (#1685), but up until recently it was not possible because App Service itself did not support using MSI to pull an image.

You can read more on how to enable admin on your ACR here: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication#admin-account
