### ISSUE TITLE
The Docker view state is not changed after installing and starting Docker Desktop

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2629]
**OS:** Win 10
**Build Version:** 20210111.1

**Repro Steps:**
1. Make sure Docker Desktop is not installed on the machine.
2. Open the Docker view, it will show as below.
![image](https://user-images.githubusercontent.com/45614674/104554040-958b5c00-5676-11eb-8440-f775947fc26e.png)
3. A notification will be shown, click "Install" button to install Docker Desktop.
4. Start the Docker Desktop and check the Docker view.

**Expect:**
The Docker view state is changed to "No items found".
![image](https://user-images.githubusercontent.com/45614674/104553918-6b399e80-5676-11eb-8b17-ee24be42b346.png)

**Actual:**
The Docker view state is still "Failed to connect. Is Docker installed?".
![image](https://user-images.githubusercontent.com/45614674/104554144-c7042780-5676-11eb-8955-2a8e3171239d.png)

**More Info:**
1. Refresh can't fix this issue.
2. Restart VS Code can fix this issue.

**Comment by bwateratmsft** [comment]
Related to #2474

**Comment by ucheNkadiCode** [comment]
I assume closing VS Code and reopening would also fix this issue in the case that Docker wasn't installed? 

Also, I am still in favor of some messaging around telling the user to click refresh after they install Docker. I want to continue the habit of telling the users exactly how they can solve their issue even if it may be obvious to most. 

This is our **most** common error in VS Code, so anything that can lessen the impact/annoyance once the error happens, is worth it.

Suggested wording: "Failed to connect. Make sure Docker is installed and refresh this window" (or "the window"/pane)

**Comment by bwateratmsft** [comment]
Yes, restarting would fix it. Also, I disagree--refreshing is absolutely a natural step for users to take. They just installed Docker so they know something has changed behind the scenes--that isn't something that happens automatically--the obvious next step is to try refreshing. CTI tried that first:

> **More Info:**
>
> 1. Refresh can't fix this issue.

Rather than change the messaging, I'd prefer to just fix the issue so it automatically starts working once Docker is installed, but it definitely isn't urgent enough to try to force into 1.10.0.

**Comment by dbreshears** [comment]
Closing since there are workarounds and other fixes have mitigated the impact such as any refresh action.
