### ISSUE TITLE
Fail to compose down the container when the project is in the subdirectory

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2633]
**OS:** All
**Build Version:** 20210114.1

**Repro Steps:**

1. Create an Express App project and open it in VS Code -> Command Palette -> Add Docker files to workspace -> Node.js -> Enter port -> Close the workspace folder.
2. Create a new folder -> Move the Express App project into the new folder.
3. Right click the docker-compose.yml file -> Select "Compose Up".
4. Navigate to "Containers" view -> Right click the compose group -> Select "Compose Down".
5. Check whether compose down the container successfully.

**Expect:**
Compose down the container successfully without any error.

**Actual:**
Fail to compose down the container with an error.
![image](https://user-images.githubusercontent.com/62053665/104708388-9ac0d780-5758-11eb-95f7-88c214e2aa10.png)

**More Info:**
This issue also reproduces for "Compose Logs/Compose Restart" commands.

**Comment by bwateratmsft** [comment]
Good find! The compose down / etc. commands are supposed to be using absolute paths so I'll have to look into why this is happening.

**Comment by bwateratmsft** [comment]
What's happening is basically contradictory information from compose. They use the paths for the config files, relative to cwd of the `docker-compose up` command execution; but they stamp the working directory as the folder containing the config files.

For example:
Compose up "NetNoSsl\docker-compose.yml" from directory: D:\Sandbox
Working dir label: D:\Sandbox\NetNoSsl
Config files label: NetNoSsl\docker-compose.yml

I don't think that this is desirable behavior; IMO the config files should always be relative to the working dir--so either working dir should be "D:\Sandbox" above, or config files should be just "docker-compose.yml".

In terms of solving the problem--I think I'll just take the filenames only from the config files label, i.e. "docker-compose.yml" instead of "NetNoSsl\docker-compose.yml". Having a working dir that doesn't directly contain the config files is probably unusual.
