### ISSUE TITLE
Adding Docker files for .NET Core does not automatically generate .NET debug assets

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#2669]
Context: https://github.com/OmniSharp/omnisharp-vscode/issues/3403
Merged PR: https://github.com/OmniSharp/omnisharp-vscode/pull/4241

When a user adds .NET Core Dockerfiles to Workspace, in order to F5 a project successfully, they need to add the .NET Core build/debug assets before adding Docker debug assets (either via "Add Docker Files..." or "Initialize for debugging", due to OmniSharp/omnisharp-vscode#3403 (overwriting the existing launch and task files) which has now been fixed.

Could we create functionality that automatically runs this command in the background for a smoother F5 experience?

**Comment by bwateratmsft** [comment]
🤦‍♂️ I only just realized, the change in the C# extension isn't released just yet. Naturally we need to wait until the fix is (widely-enough) available before we proceed--probably will need to be moved to 1.11.0 but I'll leave it in 1.10.0 for now.

@ucheNkadiCode, can you follow up with the C# folks and see when they expect to release next?

**Comment by bwateratmsft** [comment]
Moving to 1.11.0 so we can give time for users to upgrade to the needed C# extension version.

**Comment by bwateratmsft** [comment]
This is now released in Docker extension version 1.11.0.
