### ISSUE TITLE
Running extension in UI mode under Remote Development

### ISSUE THREAD

**Issue by davecardwell** [microsoft/vscode-docker#2673]
I’m running my “remote” development using Docker Compose on Docker Desktop for Mac.

My dev container needs to be running node so I can use its tsserver as my workspace TypeScript version, and so I can easily run scripts, install dependencies etc. without having to hop between the various application containers.

Since I am installing third-party code from npm—and there have been numerous security incidents with malicious packages—I would prefer to use my dev container as a non-root user, and to avoid any docker-in-docker scenarios where the host’s docker.sock is exposed in the remote container.

I found I can use the `remote.extensionKind` setting to force `ms-azuretools.vscode-docker` into `ui` mode so it uses the host’s docker.sock, however I cannot use various commands like “View Logs” or “Attach Shell” without getting the error message:

> This operation is not supported because the Docker extension is currently running outside of your container.

Is this missing functionality something that could be made to work when running in UI mode under Remote Development, or is it fundamentally unavailable due to the way extensions are implemented?

**Comment by bwateratmsft** [comment]
I believe it's one of those fundamental it-won't-work things, unfortunately. AFAIK VSCode's terminals are _always_ in the remote target, never on the host. I looked through the API and didn't see anything obvious indicating it's possible to do otherwise. So in this scenario, the terminal shell would always be in the dev container. This means we couldn't run `docker logs` / `docker attach` / etc. on the host, while also having that visible in the terminal window (we _can_ run it in the background using Node's `child_process` module, but the user couldn't see it so that's not useful).

It's not elegant but one option would be to use two VSCode windows--one w/ remoting to the dev container, the other just on the host. Another would be to map the host's Docker socket but as you point out that carries security risk.

**Comment by davecardwell** [comment]
Thanks, @bwateratmsft—I appreciate the swift response. I’ll see how working with docker in a separate VSCode window or just Terminal.app goes.
