### ISSUE TITLE
Containers not being removed after debugging when using hotkeys to restart debugging

### ISSUE THREAD

**Issue by Technoguyfication** [microsoft/vscode-docker#2676]
**Summary:**

When using `removeContainerAfterDebug` in my `launch.json`, containers aren't being removed after debugging when using the Ctrl+Shift+F5 hotkey to restart debugging. They're removed just fine when clicking the restart button, just not when using the hotkey.

**How to reproduce:**

1. Set up docker container debugging with vscode (I'm using node.js)
2. Set `removeContainerAfterDebug` to `true` in `launch.json` in the launch configuration object
3. Start a container and begin debugging
4. Restart debugging using the hotkey (Ctrl+Shift+F5)
5. The previous container is not removed as it should be

**Expected behavior:**

The container should be removed after debugging, the same as when you click the restart debugging button with the mouse.

**Comment by bwateratmsft** [comment]
Could be related to how VSCode handles tasks; we'll have to investigate.

**Comment by bwateratmsft** [comment]
I've investigated and found that this issue is external: https://github.com/microsoft/vscode/issues/117984

When restarting debugging via the UI button, `vscode.debug.onDidTerminateDebugSession` does get called. However, when restarting with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F5</kbd>, it does _not_ get called, and we do not shut down the container.

**Comment by bwateratmsft** [comment]
Reopening. The root problem is actually in this extension; we misunderstood how the restart flow works.

**Comment by bwateratmsft** [comment]
This fix is now released with Docker extension version 1.12.0.
