### ISSUE TITLE
Selecting a container to start - please change UI

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-docker#2684]
Why does the activity bar and the command palette show the SHA of containers? It would be more helpful to show the container tag first, then the image the container is from. The SHA is just about meaningless. 

![image](https://user-images.githubusercontent.com/41597107/106284587-4279e300-61f8-11eb-8476-bd5582522346.png)

@burkeholland

**Comment by bwateratmsft** [comment]
@diberry the views are highly customizable (you can customize label, description, grouping, sorting from the gear icon on that title bar). In this case, it's showing the SHA hash because the image it's using is untagged. Normally it shows the image name by default.

**Comment by diberry** [comment]
I configed but the individual containers didn't change. 
![image](https://user-images.githubusercontent.com/41597107/106293704-29c2fa80-6203-11eb-9395-d8a17c824c5b.png)

**Comment by bwateratmsft** [comment]
Do you know what image these containers are from? If you've pulled a new version of that image, then the old version is technically no longer tagged--which would lead to what you're seeing. Otherwise, if the image has been removed, that would also have the same effect.

**Comment by diberry** [comment]
Do containers go into "Individual containers" if they are not tagged or orphaned from their parent image?

**Comment by bwateratmsft** [comment]
A couple releases back we changed the default grouping for containers from "none" to compose project, since a lot of people were asking for that not realizing we had that feature already! So in your above screenshot, the `CONTAINERREGISTRY...` container is part of the `js-e2e-express-react-mongodb` compose project. The rest of the containers are not part of any compose project, so they fall under "Individual Containers", because our UI framework basically constrains us to grouping them under _something_.
