### ISSUE TITLE
Gitlab registry oauth (unknown client)

### ISSUE THREAD

**Issue by rundx** [microsoft/vscode-docker#2688]
Incase no one noticed, Gitlab registry login is not working anymore
I think they require HTTP Basic authentication using client_id and client_secret along with this request to get the oauth token https://docs.gitlab.com/ee/api/oauth2.html

    POST /oauth/token HTTP/1.1
    host: gitlab.com
    content-type: application/x-www-form-urlencoded
    accept: application/json
    Content-Length: 56
    Connection: close
    grant_type=password&username=xxxx&password=xxxxxxx

    {
      "error":"invalid_client",
      "error_description":
      "Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method."
    }

**Comment by bwateratmsft** [comment]
Looks like you're correct. We'll have to investigate.

**Comment by bwateratmsft** [comment]
Looks like OAuth is not a practical solution anymore since it requires users to register an application and provide the app ID and secret in addition to the username and password. Personal access token auth is probably the only reasonable replacement. I'm going to dupe this to #1968, and flag that one for re-triage so we can prioritize appropriately.

**Comment by bwateratmsft** [comment]
This fix is now released in Docker extension version 1.10.0.
