### ISSUE TITLE
Fail to restart the running container which generated by debugging

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2705]
**OS:** All
**Build Version:** 20210204.1

**Repro Steps:**

1. Create an Express App project and open it in VS Code -> Command Palette -> Add Docker files to workspace -> Node.js -> Enter port.
2. Debug -> Navigate to the "CONTAINERS" node -> Right click the running container -> Select "Restart".
3. Check whether restart the running container successfully.

**Expect:**
Restart the running container successfully.

**Actual:**
Fail to restart the running container with an error.
![Screen Shot 2021-02-08 at 3 08 56 PM](https://user-images.githubusercontent.com/62053665/107188086-075e8780-6a22-11eb-9347-6bfc22994fd3.png)

**More Info:**

1. This issue also reproduces for Python project.
2. There is an error for .NET Core project.
    ![Screen Shot 2021-02-08 at 5 23 38 PM](https://user-images.githubusercontent.com/62053665/107201328-cbccb900-6a33-11eb-9a1d-6e353052a94e.png)

**Comment by bwateratmsft** [comment]
This is by design. The container gets removed once debugging stops; when the container is stopped by doing "Restart Container", it causes debugging to stop and the container gets removed. By the time the system tries to restart the container, the code to remove after debugging has already marked it for removal.

**Comment by v-mengwe** [comment]
@bwateratmsft Thanks for you sharing. It would be better to disable the "Restart" for this running container if this is by design.
