### ISSUE TITLE
dockerRun-property "portsPublishAll" ignored for Python tasks

### ISSUE THREAD

**Issue by Rumpel22** [microsoft/vscode-docker#2708]
The executed command for a `docker-run` task for Python contains the argument `-P` (Publish all exposed ports to the host interfaces), regardless if the dockerRun-property `portsPublishAll` in the tasks.json is set to true, false or left undefined. If you use the `network`-property to connect to a specific, long-running container, the `docker run` command fails with the message "conflicting options".

The reason may be a logic error in src\tasks\python\PythonTaskHelper.ts, 108:
```
runOptions.portsPublishAll = runOptions.portsPublishAll || true;
```
This code sets the `runOptions.portsPublishAll` always to `true`. I guess, this code should set the property to true only if it was undefined.

**Comment by bwateratmsft** [comment]
Thanks for investigating! You're spot on. That should be `??` instead of `||`.

**Comment by Rumpel22** [comment]
More general: The handling of the property `portsPublishAll` is distributed over several files and inconsistent:
* For .NET core, the logic is completely in the common code when the command line is constructed, taking into account the `ports`-property if `portsPublishAll` is undefined (src\tasks\DockerRunTaskProvider.ts, 86)
* For Node, there is some code (src\tasks\node\NodeTaskHelper.ts, 155) that does some additional checks on the `ports`-property, which may set the property to true if it was undefined before. 
* For Python, (if the code would work as expected and set the property to true if it was undefined) the property is either true or false and the common code handling the `ports`-property is overruled.

**Comment by bwateratmsft** [comment]
Good point. Python probably should be changed to match .NET (i.e. removing line 108 entirely), since neither .NET nor Python require a port open for debugging. For Node, I think the comment in the code describes the reasoning pretty well so I don't think that should get changed. Node is sort of a special case because it _does_ require an open port to debug, _and_ we expect that port to be constant, while for all three the port for the web server is published with `-P` (by default) to avoid port conflicts.

**Comment by Rumpel22** [comment]
That sounds good to me 👍
