### ISSUE TITLE
"ARG requires exactly one argument" dockerfile-utils(4)

### ISSUE THREAD

**Issue by oberfoerster** [microsoft/vscode-docker#2760]
in Dockerfile:
```
...
ARG BUILD_ARG1=23 \
    BUILD_ARG2=42
...
```
renders following warning from dockerfile-utils: "ARG requires exactly one argument" albeit everything building and working as expected.

ENV:
```
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:52:11.516Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 3.10.0-1160.11.1.el7.x86_64
```

**Comment by ucheNkadiCode** [comment]
@rcjsuen, do you think it's possible to make this dockerfile specification a little more flexible to include the user's `ARG` use case? The phrase "requires" makes it seem like their example won't run when it will.

**Comment by rcjsuen** [comment]
First of all, thank you to @oberfoerster for the bug report and my apologies for the late response. Been flooded with GitHub notifications and I haven't yet gotten around to pruning things down so this fell through the cracks. :(

So, with regards to `ARG` instructions taking in multiple arguments, that is a new feature introduced by https://github.com/moby/buildkit/pull/1692 in the [20.10 release](https://docs.docker.com/engine/release-notes/). I'll make the change in the language server so that this is no longer flagged as an error.

**Comment by bwateratmsft** [comment]
Cool, didn't know it was explicitly added as a new capability. Thanks!

**Comment by oberfoerster** [comment]
Thank You!
Seems, I'm an early adopter then ;)

**Comment by rcjsuen** [comment]
@oberfoerster I've opened #2866 to fix this.
