### ISSUE TITLE
Support Product Icon Themes

### ISSUE THREAD

**Issue by mirdaki** [microsoft/vscode-docker#2763]
It would be really awesome for the Docker extension so support the new-ish [Product Icon themes](https://vscode-eastus.azurewebsites.net/api/extension-guides/product-icon-theme). That would enable theme authors (such as [Fluent Icon](https://github.com/misolori/vscode-fluent-icons/issues/12)) to update the extension icon to match the rest of their theme.

**Comment by bwateratmsft** [comment]
This should now be possible due to #2678, with one exception--the Docker icon in the Activity Bar is not changeable; this icon is part of Docker's brand and we can't change it. Everything else uses ThemeIcons / codicons.

![image](https://user-images.githubusercontent.com/36966225/110649843-fcfded80-8187-11eb-803c-a7c4c9cea92c.png)

I tested it out using the first product icon theme in the search results and it looks to be working as expected:
![image](https://user-images.githubusercontent.com/36966225/110650084-36cef400-8188-11eb-8229-6832596b6dfc.png)

The underlined icons are different from the default theme. The others I assume were not replaced by that theme, but all are referenced the same way.
