### ISSUE TITLE
There is no error notification when selecting an application platform that does not match the project

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#2773]
**OS:** Win 10
**Build Version:** 20210311.1

**Repro Steps:**

1. Open a Python project with no dockerfile in VS Code -> Command Palette -> Docker Images: Build Image -> Click "Yes" when it asks if you want to add Docker files -> Select "Go" application platform.
2. Check whether pop up an error notification.

**Expect:**
Pop up an error notification when selecting an application platform that does not match, e.g.
![image](https://user-images.githubusercontent.com/62053665/110926377-47859280-835f-11eb-96ba-565f04530c0c.png)

**Actual:**
There is no error notification when selecting an application platform that does not match.

**Comment by bwateratmsft** [comment]
For now at least this is by-design. We want to avoid getting into the complexity of trying to determine what framework a project automatically (#1837), since this can get complex very quickly. For example, what if there is a .csproj and .py files? How would we tell between Flask and Django? etc.

As for the above errors, those happen because all .NET projects would have a .csproj (or .fsproj); similarly all Node projects would have a package.json. We gather some information used in scaffolding from those sources, so if they are missing we must throw an error.
