### ISSUE TITLE
[Codespaces] An error occurs in "Debug Console" panel when debugging a Django/Flask project

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2774]
**Environment:** GitHub Codespaces
**Build Version:** 20210311.1

**Repro Steps:**
1. Open a Django/Flask project in GitHub Codespaces environment.
2. Add Docker support for this project.
3. Debug it.
4. Check the logs in "Debug Console" panel.

**Expect:**
There is no error in "Debug Console" panel.

**Actual:**
An error occurs in "Debug Console" panel.
Logs for Django project:
![image](https://user-images.githubusercontent.com/45614674/110932298-41df7b00-8366-11eb-9a5e-3a996ea32a10.png)
Logs for Flask project:
![image](https://user-images.githubusercontent.com/45614674/110932334-4e63d380-8366-11eb-9590-56cbc862fce8.png)

**More Info:**
1. The web page can be opened successfully when debugging a Django/Flask project.
2. This issue does not reproduce on non-Codespaces environment.

**Comment by bwateratmsft** [comment]
Looks like this is a deliberate design from the Codespaces side. They do automatic port forwarding so that when you open something on localhost, it forwards to the Codespace. But, they don't inherently know if it's HTTPS or HTTP, so they try first with HTTPS and if that doesn't work, fall back to HTTP. That's what's happening here--there's an initial bad request (400), then a successful request to `/` (200):

![image](https://user-images.githubusercontent.com/36966225/110957627-c952cd00-8319-11eb-948d-a53cbe12849d.png)
