### ISSUE TITLE
"Property env is not allowed" in launch.json

### ISSUE THREAD

**Issue by akrymskiy** [microsoft/vscode-docker#2863]
Hello!

Seeing this "Property env is not allowed" warning in my launch JSON. The launch is working as expected and all the environment variables are passed in to the container. Docker extension v1.11.0

![image](https://user-images.githubusercontent.com/9452607/114246073-b30f4f80-995f-11eb-99f1-6aaa7712c498.png)

**Comment by bwateratmsft** [comment]
@akrymskiy this is by-design. The Docker extension's launch configuration, after resolving, becomes a Python launch configuration. It will pass-through (almost) all properties specified in the launch.json, which is why this works--we want to allow users to override (nearly) everything. However, since environment variables in launch.json only apply during debugging--and are not applied to the container itself--we usually recommend using the [`env` property](https://code.visualstudio.com/docs/containers/reference#_dockerrun-object-properties) in the `docker-run` task. Having them present only in debugging can cause confusion later on. There are valid use cases for using `env` in the launch.json file instead, but I think most scenarios are better served by using the task config.

If your scenario is best served by having these be debugging-only variables, that's fine; you can ignore the warning in this file. It will disappear from the problems window when you close the document.

**Comment by akrymskiy** [comment]
Thank you for the explanation! I am using the launch config to collect user input - that is passed to container in environment variables as job execution parameters. I will ignore the warning. Thanks!
