### ISSUE TITLE
Explorer views 'failed to connect' on remote context from WSL2

### ISSUE THREAD

**Issue by mfloresVicomtech** [microsoft/vscode-docker#2893]
Issue Type: <b>Bug</b>

- Set up Docker at Ubuntu 18.04 server and create a ssh key (ECDSA 521, also tested with RSA 2048) to connect to.
- Add key to ssh-agent, both on Windows and WSL2 (Ubuntu 20).
- Test that it succesfully connects.
- Create Docker context pointing to remote server.
- Change context to that remote:
   · VSCode on Windows correctly shows containers & images at explorer view.
   · VSCode on WSL shows a message "In order to use an SSH DOCKER_HOST, you must configure an ssh-agent." and explorer views says "Failed to connect. Is Docker running? Error: Request timed out."

If I enter "docker ps" at integrated terminal it correctly displays remote context containers.

Extension version: 1.12.1
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (1.94GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu/d/mflores/Documents/RAPID --crash-reporter-id c24afaa5-507b-48dd-96d1-8dc70abce61d|
|Screen Reader|no|
|VM|44%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|7.77GB (1.84GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30270858
pythonvspyt602:30291499
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30291488
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30276952
pythondataviewer:30285071
vscus158cf:30286554

```

</details>

**Comment by bwateratmsft** [comment]
I wasn't able to reproduce, but I suspect I might know what's going on. On Windows, the ssh-agent always listens on `\\.\pipe\openssh-ssh-agent`, so if the environment variable `SSH_AUTH_SOCK` is not defined, we assume it has that value. However, on Linux (and WSL), the value cannot be predicted like this--so that leaves no choice but to ensure that environment variable is set in the VSCode process.

@mfloresVicomtech I set up my `.bashrc` script to start the SSH agent _and_ take care of getting the environment variable set. With that setup, I am able to get everything to work in a VSCode WSL window. Here's the relevant section from my `.bashrc`:

```bash
if [ ! -e ~/mysock ]; then
  eval $(ssh-agent -s -a ~/mysock)
  ssh-add ~/.ssh/id_ecdsa
else
  echo SSH agent already running
  export SSH_AUTH_SOCK=~/mysock
fi
```

If the SSH agent is not running, it will start it, doing `eval $(ssh-agent ...)` in order to set the environment variables. I have it set to always use `~/mysock` as the socket so that I don't have to start a new ssh-agent process every time.

Can you try that approach and see if it works?

**Comment by mfloresVicomtech** [comment]
Hi @bwateratmsft, thank you so much for your answer. I almost forgot about this, but I've tested switching to remote context and now it works! The SSH_AUTH_SOCK was already set by `keychain` as I set that up in my .bashrc to share SSH keys from Windows to WSL:
```
# Sharing SSH keys from Windows
eval `keychain --eval --agents ssh *`
```

**Comment by bwateratmsft** [comment]
Awesome! That's a good idea. Glad it's working now!
