### ISSUE TITLE
unable to connect to docker hub

### ISSUE THREAD

**Issue by rajinder-yadav** [microsoft/vscode-docker#2925]
Does this occur consistently? 
Repro steps:

1. click on "Connect Registry"
2. select "Docker Hub"
2. provide username
3. provide password

I am able to login from the Docker Hub website.

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

![snap-47](https://user-images.githubusercontent.com/439226/117931482-3c060780-b2cd-11eb-85ab-284cce82425f.png)

Version: 1.12.1
OS: linux
OS Release: 5.12.0-2-default
Product: Visual Studio Code - Insiders
Product Version: 1.57.0-insider
Language: en

**Comment by karolz-ms** [comment]
Thanks, @rajinder-yadav We should investigate why the fix to https://github.com/microsoft/vscode-docker/issues/722 did not quite work.

**Comment by karolz-ms** [comment]
The original fix was in code that was subsequently removed when support for keytar was removed from VS Code. So this is, effectively, a new bug.

**Comment by karolz-ms** [comment]
So @rajinder-yadav thanks again for reporting; I am going to resolve this as external, because I am quite sure that when the underlying issue https://github.com/microsoft/vscode/issues/115248 is fixed, the Docker Hub connectivity will be restored. 

In the meantime installing `gnome-keyring` package should unblock things for you.
