### ISSUE TITLE
Docker Start Page pops up for non-docker related activations

### ISSUE THREAD

**Issue by ucheNkadiCode** [microsoft/vscode-docker#2953]
I think that although this error happens once per update... it happens EVERY UPDATE of VS Code. So I feel like this bug directly influences customer satisfaction and is important to tackle.

Repro video: https://channel9.msdn.com/Shows/VS-Code-Livestreams/1-56-Release-Party#time=03m47s

**Comment by karolz-ms** [comment]
The current implementation is that the page will pop up when we detect an updated version of the extension was activated. It should not happen just because of VS Code update, but it will happen for every VS Code copy that the user is using (the result of Docker extension upgrade check is not synced between machines).

As the extension can be activated for various reasons, including running *any* tasks (because it contributes a few custom tasks) it might seem that the start page pops up semi-randomly. IMO this happens too eagerly, and I propose that we show the start page for specific gestures instead of all extension activations. Here is what this gesture list might look like:

1. Show Docker view
2. Open a Dockerfile or Docker Compose file

The intention behind making the list so short and specific is to limit the (somewhat disruptive) showing of the start page to situations where the user already has decides to show a new piece of UI, and automatically showing another piece of UI will not be very jarring. 

@ucheNkadiCode @BigMorty @philliphoff @dbreshears  please share your thoughts

**Comment by philliphoff** [comment]
There are a couple of [asks](https://github.com/microsoft/vscode/issues/44711#issuecomment-369183434) in VS Code to allow extensions to have more insight into why they're being activated, which would allow us to better tailor our experience, but they've not gotten much traction.

I agree with @karolz-ms that we may need to switch to a model where we show the start page only for a select set of commands (or language service initializations, etc.).  If we think that set is large, we might find a way to make it fairly generic in our command registration, so that we can just turn *off* the few commands/providers that we don't want to induce the start page.

**Comment by karolz-ms** [comment]
We had a chat over email and this is the RC for the gestures that might trigger start page showing:

1. Show Docker Explorer (Docker view)
1. Open a Dockerfile or Docker Compose file
1. Add Docker / Docker Compose files to workspace
1. Install Docker
1. Container inspect
1. Image inspect

**Comment by karolz-ms** [comment]
Fixed in release 1.14
