### ISSUE TITLE
Support login to Docker Hub for account with MFA authentication

### ISSUE THREAD

**Issue by yooakim** [microsoft/vscode-docker#2975]
I have multi-factor authentication enabled on my Docker hub account. When I use the Docker Extension I would like to be able to login to the Docker Hub registry.

But when I use the extension to enter my username/password I get a 401. I am never asked for my MFA code. 

Am I doing something wrong or are accounts with MFA enabled not supported by the Docker Extension?

![image](https://user-images.githubusercontent.com/862546/119771816-8f2bad00-bebe-11eb-8644-06308538238e.png)

**Comment by karolz-ms** [comment]
@BigMorty could you confirm that Docker Hub MFA has been finalized?

**Comment by bwateratmsft** [comment]
Related to #2753.

**Comment by bwateratmsft** [comment]
Unfortunately, it looks like (at least right now), this is impossible for us. Was reading up on [here](https://docs.docker.com/docker-hub/2fa/#enable-two-factor-authentication), where toward the end of the doc it states:

> **Note:** Now that you have two-factor authentication enabled on your account, you must create at least one personal access token. Otherwise, you will be unable to log in to your account from the Docker CLI. See [Managing access tokens](https://docs.docker.com/docker-hub/access-tokens) for more information.

We sign in to Docker Hub in more-or-less the same way as the CLI--and use the same credentials--thus, in order to use MFA, a personal access token is the only possibility. We _do_ support PATs at this time in place of a password.

![image](https://user-images.githubusercontent.com/36966225/128555185-16b89a13-da8f-48fe-a98d-128b276e1fdc.png)

**Comment by BigMorty** [comment]
@bwateratmsft - I am confused, above you say it is impossible for us to support, but then you say we DO support PAT?

**Comment by bwateratmsft** [comment]
PAT (personal access token) is supported and has been for some time; what we cannot support is MFA.
