### ISSUE TITLE
Run docker task in interactive mode

### ISSUE THREAD

**Issue by Stadly** [microsoft/vscode-docker#2978]
`docker-run` tasks are always run in detached mode. I would like to specify which tasks should run in interactive mode, so I don't have to manually attach to the docker containers to see the output.

I have tried making `docker.commands.run` interactive, but it seems that tasks doesn't use those templates.

**Comment by karolz-ms** [comment]
Indeed, `docker-run` tasks do not use docker run command templates. 

Sounds like a good idea to add an option for running interactively; we'll take a look.

**Comment by bwateratmsft** [comment]
Turns out this probably isn't feasible. Our use of `CustomExecution` means there's not actually a TTY and interactive mode can't be used. Similar to #2451 the real solution is to not use `CustomExecution` but I don't know if we can actually work without it.

**Comment by bwateratmsft** [comment]
I'm going to remove the milestone to push this back into our triage bucket.

**Comment by karolz-ms** [comment]
😞

**Comment by bwateratmsft** [comment]
@Stadly unfortunately it doesn't look possible. There would need to be major engineering work to switch to `ShellExecution`, and there may be other reasons why that just isn't possible that we haven't thought of yet.

Your best bet in this case is to use a generic shell task instead of the `docker-run` task. Here's a simple example of one that's interactive:
```json
        {
            "label": "Interactive Docker Run Command",
            "type": "shell",
            "command": "docker run -it -p 1234:5678 alpine:latest"
        }
```

In context:
![image](https://user-images.githubusercontent.com/36966225/127380262-12f65b80-4a06-49d4-bedd-3715034a898a.png)

**Comment by Stadly** [comment]
Thanks for the update and suggestion, @bwateratmsft.
