### ISSUE TITLE
Please add more double-click/default actions

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vscode-docker#2980]
The `vscode-docker` extension is a great tool.

I would very much wish to have some more double-click, or <kbd>RETURN</kbd> key, default behaviour on selected items, like for switching context, or open files in a remote docker container by double-clicking on them.

https://user-images.githubusercontent.com/9283914/120103402-bea51880-c14f-11eb-89d4-d5814ab49aeb.mp4

**Comment by karolz-ms** [comment]
Makes sense, thanks for the suggestion @SetTrend What are the actions that would be most useful to you? Looks like opening/editing files in a container is one of them, any others?

**Comment by philliphoff** [comment]
We explicitly decided *not* have a default action when selecting container files because pulling them out of the container was an expensive (and less immediate) operation and it's easy to "accidentally" select a file.  Or, rather, we wanted to wait and see if customers really *wanted* that behavior before making it the default.  We had discussed whether it could be, say, an option to turn on/off.

One note is that VS Code only allows us to bind a command to an item when selected; it has no notion of a "double click" or "enter" action.  (If it had, we would definitely made that trigger opening the files.)

**Comment by karolz-ms** [comment]
@SetTrend thank you for submitting the issue--much appreciated. As @philliphoff mentions above, double-click is not an action that is supported by VS Code.

**Comment by SetTrend** [comment]
@karolz-ms , philliphoff

Paron my late reply. I had been busy on other issues for the last few days.

This is odd. There has been a discussion in the VS Code team to include double-click behaviour for the tree control:

https://github.com/microsoft/vscode/issues/85636#issuecomment-724844387

This should be implemented by now.

Would you want to revise this issue, given the new information?

I understand that transferring a file may be an expensive operation. Yet, double-clicking a file would be a strong expression of the user's expectations, I believe.

**Comment by karolz-ms** [comment]
Axel, thanks. We will reconsider

**Comment by philliphoff** [comment]
@SetTrend As I read it, the linked discussion doesn't refer to the ability for extensions to arbitrarily choose whether selection or double-click results in an opened document.  Instead, it refers to changes that allow extensions to (choose to) match the default VS Code behavior of whether selection or double-click results in the document being opened in its own tab or just replaces a previously-open document tab (and/or whether the document has text pre-selected, etc.).  The document is still *always* opened (which wasn't the behavior that we initially wanted).

Files are read from the container by way of a custom VS Code file system provider. Unfortunately, that API was not designed for streaming or in an otherwise cancellable manner. (VS Code simply provides a URI and expects the file to be returned as a complete in-memory buffer, with no mechanism to cancel the operation.)

**Comment by dbreshears** [comment]
Closing external issue.
