### ISSUE TITLE
The container node keeps loading for several seconds after the "Files" node expanded

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-docker#2986]
**OS:** Windows
**Build Version:** 20210603.1

**Repro Steps:**
1. Run a Redis container using this command "docker run -dt redis:latest".
2. Open the Docker Containers View in VS Code and expand this new started container node.
3. Expand "Files" node.
4. Check whether the container node stops loading after the "Files" node expanded. 

**Expect:**
The container node stop loading after the "Files" node expanded.

**Actual:**
The container node keeps loading for several seconds after the "Files" node expanded.
![test1](https://user-images.githubusercontent.com/45614674/120774114-8b4df980-c554-11eb-9b80-03182704a9bb.gif)

**Comment by philliphoff** [comment]
I can see the same thing on Windows.  My guess is that it's related to the updating of the "uptime" text of a container node.  I suspect that the uptime is now included in the node ID which is used by VS Code to determine whether a node has changed and needs its tree to refresh.  Since the uptime changes every second until get its to "about a minute", then it continually forces refreshes of the (file) sub-nodes.

I vaguely recall an issue with refresh when the "uptime" *wasn't* part of the node ID (i.e. the node text wouldn't get updated).  This maybe a secondary effect of the fix for that.

**Comment by dbreshears** [comment]
Related to #2983

**Comment by bwateratmsft** [comment]
I'm going to dupe this to #2983 since I'm pretty sure the underlying issue is the same (over-refreshing).
