### ISSUE TITLE
Show "Safari Can't Open the Page" in the browser after clicking "Open in Browser" for Python flask project with multiple ports

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-docker#3007]
**OS:** Mac
**Build Version:** 20210615.1

**Repro Steps:**

1. Open a Flask project in VS Code -> Add Dockerfile support including docker-compose files with port "`5000,5001`".
2. Debug -> Succeed to open a webpage in the browser.
3. Navigate the "CONTAINERS" node -> Right click the running container "flaskproject" -> Select "Open in Browser".
4. Check whether the webpage shows well  in the browser.

**Expect:**
The webpage shows well in the browser.

**Actual:**
Show "Safari Can't Open the Page" in the browser.
![Screen Shot 2021-06-17 at 6 02 21 PM](https://user-images.githubusercontent.com/62053665/122376845-18527300-cf97-11eb-9224-5fa1c9dd6072.png)

**More Info:**

1. This issue doesn't reproduce when adding docker files to workspace only with default port "5000".
2. This issue only reproduces on Mac.

**Comment by bwateratmsft** [comment]
Probably due to SSL being off by default now unless `configureSsl` is explicitly set to true.

**Comment by bwateratmsft** [comment]
I looked into it and this is by design. The relevant code is https://github.com/microsoft/vscode-docker/blob/main/src/commands/containers/browseContainer.ts#L28-L31. Most commonly, 5001 is an SSL port--the default for ASP.NET, in particular. So, if we see the container-side port is 5001 (or 443), we will open a URL with `https` instead of `http`.

Using anything other than 5001 or 443 causes it to open with `http` which would work as long as Flask is listening on that port.
