### ISSUE TITLE
Docker container removed after task completes or stopped, despite dockerRun.remove = false

### ISSUE THREAD

**Issue by codeocelot** [microsoft/vscode-docker#3200]
Reproduction:
- Clone [this minimal reproduction repo](https://github.com/codeocelot/vscode-docker-remove-bug) and open in VS Code with this extension enabled (and no other extension)
- Run Task labeled "docker-run: debug (no remove)"
- Observe that the container is removed, despite `remove: false`
- [Optional] Run task labeled "docker-run: debug (remove)" to confirm both options produce the same results.

Expected:
My container shouldn't be removed if `remove: false`

Actual:
My container is always removed, despite the flag.

Resources:
VS Code documentation that explains the use of this flag.
https://code.visualstudio.com/docs/containers/reference#_dockerrun-object-properties

**Comment by bwateratmsft** [comment]
This is actually by-design. The `"remove"` flag is intended for use outside of debugging, i.e. if you simply ran the task directly (though, the app itself will not run when launched from a debug task, unless you override the `"command"` option in `"dockerRun"`). When debugging, container removal after debug is controlled by the `"removeContainerAfterDebug"` flag on the launch configuration:

```json
        {
            "name": "Docker: Python - No Remove",
            "type": "docker",
            "request": "launch",
            "preLaunchTask": "docker-run: debug (no remove)",
            "python": {
                "pathMappings": [
                    {
                        "localRoot": "${workspaceFolder}",
                        "remoteRoot": "/app"
                    }
                ],
                "projectType": "general"
            },
            "removeContainerAfterDebug": false
        }
```

The reason these containers are removed after debugging is because, if they weren't, subsequent debug sessions would fail because the container name is already in use.

For reference, this would be a launch task that would not remove the container afterward, but still launch the app:

```json
		{
			"type": "docker-run",
			"label": "docker-run: debug (no remove)",
			"dependsOn": [
				"docker-build"
			],
			"dockerRun": {
				"remove": false,
				"command": "python3 main.py"
			},
			"python": {
				"file": "main.py"
			}
		}
```
