### ISSUE TITLE
v1.18.0 broke image pushing to GitLab Container Registry

### ISSUE THREAD

**Issue by philippdormann** [microsoft/vscode-docker#3321]
when clicking "Docker Images: Push" via the VS Code Command Palette, the image selection gets displayed properly.

when submitting (ENTER), the push fails with this error
```
Request to https://gitlab.com/api/v4/projects?per_page=100&simple=true&membership=true failed with status 403: Forbidden
```

pushing via `docker push <image>` works just fine

for now, rolling back to v1.17.0 works

## system info
- Docker version 20.10.8, build 3967b7d
- VS Code 1.63.0-insider

**Comment by bwateratmsft** [comment]
What scopes are present on the access token you are using?

**Comment by bwateratmsft** [comment]
I guess raising that error is a side-effect from #3242, where before it would be suppressed and things would proceed (accidentally, I would argue). While the Docker CLI only requires `write_registry` to push an image, the extension itself requires the `read_api` or `api` scopes in order to enumerate projects. In your case, `read_api` and `write_registry` I think would be sufficient, otherwise `api` certainly is. Can you try switching to a token with those scopes to see if that fixes the issue with 1.18?

**Comment by philippdormann** [comment]
adding the `read_api` scope solves this issue 😉

**Comment by bwateratmsft** [comment]
Great! I'll close this since it's working as desired with `read_api` and `write_registry`.

Thank you for filing this! Hopefully it will help anybody else who runs into the same issue.
