### ISSUE TITLE
Treeview UI for images does not reflect the similarity of Image IDs stored in different registries (add untag?)

### ISSUE THREAD

**Issue by PrashanthCorp** [microsoft/vscode-docker#333]
In your existing docker project, build an image twice, with the registry (prefix in the tag) being different. 
Docker behavior: the images have the same ID. 
![image](https://user-images.githubusercontent.com/30420973/43288123-d36a3e64-90db-11e8-8073-810c7947ae50.png)

The side-effect (expected Docker behavior) is that removing any one of these images removes both. Our UI should have some indication of this.

**Comment by PrashanthCorp** [comment]
Moreover, I can't seem to remove a tag. I get the following error:
(HTTP code 409) conflict - conflict: unable to delete 406f227b21f5 (cannot be forced) - image has dependent child images

**Comment by StephenWeatherford** [comment]
Is there an untag?

**Comment by PrashanthCorp** [comment]
This could be helpful: 
https://serverfault.com/questions/703344/how-to-remove-an-image-tag-in-docker-without-removing-the-image-itself

**Comment by StephenWeatherford** [comment]
Have:

  Remove Tag  (new)
  Remove Image  (shows warning if multiple tags for same image)

**Comment by khaledez** [comment]
I faced the same issue. I expected remove docker image in VSCode to behave the same as docker cli, but it doesn't, specially in the case of having more than one tag for an image.
If I try to remove a tag, I get 409 conflict error.

I think the expected behaviour should be the same as docker cli and remove the tag not the image.
