### ISSUE TITLE
Show more Info in Network Panel

### ISSUE THREAD

**Issue by JM-Lemmi** [microsoft/vscode-docker#3337]
It would be nice, if the network panel could show more information with a dropdown.

The most useful information in my opinion would be a list of containers connected to the network (and their IP addresses). You can currently get this info from the Inspect-option, but having this info at a glance would be nice.

Mockup:
![github-vscodedocker-netpanel-mockup](https://user-images.githubusercontent.com/41118534/144047178-20c47093-c187-4341-adfa-d6f3b1c6b2d7.png)

**Comment by bwateratmsft** [comment]
It's not as detailed but the tooltip will show containers:
![image](https://user-images.githubusercontent.com/36966225/144069873-1d1dd648-b9c5-4080-9f9d-ab49465dde46.png)

**Comment by bwateratmsft** [comment]
@JM-Lemmi I can't believe I didn't think of this before, but you can set the grouping for the Containers view to use networks. It gives the view you're showing, but in the Containers window instead.

1. Click the gear icon on the Containers view
![image](https://user-images.githubusercontent.com/36966225/151389065-64dd0c46-7139-4c79-adc4-efe2b75a1f70.png)
1. Choose Group By, and select Networks
![image](https://user-images.githubusercontent.com/36966225/151388982-08c11604-7008-42e7-9d6b-f892169841d9.png)

Containers will be shown grouped by network:
![image](https://user-images.githubusercontent.com/36966225/151389283-b2981757-6445-44bf-b704-cb7509143788.png)

I'm going to leave this issue open since there's not currently a way to have the IP address shown in the description like in the mockup, but this may still be helpful.

**Comment by stuartthomson** [comment]
Personally I'd also like to be able to see the containers more easily in the networks view. If we could agree on a design I'd be happy to open a PR with an implementation.

The main thing I am not sure about is if the containers as seen in the networks view should be the same as the ones shown in the container view - for example should you be able to right-click and do everything you can normally do with them?

I'd want to be able to right-click a container to disconnect it.

**Comment by JM-Lemmi** [comment]
That would be awesome. I don't feel comfortable enough with TS to be opening a PR, but I'd happily assist you if I can.

I think the standard options should definitely be there. _Attach, Logs, Stop, Restart_.

_Disconnect_ on the container menu and _connect_ on the network menu would be obvious choices for extra options.

**Comment by bwateratmsft** [comment]
The biggest problem is that a container can be connected to multiple networks. Our tree view framework would not work, as the same container node would need to show up as a child of multiple network nodes. Altering the framework to support this scenario would be quite costly.
