### ISSUE TITLE
Add submenu to "Build image" for arm64 etc

### ISSUE THREAD

**Issue by MikeMichel** [microsoft/vscode-docker#3342]
...where under the hood `docker buildx build --platform linux/arm64` etc. is triggered so you can choose for which platform you want to build.

or add in the field for the image name after you clicked "Build image" the option to choose even multiple target architectures via checkbox so a `docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 ...` is executed.

**Comment by bwateratmsft** [comment]
In this scenario the best choice would be either the Docker extension's [command customization](https://code.visualstudio.com/docs/containers/reference#_command-customization) or a generic [VSCode shell task](https://code.visualstudio.com/Docs/editor/tasks#_custom-tasks). If you go with command customization, the workspace settings (rather than user settings) is probably the best place.
