### ISSUE TITLE
Connects to telemetry domain when installed via SSH Remote (vscode-server)

### ISSUE THREAD

**Issue by natevw** [microsoft/vscode-docker#3372]
The current README says [re. telemetry](https://github.com/Microsoft/vscode-docker#telemetry):

> If you don’t wish to send usage data to Microsoft, you can set the `telemetry.enableTelemetry` setting to `false`.

I have done so in my "main" VS Code app running on my Mac, but it appears that this setting is not being respected in a VM that I connect to via the Remote SSH extension, and afaict it is this (vscode-docker) extension that is the culprit.

Specifically I have done:

1. Set `telemetry.enableTelemetry` as `false` on my "local" development workstation
2. Installed the Remote SSH extension on that local workstation
3. Used the Remote SSH extension to connect to a VM from the local app (this step installs vscode-server on the remote)
4. Installed this Docker extension on the *remote* (VM) workspace

And after I have done so, my VM begins attempting connections to endpoints (e.g. `eus012-breeziest-in.cloudapp.net`) which present a TLS cert for `in.applicationinsights.azure.com` which smells like an analytics gathering service.

Why does my telemetry opt-out seem to be ignored in this situation? Why is this extension phoning home from an opted-out VS Code app when run in a remote/vscode-server context?

**Comment by bwateratmsft** [comment]
Taking a look at why this is happening. We absolutely want to respect this setting.

**Comment by natevw** [comment]
@bwateratmsft Thanks! I wasn't sure if there was a separate opt-out on the server itself that I'd neglected, but afaict the workstation's settings usually "inherit" to the remote. And the main VS Code server only seems to be reaching out to update but not analytics servers, until I add this plugin.

**Comment by karolz-ms** [comment]
Regardless of the root cause, we should update the README to point people to `telemetry.telemetryLevel` as `telemetry.enableTelemetry` is deprecated: https://code.visualstudio.com/docs/supporting/faq#_how-to-disable-telemetry-reporting

@natevw if you use `telemetry.telemetryLevel` to `off`, do you still see VS Code Docker ext reporting telemetry from remote machine?

**Comment by bwateratmsft** [comment]
Agree with @karolz-ms though I do also want to point out that if `telemetry.enableTelemetry` is set to `false`, then `telemetry.telemetryLevel` will be ignored:

![image](https://user-images.githubusercontent.com/36966225/148842265-a32e2fa9-ba77-4fa7-812b-2c512c82890a.png)

**Comment by natevw** [comment]
> @natevw if you use telemetry.telemetryLevel to off, do you still see VS Code Docker ext reporting telemetry from remote machine?

It looks like this was indeed the setting (in the "User" tab) that I'd been using on this new setup. My `~/Library/Application Support/Code/User/settings.json` begins with:

```
{
    "telemetry.telemetryLevel": "off",
//…
```

Whereas in the remote VM I have an *empty* settings.json apparently. `/home/debian/.vscode-server/data/Machine/settings.json` simply:

```
{
}
```


And full disclosure: I honestly thought I had narrowed it down to this plugin, and definitely got a connection attempt right as I switched to it in the sidebar, and they seemed to go away when I disabled it. But I may have just seen another connection while *this* extension was disabled. So there's a chance this may be a different problem :-/

**Comment by bwateratmsft** [comment]
As far as I can tell, the absence of those settings in the Remote settings is intentional; they do not show up in the Remote settings UI at all:
![image](https://user-images.githubusercontent.com/36966225/148843226-c1412f3b-a250-42b0-8c28-94462550318d.png)
![image](https://user-images.githubusercontent.com/36966225/148843263-666b516b-6d1b-4785-a806-92687af8fa02.png)

I did a quick and dirty test and found that the setting value, and also `vscode.env.isTelemetryEnabled`, are carried as expected into the remote workspace (at least in WSL's case but I have no reason to think SSH would be different).

It is possible that something other than the extension's telemetry system is reaching out to the domain. There are a _few_ `@azure` packages that get loaded unconditionally when the extension is activated, and a several more if any Azure features are used. I don't know if they have their own telemetry system or not, but it is possible.

**Comment by natevw** [comment]
Thanks for your continued investigation. I went ahead just as a test (this does **not** appear to be even a workaround, and iiuc from your above notes, this shouldn't be necessary in the first place) and set my **remote** settings (e.g. "/home/debian/.vscode-server/data/Machine/settings.json") to:

```
{
    "telemetry.telemetryLevel": "off"
}
```

This changes no behavior, I still see the connection attempts.

**Comment by natevw** [comment]
> It is possible that something other than the extension's telemetry system is reaching out to the domain. There are a few @azure packages that get loaded unconditionally when the extension is activated, and a several more if any Azure features are used. I don't know if they have their own telemetry system or not, but it is possible.

Ahhh, despite my slight hedging above I retested this and even had a sketched out a whole writeup here about various tests I did to "prove" that it was this extension. (No use of domain without it, use of domain as soon as installed, stops using domain once uninstalled, etc.)

**But** then I repeated them with e.g. "Hex Editor" instead of (this) "Docker" plugin — and got the same results! My VM tries to send analytics as soon as I install *that* plugin instead.

So I do apologize — there's something wrong here but I now agree that it seems to be elsewhere. My current working theory is that VS Code (/vscode-server) itself is sending telemetry when I interact with **any** extension, and this just happened to be the one extension I was interacting with. Sorry for the noise, and thanks for your quick attention anyway!

**Comment by bwateratmsft** [comment]
Thank you for reporting this either way! It's very important to us to respect user choice.

**Comment by karolz-ms** [comment]
@natevw thank you for helping us make VS Code better, we appreciate that a lot. Please consider opening in the [VS Code main repo](https://github.com/Microsoft/vscode), even if you are not able to narrow the repro down precisely. Privacy IS important to us. Thanks again.
