### ISSUE TITLE
Use absolute filepaths from "config_files" unchanged

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-docker#3401]
https://github.com/microsoft/vscode-docker/commit/6bc9540b3a058e3dc338fa2e1fcc6797b2a369d7 changed `getComposeFiles()` to always use the basename of the filepath. It would make sense to keep filepaths that are absolute as-is.

/cc @bwateratmsft

**Comment by bwateratmsft** [comment]
It seems that Compose V2 maybe generally solves the original issue (#2633) anyway, since it seems to always stamp absolute file paths in `config_files`. Still, Compose V1 is common, so we'll blend the logic as @chrmarti suggests--if the path is already absolute, no need to make changes or assumptions to it.
