### ISSUE TITLE
DOCKER_HOST is not respected when Docker Desktop is not installed

### ISSUE THREAD

**Issue by AlexanderYW** [microsoft/vscode-docker#3469]
DOCKER_HOST is not respected when Docker Desktop is not installed. Make VS Code read the environment variable and use the value with the docker cli binaries, just like if it was manually defined inside settings.

Why?
- Automating a full development setup will need this approach where setting the environment variable will make the software and extension work out of the box.
- Centralizing the configuration of the remote docker instance endpoint.

- VSCode Version: 1.65.2
- Local OS Version: 1.20.0

Steps to Reproduce:
1. Make sure Docker Desktop is not installed
2. Make sure you have a Docker instance running on a remote machine
3. Download and add the Docker Cli Binaries on windows to your system PATH environment variable
4. Add DOCKER_HOST to your windows environment variables to point at the remote instance through SSH or TCP
5. Open the Docker Extension in VS Code and see it's not able to connect to the instance (If one sets it manually inside the extension settings it works)

**Comment by bwateratmsft** [comment]
A couple questions just to make sure I'm understanding your scenario correctly.

1. Does the Docker CLI work from within a VSCode terminal, when you have `DOCKER_HOST` set?
2. When you say "manually defined inside settings", do you mean the Docker extension works as expected if you use the `docker.host` VSCode setting?
3. Are you using TCP or SSH? SSH requires some extra setup (https://code.visualstudio.com/docs/containers/ssh), and TCP doesn't work if certificates are required (#2058)

**Comment by AlexanderYW** [comment]
1. No Docker CLI does not respect the DOCKER_HOST environment variable, but i think it would make sense that VS Code would be using it still
2. Correct, right now it's defined inside docker extension settings where it works
3. I'm using TCP, but i dont think using SSH would change the outcome when it's not even reading it. I only wrote the SSH one to make sure that would work as well for people with that kind of setup :)

**Comment by bwateratmsft** [comment]
The [code](https://github.com/microsoft/vscode-docker/blob/main/src/docker/ContextManager.ts#L222-L271) we have for loading context information first looks at settings, then at the `DOCKER_HOST` environment variable. The setting is used preferentially, but otherwise it is used and treated exactly the same as the `DOCKER_HOST` environment variable. In fact, the setting actually just results in the `DOCKER_HOST` environment variable being set to the settings' value within the Dockerode initialization and within terminals and processes within VSCode.

There are two key ways in which the Docker extension interacts with the Docker host--

1. Using the HTTP daemon API (through the `dockerode` NPM package). This powers most everything in the explorer view; e.g. the list of containers, images, etc. It also handles some of the Docker commands like pruning, starting/stopping containers, etc. In general, anytime you _don't_ see the command executed in the terminal, we're going through HTTP API. Even if the CLI is absent entirely, most of these features should work; if not that's probably a bug.
3. Using the CLI. This powers commands like Docker build, anything Compose-related, image tagging and pushing, container log viewing and shell attach, and a few other things. In general, anytime you _do_ see the command executed in the terminal, that really is the CLI doing it.

With `docker.host` (the extension setting) in place, which of 1. and 2. above are working (or both)? With `DOCKER_HOST` (the environment variable) in place, which are working?

**Comment by gattila** [comment]
I have a DOCKER_HOST env variable, and it points to tcp://localhost:2375. The docker ps works fine. The docker explorer also works like a charm. But the current version of this extension still display "Error: ECONNREFUSED tcp://localhost:2375" message.

**Comment by AlexanderYW** [comment]
> The [code](https://github.com/microsoft/vscode-docker/blob/main/src/docker/ContextManager.ts#L222-L271) we have for loading context information first looks at settings, then at the `DOCKER_HOST` environment variable. The setting is used preferentially, but otherwise it is used and treated exactly the same as the `DOCKER_HOST` environment variable. In fact, the setting actually just results in the `DOCKER_HOST` environment variable being set to the settings' value within the Dockerode initialization and within terminals and processes within VSCode.
> 
> There are two key ways in which the Docker extension interacts with the Docker host--
> 
> 1. Using the HTTP daemon API (through the `dockerode` NPM package). This powers most everything in the explorer view; e.g. the list of containers, images, etc. It also handles some of the Docker commands like pruning, starting/stopping containers, etc. In general, anytime you _don't_ see the command executed in the terminal, we're going through HTTP API. Even if the CLI is absent entirely, most of these features should work; if not that's probably a bug.
> 2. Using the CLI. This powers commands like Docker build, anything Compose-related, image tagging and pushing, container log viewing and shell attach, and a few other things. In general, anytime you _do_ see the command executed in the terminal, that really is the CLI doing it.
> 
> With `docker.host` (the extension setting) in place, which of 1. and 2. above are working (or both)? With `DOCKER_HOST` (the environment variable) in place, which are working?
> 
> (Side note: eventually we're hoping to use the CLI only, #3263, so that there's no longer any disparity between 1. and 2. above)

Hi @bwateratmsft,

I was reading the code too and could not understand why it wasn't working. Thats why I created this issue.

But you're right it should work and it does work! It turns out that I had to restart VSCode, before it went into effect (I believe?), because it's working now!

Not sure if that should be a different issue? (one has to restart it), but my issue works. So i'm closing this one :)
