### ISSUE TITLE
Group ownership of the file changes by editing

### ISSUE THREAD

**Issue by nachokhan** [microsoft/vscode-docker#3484]
My container is running alright.
I have mounted a volume to allow modifications locally and get the changes in the container.
Then I open a container, look for a file inside of it.
Then I right-click the file selecting the "Open" option.
I change the file's content and save it.
The file saved is now in the container.
The problem is: locally, the group ownership changed to "root" (it was nacho).

In the following example the edited file is **main.py**

This first image shows permissions locally before editing and saving.
![image1_before_save](https://user-images.githubusercontent.com/984137/162277272-02b185e2-8d25-4445-8544-e4c7233cd992.png)

Second image shows the same folder after the edition.
![image2_after_save](https://user-images.githubusercontent.com/984137/162277318-7ef93324-1dd7-4062-9f48-0cacdc2380ed.png)

It would be nice to keep permissions as they were. Why? Because after this change, I need root permissions to update the file locally.
That makes no sense.

**Comment by bwateratmsft** [comment]
Thanks for opening this, it's a good issue. I don't think we have logic to preserve the permissions and ownerships. It might just be the `copyUIDGID` flag: https://docs.docker.com/engine/api/v1.41/#operation/PutContainerArchive

**Comment by bwateratmsft** [comment]
I've spent some time investigating, and unfortunately I don't think it's possible to deal with this scenario without making the performance absolutely awful. VSCode's [`FileSystemProvider`](https://code.visualstudio.com/api/references/vscode-api#FileSystemProvider) API, [`FileStat`](https://code.visualstudio.com/api/references/vscode-api#FileStat) in particular, does not offer a way to attach owner/group owner info--so even though we _could_ access it at the time of directory listing, it would immediately be lost.

The only alternative (which would have awful performance) would be to look up the UID/GID of the file just before writing, pack those values in to the archive, and use the `copyUIDGID` flag.

@nachokhan the best workaround would be to use the [Remote - Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension to attach VSCode to the container, and edit files there--or otherwise, edit the files on the host side of the volume mapping instead of the container side, if that is possible in your scenario.

**Comment by nachokhan** [comment]
Thanks my friend for the time invested on this topic. Because of the nature of my problem it is possible to use volumes and that's what I'm doing now so it's not a problem at all right now. However it would be nice to warn about this problem just in case another user face the same situation :)
