### ISSUE TITLE
Remote Docker Containers "Failed to connect. Is Docker running?"

### ISSUE THREAD

**Issue by YouSenRong** [microsoft/vscode-docker#3530]
The remote docker containers "Failed to connect. Is Docker running?", but the Images can be connect and show correctly.

Local:
VScode 1.67.2 universal
Mac os 12.4
Remote:
Ubuntu 16.04

I have read these two issue, but it seems not work to me. 

https://github.com/microsoft/vscode-remote-release/issues/4800

https://github.com/microsoft/vscode-docker/issues/3111

Additionaly, I have seen this answer https://github.com/microsoft/vscode-docker/issues/3111#issuecomment-894636153, but I don't know how to apply it in my problem.

**Comment by bwateratmsft** [comment]
@YouSenRong can you share a screenshot of what you're seeing?

**Comment by code-d** [comment]
@YouSenRong I have the same issue, maybe its related to `ssh2` issue

need to add following line to sshd config on the server

```text
PubkeyAcceptedKeyTypes=+ssh-rsa
```

Details:
https://github.com/mscdex/ssh2/issues/989#issuecomment-1117074996_

**Comment by chrisbrocklesby** [comment]
I am also having the same issue on MacOS with the VSCode Docker Extension...

`docker context use remote` works in Terminal but the extension refuses to connect to the remote host/context.

**Comment by majksner** [comment]
I am also having the same issue, and it seems it's because I have moved my SSH keys to 1Password (https://developer.1password.com/docs/ssh/get-started#step-3-turn-on-the-1password-ssh-agent) and added this line to `~/.ssh/config

```
Host *
  IdentityAgent "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
```

If I remove this line, all works correctly. Running `docker ps` from command line works fine, but it asks me to authenticate to use my SSH key.
