### ISSUE TITLE
Debugging into .NET container fails when OutputPath is set to absolute path

### ISSUE THREAD

**Issue by the-nerbs** [microsoft/vscode-docker#3597]
My coworkers and I are running into an issue when trying to set up a launch configuration to debug our .NET application while it's running inside a container.  We have found that when we assign our project's `OutputPath` property with an absolute path, debugging fails with a message saying the application DLL was not found and showing a path that appears to be just `/app` with our absolute path appended to it.

Repro steps:
1. Create a C# console application using the `dotnet new console` command in an empty directory
2. Open the directory from step 1 in VS Code.
3. Ensure the C# (`ms-dotnettools.csharp`) and Docker (`ms-azuretools.vscode-docker`) extensions are installed and enabled.
4. Add `<OutputPath>$(MSBuildThisFileDirectory)/bin/$(Configuration)/</OutputPath>` to a `<PropertyGroup>` in the csproj created in step 1.
5. Open the command palette and run the "Docker: Add Docker Files to Workspace..." command. Select ".NET: Core Console" for the platform, "Linux" for the OS, and "No" for including an compose file.
6. Place a breakpoint on the `Console.WriteLine` call in Program.cs.
7. Run the "Docker .NET Core Launch" debug configuration.

Expected behavior: The application is built and the debugger pauses execution at the `WriteLine` call.

Actual behavior: The application is built, but debugging fails with messages similar to this printed to the Debug Output window:
> The command could not be loaded, possibly because:
>   * You intended to execute a .NET application:
>       The application '/app/home/the-nerbs/src/repro/bin/Debug/net6.0/docker-debug-repro.dll' does not exist.
>   * You intended to execute a .NET SDK command:
>       No .NET SDKs were found.
> 
> Download a .NET SDK:
> https://aka.ms/dotnet-download
> 
> Learn about SDK resolution:
> https://aka.ms/dotnet/sdk-not-found
> The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
> The program '[28] dotnet' has exited with code 145 (0x91).

The project I generated this output from was in the directory `/home/the-nerbs/src/repro`.  By removing the `$(MSBuildThisFileDirectory)/` prefix from the `OutputPath` value, or by removing the property assignment entirely debugging works as expected.

I can't share my exact use case here, but I've created a repository containing a reproduction that's a bit closer to our real use case here: https://github.com/the-nerbs/docker-debug-repro . I believe the most significant difference between the repro steps above and this other repro is that `OutputPath` is also set to a path outside of the project's directory.

Some information on the environments we're seeing this on:
- OS: seen with both Ubuntu 22.04 (jammy) and Linux Mint 20.3 (una)
- .NET v6.0.300
- Docker Extension v1.22.1
- Visual Studio Code v1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2)

**Comment by bwateratmsft** [comment]
First off, thanks for all the details, it really helps!

I wouldn't recommend using an absolute path as the `$(OutputPath)`, because it could take away some of the portability that you gain by using containers. In the case of the Docker extension, it could not always accurately determine the artifact path, because it can only look at the project files on the local machine to determine the path, but the correct path is in the container. (We actually do `dotnet build` locally to let MSBuild evaluate the `$(OutputPath)` property for us, but make the assumption that it is a relative path--which is incorrect in this case)

Nevertheless there's two changes you can make that I think should get debugging working (I tried these in your sample repo and everything seemed to work):

1. In `.vscode/tasks.json`, add a volume mapping to map the location on your local machine to the `/app` folder in the container. In the case of your repro repository, it's just `${workspaceFolder}`. The added bit is the `"volumes"` section in the `"dockerRun"` property.
```json
{
    "type": "docker-run",
    "label": "docker-run: debug",
    "dependsOn": [
        "docker-build: debug"
    ],
    "dockerRun": {
        "volumes": [
            {
                "containerPath": "/app",
                "localPath": "${workspaceFolder}",
                "permissions": "rw"
            }
        ]
    },
    "netCore": {
        "appProject": "${workspaceFolder}/DotnetDockerDebugRepro/DotnetDockerDebugRepro.csproj",
        "enableDebugging": true
    }
}
```
2. In `.vscode/launch.json`, override the args used to launch `vsdbg` in the container to reflect the new path. The added bit is the `"args"` property.
```json
{
    "name": "Docker .NET Core Launch",
    "type": "docker",
    "request": "launch",
    "preLaunchTask": "docker-run: debug",
    "netCore": {
        "appProject": "${workspaceFolder}/DotnetDockerDebugRepro/DotnetDockerDebugRepro.csproj"
    },
    "args": "--additionalProbingPath /root/.nuget/packages --additionalProbingPath /roo/.nuget/fallbackpackages /app/artifacts/DotnetDockerDebugRepro/net6.0/DotnetDockerDebugRepro.dll"
}
```
NOTE: VSCode will give yellow warning squiggles on the "args" property because it's not part of the `docker` launch config--you can ignore this warning; the `docker` launch config ultimately resolves into a `coreclr` launch config, which _does_ contain that property.

The diffs may make it a little easier to see what to add where:
![image](https://user-images.githubusercontent.com/36966225/183652971-9455368a-f75c-4d31-8605-4978b4b2a318.png)
![image](https://user-images.githubusercontent.com/36966225/183653030-2fe1526f-82f2-4c24-8165-f6f4dc601340.png)

Does this work for your scenario?

**Comment by the-nerbs** [comment]
I appreciate the quick reply!

We aren't trying to set the applications directory in the container, just where it builds to on the host environment.  In fact, getting our app to run from the container's `/app` directly would be ideal since that would match our production images.

We gave your suggestion a try and it does get the debugger working as expected. However, we had one issue with the working directory still being `/app` while the DLL and some content files were under the `/app/artifacts/DotnetDockerDebugRepro/net6.0/` directory.

I was able to get past this by updating the `/app` volume mount's host path to `${workspaceFolder}/artifacts/DotnetDockerDebugRepro/net6.0` (the value of our `OutputPath`, including the target framework moniker):
```json
// in tasks.json
{
    "type": "docker-run",
    "label": "docker-run: debug",
    "dependsOn": [
        "docker-build: debug"
    ],
    "dockerRun": {
        "volumes": [
            {
                "containerPath": "/app",
                "localPath": "${workspaceFolder}/artifacts/DotnetDockerDebugRepro/net6.0",
                "permissions": "rw"
            }
        ],
    },
    "netCore": {
        "appProject": "${workspaceFolder}/DotnetDockerDebugRepro/DotnetDockerDebugRepro.csproj",
        "enableDebugging": true
    }
}
```

and also updating the path in the launch configuration's `args` accordingly:
```json
// in launch.json
{
    "name": "Docker .NET Core Launch",
    "type": "docker",
    "request": "launch",
    "preLaunchTask": "docker-run: debug",
    "netCore": {
        "appProject": "${workspaceFolder}/DotnetDockerDebugRepro/DotnetDockerDebugRepro.csproj"
    },
    "args": "--additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages /app/DotnetDockerDebugRepro.dll"
}
```

I believe this gets us past the issues we were running into. Being able to set the application's path in the container from the launch configuration's `args` was definitely the key we were missing here. Thank you very much for your help!

**Comment by bwateratmsft** [comment]
Awesome! I'm glad it's working now! I'll close this issue since there's not really a change we can make (due to the absolute path on host vs. in container thing). Let me know if anything else comes up!
