### ISSUE TITLE
The file list of the container cannot be refreshed

### ISSUE THREAD

**Issue by xiaguangbo** [microsoft/vscode-docker#3599]
New folders are not displayed, and clicking the refresh button does not work.
Sometimes I don't click the refresh button it refreshes itself and then it shows success.
If there are files displayed in the file list, use the command to delete them, but the ones in the list on the left will not disappear.
![image](https://user-images.githubusercontent.com/102402151/184528506-10a23b46-29ba-4770-9212-e0e346a92b56.png)

## environment
版本: 1.71.0-insider (user setup)
提交: eebdf8174b087979ae6af103f6f2e2f6f9062056
日期: 2022-08-12T05:17:00.323Z
Electron: 19.0.11
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.25179

VSCode “Docker” extension：v1.22.1

**Comment by bwateratmsft** [comment]
I have not been able to reproduce this including on Insiders. However, it is significantly affected by performance; file enumeration is inherently very slow in Docker because we have to do `docker exec` commands. We are hoping to improve the performance with #3586.

Do you have a different value in place for the `docker.explorerRefreshInterval` setting?
![image](https://user-images.githubusercontent.com/36966225/184649350-7a625d0c-4d85-4045-b6a4-b09ecc4e9c99.png)

**Comment by xiaguangbo** [comment]
@bwateratmsft I haven't touched these settings, the container I use is ubuntu 20.04, maybe there are too many files in the container?

**Comment by bwateratmsft** [comment]
That's possible. Try changing that setting to something slower, e.g. 5000 or 10000. I've seen VSCode start to struggle when the refreshes take longer than 2 seconds.

**Comment by xiaguangbo** [comment]
@bwateratmsft The parameters have been changed, the effect is not good, and it is still easy to cause the file to not be refreshed.

**Comment by bwateratmsft** [comment]
Ok. I'm hoping that the changes we are making in #3586 should improve this, we've done some perf improvements around the file explorer.

**Comment by bwateratmsft** [comment]
This has now been released in Docker extension version 1.23.0.
