### ISSUE TITLE
Output in the OUTPUT window is missing characters

### ISSUE THREAD

**Issue by charris-msft** [microsoft/vscode-docker#3616]
## Issue
I've run through the "Build Image in Azure..." process a number of times and I've been surprised by the number of missing characters I see in the output window.

Here are some examples:
![image](https://user-images.githubusercontent.com/74415662/190730726-22973c43-a33c-4151-bc54-c3ba10e1f2cc.png)

## Expected behavior
I expect to see 100% of the characters that are being logged displayed in the OUTPUT window.

## Video Repros
https://microsoft.sharepoint.com/:f:/t/JEM/EklDiahGaQtDigc5E2SlrYAB3YU7H2NvdoiyIo1AkQUZ-A?e=eCGRIh

**Comment by bwateratmsft** [comment]
These logs are being streamed from Azure. Need to investigate whether the missing data is happening on service-side (in which case we can't do anything about it) or if it's happening on the client.

Related to #3617

**Comment by dbreshears** [comment]
We should figure out if it is coming from the service or if we are causing

**Comment by bwateratmsft** [comment]
I looked into it, and what's happening is that we're downloading a complete block blob--starting from some byte offset--and outputting it to the output window. I couldn't get it to reproduce, but I'm fairly confident that what was happening here--and in #3617--was the `byteOffset` was slipping due to non-printing terminal control characters not being counted. Slipping backward would cause things to be printed again (as in #3617), slipping forward would cause things to be skipped (as in here).

Additionally, due to #3809, we were outputting redundant timestamps--one from VSCode's log output window, one from the actual blob logs. This was ugly, but we can't prevent VSCode from emitting its timestamps. The simplest solution was to remove the redundant timestamps from the logs themselves.

I have a fix for both the byte offset slippage and the timestamp formatting.

**Comment by alexyaang** [comment]
This has now been released in Docker extension version 1.25.0.
