### ISSUE TITLE
The notification doesn't disappear after clicking "Learn More" button

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-docker#3706]
**OS:** All
**Build Version:** 20221116.1

**Repro Steps:**

1. Start up a private local registry using the command `docker run -d --rm --name noAuthRegistry -p 5100:5000 registry`.
2. Go to the "REGISTRIES" node -> Click 'Connect Registry...' -> Select 'Generic Docker Registry(Preview)' -> Input the URL: 
   ` http://localhost:5100` -> Username: <`Press Enter`>.
3. Push an image to the registry -> Right click the pushed image -> Select "Delete Image..." -> "Yes" -> Click "Learn more" when 
   popping up a notification.
4. Check whether the notification disappears after clicking "Learn More" button.

**Expect:**
The notification disappears after clicking "Learn More" button.

**Actual:**
The notification doesn't disappear after clicking "Learn More" button.
![1](https://user-images.githubusercontent.com/107091828/202675817-771f1768-0555-4f0d-bbd6-485fc444e13a.gif)

**Comment by bwateratmsft** [comment]
This is by design for our Learn More buttons. For toasts that have other actions it's important for users to be able to click "Learn More" and then still be able to take the other actions. For this particular scenario it is indeed strange, but I don't think it's worth deviating from our normal behavior.
