### ISSUE TITLE
The file list cannot display shortcut files

### ISSUE THREAD

**Issue by xiaguangbo** [microsoft/vscode-docker#3738]
1.23.0 and 1.23.1 have this problem, older versions do not.
The shortcut is not visible, but there is no problem with using it, indicating that the shortcut actually exists.

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/102402151/204976775-9057e956-398a-4e7b-8775-fd88c43f329e.png">

**Comment by bwateratmsft** [comment]
IIRC we intentionally do not show them, I need to double-check the code.

**Comment by bwateratmsft** [comment]
Looking back at the [code](https://github.com/microsoft/vscode-docker/blob/3f7cc1300deb33afbc602d40313b829628af871b/src/tree/containers/files/DirectoryTreeItem.ts#L61-L79), it looks like we never intentionally supported symlinks. I think in older versions of the extension, they were mistakenly classified as regular files, though. I think by happy accident they still worked for reading and possibly writing, due to how Docker implements its equivalent to `docker cp` on the HTTP API.

Nevertheless, we didn't really _mean_ for symlinks to ever work, so I think I'm going to change this from bug to enhancement.

**Comment by xiaguangbo** [comment]
@bwateratmsft It is necessary to display all the files in the directory like "ls", which is a big reason why I like this plugin, because it eliminates the need for me to use "ls" to view all files.
It turned out that although I could display all the files, I couldn't tell whether they were ordinary files or links on the screen, resulting in empty files downloaded when I clicked on the mouse to download.
It is better to show all files, and then display a flag to the left or right of the link to indicate that this is a link.

**Comment by bwateratmsft** [comment]
For more advanced file operations, I'd recommend the [Dev Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension. Along with the Docker extension you can use it to attach VSCode to a container, where you can much more easily manage files.

![image](https://user-images.githubusercontent.com/36966225/207635419-0acf11fb-9666-4929-897e-504f266f22e1.png)

**Comment by xiaguangbo** [comment]
@bwateratmsft ok
