### ISSUE TITLE
Saving of a file of a docker container changes its permissions and date

### ISSUE THREAD

**Issue by pananag** [microsoft/vscode-docker#3740]
When I'm editing a file in a docker container that I have opened using the docker extension v.1.23.1 in VSCode and I save it, it loses its permissions and date.

These are the permissions and date of the file before saving
![before](https://user-images.githubusercontent.com/76752433/204999685-6983caa1-9b2a-469d-975a-d3610c009358.png)

But immediately after saving, they are gone.
![after](https://user-images.githubusercontent.com/76752433/204999721-da12a369-56d7-439f-ba60-191e15fffdc2.png)

Same thing happens with every file in every container

**Comment by luarss** [comment]
Can verify this is not a problem in v1.22.2. 

Updates in 1.23.0 and 1.23.2 will lead to this bug

**Comment by bwateratmsft** [comment]
@danegsta we'll have to investigate. I don't know for sure if `docker cp` actually has a way to let us maintain permissions. The `-a` flag mentions copying uid/gid information which would allow us to keep the owner and group (assuming we _know_ their uid/gid), but I don't see anything about permissions.

**Comment by danegsta** [comment]
Looks like we're not writing the original metadata to the tar stream we pass to docker cp. We'll need to add an extra step to run docker exec stat on the file in question and apply the mode, gid, uid, etc. to the tar file in order to preserve the metadata. I've got a proof of concept working and should be able to get it polished up and ready for a PR early next week.

**Comment by bwateratmsft** [comment]
We talked about it in our standup meeting, but currently we are lying to VSCode about most stat info in our FS provider (e.g., size, ctime and mtime, etc.), because the old strategy (of encoding the info into a URI via the query string) doesn't work anymore. What we could do instead is cache the stat info on a per-URI basis, and when VSCode calls `stat()`, return the most recent info from that cache.

We can also use that same cache to store the UID, GID, mode, and other attributes of the file, so that when we overwrite it, we can reapply those same properties in the TAR entry.

**Comment by danegsta** [comment]
We've released a fix for filesystem metadata not being preserved when editing a file in VS Code in release 1.23.3 of the extension.
