### ISSUE TITLE
windows 10 docker' is not recognized as an internal

### ISSUE THREAD

**Issue by SebastianSosa** [microsoft/vscode-docker#3806]
Hi,

I installed Docker on Windows 10 and it is working on my Command Prompt and PowerShell, but when I try to run any type of Docker commands I get the following error: 'docker' is not recognized as an internal command. 

I looked into VSCode developer tools and the Docker path is included in the process.env.path. 

What is the issue and how can I fix it?

Thanks

**Comment by bwateratmsft** [comment]
@SebastianSosa does the issue persist after restarting VSCode? If you open a terminal window in VSCode, are you able to use Docker commands there?

**Comment by bwateratmsft** [comment]
Also, what version of VSCode do you have?

**Comment by SebastianSosa** [comment]
Thank you for your response. @bwateratmsft 

Yes, the problem still persists after restarting VS Code. My current configuration is:
Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

However, this issue appears not to be specific to the Docker extension as I am unable to run both Node.js and Python. I have submitted an issue on the VS Code GitHub repository.: [https://github.com/microsoft/vscode/issues/172124](url)

Best

**Comment by bwateratmsft** [comment]
Thanks @SebastianSosa!

**Comment by bwateratmsft** [comment]
Some users in #3783 might be seeing the same issue.

**Comment by danegsta** [comment]
Our latest nightly build has support for additional diagnostic logging to help troubleshoot this issue. If anyone running into this problem is willing to install the nightly build (see https://github.com/microsoft/vscode-docker/issues/1408 for instructions on installing nightly builds) and provide debug logs, that would be a big help. To install the latest nightly, you'll need to be on at least version 1.74.0 of VS Code.

To enable debug logging for the Docker extension, open the VS Code command palette (ctrl+shift+p on Windows and Linux) and run the Developer: Set Log Level... command. Select debug from the subsequent menu to enable debug level logs, and then make sure you have the Docker extension view open.

To ensure the logs capture enough events to assist in troubleshooting, click on the refresh icons for at least the CONTAINERS and IMAGES Docker resource views. Finally, open the command palette again and run the Developer: Open Log File... command and select Docker from the list of logs. This should open a tab with diagnostics logging from the Docker extension. If this looks like it's captured enough Docker command output (you should see entries for docker container ls and docker image ls at least), you can reset your log level setting to the default of info or any other value you prefer (Developer: Set Log Level... on the command palette).

Take the generated log output, remove any personal/secret information, save it to disk somewhere, and then email it to my github alias (danegsta) @microsoft.com. Please DO NOT share the logs directly in the issue comments on the off chance that they still contain personal information.
