### ISSUE TITLE
Unexpected: Files prefixed with dockerfile are treated as dockerfile

### ISSUE THREAD

**Issue by walkerxiong** [microsoft/vscode-docker#3905]
when I create a file, named 'dockerfile.go', and write some golang code into this file, the vscode reports errors like:
```
No source image provided with `FROM`dockerfile-utils(20)
Unknown instruction: PACKAGEdockerfile-utils(38)
```

**Comment by walkerxiong** [comment]
Version: 1.77.1
Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
Date: 2023-04-04T23:23:33.779Z (1 wk ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 18.7.0
Sandboxed: No
Vscode extension Docker v1.24.0

**Comment by bwateratmsft** [comment]
This is intentional, as for most users, "Dockerfile.xxx" would indeed be a Dockerfile. For example, you might have "Dockerfile.debug", "Dockerfile.win", etc.

You can override this with settings, however. The following setting in either your user or workspace settings.json will force VSCode to treat `dockerfile.go` as a Go file, instead of a Dockerfile:

```json
    "files.associations": {
        "dockerfile.go": "go"
    }
```
