### ISSUE TITLE
There is no label "recently used" next to the used context after executing "Use" action

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-docker#4115]
**OS:** All
**Build Version:** 20231012.1
**Regression:** Not a regression

**Repro Steps:**
1. Expand "Contexts" view.
2. Right click the unused context (like "default") -> Click "Use".
3. F1 -> Docker Contexts: Use.
4. Check whether there is a label "recently used" next to the used context.

**Expect:**
There is a a label "recently used" next to the used context.
<img width="606" alt="Screenshot 2023-10-12 at 16 37 59" src="https://github.com/microsoft/vscode-docker/assets/57662131/3eff5084-1588-4162-b7b3-4ab9111e7d00">

**Actual:**
There is no label "recently used" next to the used context.
<img width="602" alt="Screenshot 2023-10-12 at 16 39 24" src="https://github.com/microsoft/vscode-docker/assets/57662131/70b79298-ccac-48d7-826e-056939855b27">

**More Info:**
1. This issue doesn't reproduce after executing "Docker Contexts: Use" twice for the same one context from command palette.
2. **On Windows**, if you want to change the context "desktop-linux" to "desktop-windows", the label still doesn't appear after executing "Docker Contexts: Use" twice.

**Comment by alexyaang** [comment]
@bwateratmsft We haven't touched this side of the extension, I'm thinking this could be related to the Docker Desktop update?

**Comment by bwateratmsft** [comment]
No, this "recently used" behavior is provided by the @microsoft/vscode-azext-utils package. Could be an update there busted it. We should investigate if the problem is widespread or just affecting contexts; if it's only contexts then it can definitely wait.

**Comment by alexyaang** [comment]
Okay sounds good.

**Comment by alexyaang** [comment]
@bwateratmsft It still works on `Docker Images: Run`, so i think we should be okay. Is there any other command we should see if this works on?

**Comment by bwateratmsft** [comment]
I think I figured out what's happening. The underlying objects are changing--i.e. from "selected = false" to "selected = true"--so the hash code changes and recently used doesn't work. If you choose the same context several times in a row (even though to do so is redundant), it starts working again because the object doesn't change when it's already selected:
![image](https://github.com/microsoft/vscode-docker/assets/36966225/8c1fdda9-4a7f-417e-8afe-47cc83c7c90c)

I think we can won't-fix since it using the same context over and over again isn't something users need to do.
