### ISSUE TITLE
Can't login to GitLab

### ISSUE THREAD

**Issue by jghal** [microsoft/vscode-docker#4132]
I'm using Docker extension v1.27.0 in a remote WSL workspace, and when I go to add a registry, there doesn't appear to be a provider for GitLab. Looking at the Quickstart guide [here](https://code.visualstudio.com/docs/containers/quickstart-container-registries#_gitlab), as well as issues #162, #869, #1968, #1643, I'm under the impression that I should have a GitLab option when I click _Connect Registry_ but I only have options for _Docker Hub_, _GitHub_, and _Azure_.

Trying to connect to https://registry.gitlab.com as a generic V2 registry with my personal access token (which works for `docker login registry.gitlab.com) produces this error

![image](https://github.com/microsoft/vscode-docker/assets/53056391/4dcc6f4e-faf3-44bf-812e-44fe144e21c3)

VS Code version
```
Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by bwateratmsft** [comment]
GitLab support is going to be moved into another extension. In the meantime I would downgrade to Docker 1.26.1 while we work on that. More info here: https://github.com/microsoft/vscode-docker/issues/869#issuecomment-1768428723

> One thing we wanted to call attention to--we decided the best place for the GitLab registry data provider to be is in its own extension, which does not yet exist. As a result, support for GitLab Container Registry is removed in Docker extension version 1.27.0. If you need that GitLab support, I would recommend staying on version 1.26.1 of the Docker extension. You can change by running the command "Extensions: Install Specific Version of Extension...", choosing the Docker extension, and choosing version 1.26.1.

I'm going to leave this issue open and pinned so that others who are experiencing the same can find it easily.

**Comment by jghal** [comment]
Given that plain `docker login registry.gitlab.com` works with the same credentials, isn't it then a bug with this extension that I can't configure it as a generic v2 registry?

**Comment by bwateratmsft** [comment]
GitLab does not implement the [registry v2 specification](https://docs.docker.com/registry/), except I think for the manifest endpoint which is required to be able to pull images. But, listing images and tags is not possible through the registry V2 API; GitLab has their own API for that which is why a separate implementation is needed.

**Comment by jghal** [comment]
ah, ok.

**Comment by bwateratmsft** [comment]
GitLab has agreed to take on the support for GitLab Registries in the Docker extension. They are tracking it here: https://gitlab.com/gitlab-org/gitlab-vscode-extension/-/issues/1223

I will close this issue as external.
