### ISSUE TITLE
[BUG] Conflict with YAML Extension Affecting File Formatting

### ISSUE THREAD

**Issue by LisonFan** [microsoft/vscode-docker#4196]
Hello,

I've encountered a compatibility issue with the Docker extension when the YAML extension is also installed in VSCode.

### Issue Description
Once the YAML extension is installed, the Docker extension (ms-azuretools.vscode-docker) seems to lose its ability to format `docker-compose.yaml` and `Dockerfile`. The error message displayed is: "No formatter installed for 'dockerfile/dockercompose' files." This problem arises specifically after the installation of the YAML extension, indicating a potential conflict.

### Steps to Reproduce
1. Install and confirm the functionality of the Docker extension: [ms-azuretools.vscode-docker](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker)
2. Install the YAML extension.
3. Open a `docker-compose.yaml` or `Dockerfile`.
4. Try using the Format Document feature in VSCode to format the file.

### Environment
- VSCode Version: `1.85.1`
- OS: `macOS`   `Windows`
- Docker Extension Version: `v1.28.0`
- YAML Extension Version: `v1.14.0`

### Additional Context
![image](https://github.com/microsoft/vscode-docker/assets/9424775/a2500879-2e44-418b-9957-4177ebe8cd55)
![image](https://github.com/microsoft/vscode-docker/assets/9424775/ea2a82fc-cc22-4cd6-a5c8-ed1bc8ea5969)
![image](https://github.com/microsoft/vscode-docker/assets/9424775/5dbfc92f-cf6b-40df-bcf6-cc36d99ce7a5)

It appears to be a conflict between the Docker and YAML extensions within VSCode, affecting the file formatting capabilities. Any insights or solutions to resolve this would be greatly appreciated.

Thank you for your assistance in addressing this issue.

**Comment by bwateratmsft** [comment]
For the compose document, it looks like the YAML language extension is not registering itself as a formatter for documents with the `dockercompose` language ID. Can you file an issue in [their repository](https://github.com/redhat-developer/vscode-yaml) for that? It is intentional that the Docker extension disables its own formatter if the YAML extension is installed, because they frankly have a better formatter.

As for the Dockerfiles, you don't have the file saved yet, and it appears that VSCode does not let you format files of some languages until the file has been saved. For example, I was able to format a JSON document before saving the file, but not a Go, Java, or Python file. If you save the document the formatter should work.

**Comment by bwateratmsft** [comment]
External issue: https://github.com/redhat-developer/vscode-yaml/issues/1000
