### ISSUE TITLE
docker-compose.override.yml ignored

### ISSUE THREAD

**Issue by jwaes** [microsoft/vscode-docker#4246]
When i start from the command line `docker compose up` my docker-compose.override.yml file gets taken into account as expected.

When i right click in the extension on the docker-compose.yml file in the explorer panel and choose 'Compose Up' from the menu, the configuration the override file is ignored.

**Comment by bwateratmsft** [comment]
This is intentional since the file has been explicitly selected. If however you run "Compose Up" from the command palette instead of right-clicking the file, it will run the default `docker compose up -d` command, which will include both the `docker.compose.yml` and `docker-compose.override.yml` files.

**Comment by bwateratmsft** [comment]
You can also use [command customization](https://code.visualstudio.com/docs/containers/reference#_command-customization) to get the exact behavior you want.
