### ISSUE TITLE
Images and Containers only show up when Docker Desktop is opened

### ISSUE THREAD

**Issue by jpba7** [microsoft/vscode-docker#4322]
My containers and images doesn't show when I only open vscode
![imagem](https://github.com/microsoft/vscode-docker/assets/95439851/8ddecdc1-235a-493b-92a7-4de9aba16cad)

But after I start Docker Desktop app they start to show normally
![imagem](https://github.com/microsoft/vscode-docker/assets/95439851/b59db60c-4065-477b-9549-90977e84c203)

Version: 1.29.1
OS: linux
OS Release: 5.15.0-112-generic
Product: Visual Studio Code
Product Version: 1.90.0
Language: pt-br

**Comment by danegsta** [comment]
It sounds like you may be hitting a Docker Desktop bug related to resource saver mode that we’ve seen from a number of Docker Desktop users. Basically the Docker daemon can get stuck in resource saver mode and none of the CLI commands work to wake it up, only opening the Docker Desktop UI actually resumes the daemon. 

The main trigger for the issue seems to be that a computer sleeping or enters power saver mode while Docker Desktop is in resource saver mode. For now, the only workarounds we’ve identified are to open Docker Desktop every time you resume your computer from sleep, or to disable Docker resource saver mode.

**Comment by jpba7** [comment]
I've disabled resource saver mode and didn't fixed it. But it's not that bad to open docker desktop to use it.
Anyway, thanks for the help @danegsta !

**Comment by flash-me** [comment]
@jpba7 are you able to use the docker CLI when you don't start Docker Desktop?

**Comment by jpba7** [comment]
@flash-me 
It runs but i guess there's something wrong about my docker daemon. Look at the end of the logs:
![imagem](https://github.com/microsoft/vscode-docker/assets/95439851/3104bdd6-084b-4135-9558-693e964c1f44)

**Comment by flash-me** [comment]
> @flash-me 
> It runs but i guess there's something wrong about my docker daemon. Look at the end of the logs:
> ![imagem](https://github.com/microsoft/vscode-docker/assets/95439851/3104bdd6-084b-4135-9558-693e964c1f44)
> 
> But after i open docker desktop:
> ![imagem](https://github.com/microsoft/vscode-docker/assets/95439851/b91ff175-b068-49ab-9668-44d2c83a10ef)
> 
> 

@jpba7 

 Nothing wrong with it, but exactly what I assumed 😁

You configured your Docker Desktop to not autostart. And with this the docker daemon also not starts, until you open Docker Desktop. And if you quit Docker Desktop instead of closing/minimizing it (so docker icon is not in the menubar at the top), then the docker daemon also quits.

You may close the UI, but don't quit it, then your issues are solved.

**Comment by jpba7** [comment]
Docker Desktop was setup to not autostart. I changed the settings so it starts minimized and everything's running fine as I start my PC and I don't need to open it manually.
Thank you, @flash-me

**Comment by danegsta** [comment]
@flash-me thanks for the help in troubleshooting this issue!
