### ISSUE TITLE
[Feature] - Enable seamless experience by providing a way to start the services from within docker-compose file

### ISSUE THREAD

**Issue by mamilic** [microsoft/vscode-docker#4398]
It would be really handy to be able to run services from docker-compose file, either by having Start All, or Compose Up, or even a button alongside each service within docker-compose file. Something similar already exists in intellij.

![Image](https://github.com/user-attachments/assets/647576d8-eac9-46fc-914b-a2a257830965)

**Comment by bwateratmsft** [comment]
I like this idea!

**Comment by bwateratmsft** [comment]
This is now released in Docker extension version 1.29.4.

**Comment by SawkeeReemo** [comment]
Ok, so how to do you turn this off?? I have 500 little  `> Run Service` links cluttering up my compose file now. I keep accidentally clicking them, and then it throws an error because it's trying to run from some random place that I have no idea how it found. I really love having new features added, but maybe make them opt in. I had to roll back to the previous version just to I could continue working without all the clutter.

**Comment by bwateratmsft** [comment]
@SawkeeReemo see my comment [here](https://github.com/microsoft/vscode-docker/issues/4483#issuecomment-2614075274) for how to disable this feature.

**Comment by davidbenton** [comment]
This should not run when right-clicked. Right click is for discovery, not action. Not opening a ticket, will let maintainers decide whether this deserves one. (In case it matters: MacOS, extension v1.29.4)

**Comment by SawkeeReemo** [comment]
> [@SawkeeReemo](https://github.com/SawkeeReemo) see my comment [here](https://github.com/microsoft/vscode-docker/issues/4483#issuecomment-2614075274) for how to disable this feature.

Yeah, any idea how to do that? I’m fine doing it if someone explains how. I didn’t even know this was a thing. This should be able to be toggled on and off in the settings.

**Comment by rcjsuen** [comment]
> Yeah, any idea how to do that? I’m fine doing it if someone explains how. I didn’t even know this was a thing. This should be able to be toggled on and off in the settings.

1. View > Command Palette (or use whichever hotkey is relevant for your operating system to bring up the [Command Palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette))
2. Search for ">Preferences: Open User Settings (JSON)". Note that the starting `>` is important for searching commands rather than searching for files.
3. Insert the aforementioned block of JSON.

Hope that helps.

**Comment by SawkeeReemo** [comment]
> > Yeah, any idea how to do that? I’m fine doing it if someone explains how. I didn’t even know this was a thing. This should be able to be toggled on and off in the settings.
> 
> 1. View > Command Palette (or use whichever hotkey is relevant for your operating system to bring up the [Command Palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette))
> 2. Search for ">Preferences: Open User Settings (JSON)". Note that the starting `>` is important for searching commands rather than searching for files.
> 3. Insert the aforementioned block of JSON.
> 
> Hope that helps.

This helps immensely! Thank you. I’ll give it a shot.
