### ISSUE TITLE
Incorrect wizard step when deploying images to app service

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-docker#442]
Repro Steps:
1. Make sure there are pushed images under registry.
2. Right click one image then select 'Deploy Image to Azure App Service'
3. Check the serial number next to the placehoder on the popped prompting.

Expect:
Display as '...(Step 1/3)'.

Actual:
Display as '...(Step 2/4)'
![number](https://user-images.githubusercontent.com/34729022/45019200-4602e300-b01b-11e8-9881-c0621e511514.png)

**Comment by StephenWeatherford** [comment]
This is because we're not using the shared wizard (#372)

**Comment by v-dantch** [comment]
The first step is to prompt the customer to select a subscription.
![image](https://user-images.githubusercontent.com/34729092/49140924-6697bc00-f330-11e8-8e7b-ce27c9d62196.png)
And actually it skips this step when there is only one selected subscription.

I am not sure this is by design? Or it should display the Step1 even though there is only one selected subscription.
