### ISSUE TITLE
Disable Dockerfile Linter

### ISSUE THREAD

**Issue by mjhenkes** [Microsoft/vscode-docker#523]
Is there a way to disable the linter for dockerfiles?

Yes this is a dumb question. My project generates dockerfiles from various 'dockerfile fragments' and uses erb to inject variables into the fragments. The linter *does not* like this and complains very loudly. I could change the file extension to not be .Dockerfile but I do like the syntax highlighting.

**Comment by mjhenkes** [comment]
Ideally it'd be great if there were a '#disable' comment that could be added to the fragment dockerfiles that I want to exclude because there are other 'Real' dockerfiles that linting should be run on.

**Comment by rcjsuen** [comment]
@mjhenkes There is currently no way to disable the validation globally or for individual files. I may open up a way for ignoring files but that will probably be via a setting (think of it like a `.gitignore` file) instead of a "special" `# disable linter` comment.

@StephenWeatherford Yes, the language server provides this feature.

**Comment by StephenWeatherford** [comment]
Closing in this repo.
