### ISSUE TITLE
Add support for Docker Toolbox (docker-machine)

### ISSUE THREAD

**Issue by dlorych** [Microsoft/vscode-docker#55]
On Windows prior to version 10, the only solution to run docker is virtual machine. The most popular setup is probably Docker Toolbox kit, which provides docker-machine tool, setting up boot2docker virtual machine.

Do you plan to add a support for it, so that when you open a terminal a command `eval $(docker-machine env)` setting up docker is run before target command?

If it is something would be worth adding, I could look play around with it.

**Comment by lostintangent** [comment]
@dlorych Thanks for the feedback! In your workflow, did you already run `eval $(docker-machine env)`, such that the necessary environment variables would be set for the Docker CLI? I just ask because right now, this extension doesn't look for those environment variables, and so we could potentially just update it to respect them when set, as opposed to needing to call `eval $(docker-machine env)` ourselves.

**Comment by dlorych** [comment]
Setting environment variables in front is one of the solutions. I was thinking about setting them during the vscode runtime - it should be easy to do as well.

Anyway, now, when I gave it more thought, it might not be the best idea to add such functionality into this extension - it might be better to introduce an explicit extension for docker-machine.

I'm closing the issue. Thanks for giving me food for thoughts :)
