### ISSUE TITLE
Does not support Windows containers

### ISSUE THREAD

**Issue by heaths** [Microsoft/vscode-docker#57]
I'm using Windows containers for another Microsoft OSS project and found this extension assumes Linux containers. For example, when I tried to attach to an existing container and the extension ran `docker exec` but assumed `/bin/sh`. In fact, it seems odd to assume that even for Linux since a developer hopefully specified `ENTRYPOINT` potentially overriding the shell.

**Comment by dazhao-msft** [comment]
We have much better support for both Linux container and Windows container in VS 2017 now. Please try VS 2017 RC for your Windows container scenarios and let us know what you think.

https://www.visualstudio.com/vs/visual-studio-2017-rc/

**Comment by lostintangent** [comment]
@heaths Ah yeah, that's a good catch. We should definitely modify this behavior to accomodate Windows containers. Would the equivalent there be `docker exec -it [container] cmd`? What would you do manually in order to open up a shell within a running Windows container?

Regarding your comment about specifying a command in the first place: doesn't the `docker exec` command require you specify one? I didn't think you could simply run `docker exec [container]`.

**Comment by heaths** [comment]
Looks that way, though I can't find if it's affected by ENTRYPOINT. It would be nice if the shell to exec was configurable, since I use PowerShell.
________________________________

**Comment by lostintangent** [comment]
OK cool. I confirmed a fix for this, and will send out a PR soon.

**Comment by lostintangent** [comment]
@heaths FYI, #58 addresses this issue. What is your thoughts on making PowerShell the default for Windows containers? Would that make the most sense?

**Comment by heaths** [comment]
I responded in the PR.

**Comment by chrisdias** [comment]
PR has been merged
