### ISSUE TITLE
docker.acr.pullimage issue

### ISSUE THREAD

**Issue by cargohec** [Microsoft/vscode-docker#648]
Repro steps:

Tried to pull bitnami/java image from Azure

Action: vscode-docker.acr.pullImage
Error type: TypeError
Error Message: Path must be a string. Received undefined

Version: 0.4.0
OS: darwin

![image](https://user-images.githubusercontent.com/20497102/48985699-f0951a00-f0cf-11e8-9e4c-24bb54adae32.png)

**Comment by rosanch** [comment]
PR #656

**Comment by rosanch** [comment]
Hi @cargohec,
I haven't been able to reproduce this exact issue. However, there was an issue on pullimage. The fix was merged today to master(PR #565). That may help. If after that, the error persists please let me know. Meanwhile, is there any extra information you could provide that may help me to reproduce this issue. As of now, the one thing I can think of is that is related to the os, I'll try to test it on Darwin to see if that reproduces the error.

**Comment by rosanch** [comment]
Fixed by #705
