### ISSUE TITLE
Null ref exception showing connection error in prune

### ISSUE THREAD

**Issue by fviaud** [Microsoft/vscode-docker#652]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.system.prune
Error type: TypeError
Error Message: Cannot set property 'suppressErrorDisplay' of undefined

Version: 0.4.0
OS: win32

**Comment by StephenWeatherford** [comment]
@fviaud Thanks for reporting this, it should be fixed in the next release.

This issue only occurs when we have trouble connecting to Docker during the prune process.  I.e., we were trying to show the following error to you:

  Unable to connect to Docker. Please make sure you have installed Docker and that it is running.

thx,
Stephen

**Comment by igwejk** [comment]
I've recently encountered this as well. Looks like [`actionContext` is not being passed to `showDockerConnectionError`](Cannot set property 'suppressErrorDisplay' of undefined) as expected.

**Comment by StephenWeatherford** [comment]
Fixed, will be released as soon as I'm back from vacation in a week.  Thanks.

**Comment by StephenWeatherford** [comment]
This should be fixed in 0.5.1, which was a released a couple of weeks ago.
