### ISSUE TITLE
Testcase issue: An error dialog still pops up after setting 'docker.importCertificates' to true

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode-docker#712]
**OS**: Windows
**Node.js**: V10.13.0
**Extension Build**: [20181216.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1605)

**Repro Steps:**
1. Create a development certificate authority -> Using the new CA certificate created to create a self-certificate for SSL.
2. Create a new registry container using the certificate.
3. Set "Http.proxyStrictSSL" as "true" in VS Code.
4. Right-click on Private Registers -> Connect to a private registry... -> Inputting the **URL/Username/Password**.
5. Set "docker,importCertificates" as "true" in user setting if there is an error and prompt you to set the "docker.importCertificate" setting to true.
6. Right-click on Private Registers -> Connect to a private registry... -> Answer with the **URL/Username/Password** in step4.

**Expect:**
No error dialog pops up.

**Actual:**
Still pop up an error and prompt you to set the "docker.importCertificate" setting to true.
![image](https://user-images.githubusercontent.com/41351993/50082471-08257580-022c-11e9-928f-11a6c7df0cfd.png)

**Comment by StephenWeatherford** [comment]
Did this testcase successfully pass last week?  Also, can you make sure the certificate has been imported into the Windows certificate store?  Thx.

For some reasons I'm having trouble getting through the testcase steps, but haven't had much time to investigate.

**Comment by v-xianya** [comment]
Thanks for your updates.
1. The certificate has been imported into the windows certificate store successfully.
![image](https://user-images.githubusercontent.com/41351993/50208119-5745e480-03ab-11e9-8d92-8429e6e57efd.png)
2. Verified with build 20181218.1. This issue also reproduces.

**Comment by StephenWeatherford** [comment]
This works for me on Linux.

On Windows, it is failing because of an issue with trying to map drives in the compose file.  You can see this by using this instead of the Compose Up menu:
 
  docker-compose -f "docker-compose.yml" up  --build

You'll see this error in the output:

registry_1  | time="2018-12-20T03:42:33Z" level=fatal msg=**"open /certs/127.0.0.1.pem: no such file or directory"**

Not sure if this is a regression in docker compose for Windows or a mistake in the compose file.

Either way, this isn't an issue with our extension, but a possible testcase issue or a possible docker compose issue.

**Comment by v-xianya** [comment]
Verified on build [20190316.5](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=4119&view=results). This issue doesn't reproduce. Could you help to resolve it?
