### ISSUE TITLE
Docker push command issue

### ISSUE THREAD

**Issue by maliksajid** [Microsoft/vscode-docker#721]
Action: vscode-docker.setRegistryAsDefault
Error type: Error
Error Message: Internal error: Unexpected value found in context "type of registry node": undefined

Version: 0.4.0
OS: win32

**Comment by StephenWeatherford** [comment]
Currently on vacation.

**Comment by StephenWeatherford** [comment]
@maliksajid Thanks for bringing this to our attention.  I can reproduce this if you select "Docker: Set as Default Registry Path" from the command palette.  But the issue title says "Docker push command issue".  Did you hit this while doing a push command, because I currently don't see how that can happen.  Could you let us know what you were doing when you hit this error?  Thx.
