### ISSUE TITLE
Deploy to different Azure subscription from ACR causes issues

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-docker#743]
I'm not sure what to do about this yet so it's up for discussion.

It's recognized as an ACR connection but shows up like this in the config (notice the warning)

![image](https://user-images.githubusercontent.com/1186948/51210918-d8b86600-18c8-11e9-9bf7-db0d1ac24cca.png)

Switching over to the private registry tab, it's blank so I can't make changes to the config once deployed. Maybe only allow the user to create an app in the same sub as the registry when deploying from ACR would make this smoother, but I'm worried about a) confusion as to why the sub selection is gone and b) is this a common enough problem to fix?

**Comment by rosanch** [comment]
I'm not sure where that screenshot was taken. However, the way you can filter your subscriptions in the visual studio code app it's by clicking in your account at the bottom right corner. It should be shown after you open the extension.
In a case when a command needs the subscription to be specified. The information will be requested when the command it's executed.
If this does not solve your doubt. Could you please provide more information about the previous issue, please?

**Comment by StephenWeatherford** [comment]
Should we have restrictions on them selecting a deployment and registry subscription that are different?

**Comment by northtyphoon** [comment]
I assume you deployed an image from ACR in sub1 to an app service in sub2 and it succeeded. It seems legitimate and it's supposed to use ACR username/password to retrieve images. But you mentioned switching to Private Registry showed empty page. It sounds like a bug in App Service portal.

**Comment by nk111** [comment]
I have the same issue (kind of). Registry and app service are in different subscriptions. In this case you are not able to select the image from the dropdown. The loading indicator just never stops. When you decide to enter the image on the private registry tab you can save. But when you re-enter container settings Azure has automatically "moved" the settings back to the "ACR"  tab. You'll see the message from the screenshot above and are not able to make any changes. The container won't start.

**Comment by jhonnatanpb** [comment]
I have same issue, I create the webapp from cli or from portal, and setting the private registry to an azure registry in other subscription is not working, whe you review container settings, the private registry tab is empty, and the azure container registry tab is populated, also de env variables are created, but it fails to download the image.

**Comment by fennovj** [comment]
Same issue here, I guess this is not vscode related at all since I get the same issue if I try to use a container registry in a different subscription. Even when configuring it as a private registry, it switches back to the ACR and gives the screenshot in the OP.

**Comment by ThomasPe** [comment]
I've created an issue with the ACR team since as @fennovj mentions this seems like a Portal issue.

**Comment by mcollis2** [comment]
Interestingly - If you deploy the app_settings like:
DOCKER_REGISTRY_SERVER_URL = "myawesomeregistry.azurecr.io"
instead of
DOCKER_REGISTRY_SERVER_URL = "https://myawesomeregistry.azurecr.io"
Then it appears to work ok.  I am using terraform to deploy.

So try leaving https:// out of the registry URL - I suspect microsoft are looking for patterns matching https://**.azurecr.io.  This worked for me today.

**Comment by matthiasguentert** [comment]
> Interestingly - If you deploy the app_settings like:
> DOCKER_REGISTRY_SERVER_URL = "myawesomeregistry.azurecr.io"
> instead of
> DOCKER_REGISTRY_SERVER_URL = "https://myawesomeregistry.azurecr.io"
> Then it appears to work ok. I am using terraform to deploy.
> 
> So try leaving https:// out of the registry URL - I suspect microsoft are looking for patterns matching https://**.azurecr.io. This worked for me today.

Unfortunately this didn't work for me.

**Comment by matthiasguentert** [comment]
I have spend some time on this issue and figured it out. Here is my solution: 

Assuming we are having two subscriptions, let's call them `SUB-A` and `SUB-B`, where we are having an Azure Container Registry in `SUB-A` (called `azurebluedev` in my example). 

Now we'd like to create an App Service in `SUB-B` that pulls its image of our container registry by using the **admin username**.

It's critical that you use the correct format under `Image and tag` in the docker blade when creating the app service. It must follow the format `url/image:tag` (without https) otherwise you will run into the described problem. I was using `image:tag` format beforehand which didn't work.

[![enter image description here][2]][2]

This worked for me!


  [1]: https://i.stack.imgur.com/X3Ghq.png
  [2]: https://i.stack.imgur.com/dUmac.png

**Comment by justinpitcher** [comment]
I found a similar thing above working with YAML pipelines/deploys, but I still couldn't get cross-subscription access to work in the task `AzureWebAppContainer@1`. The `imageName` property needs to be something like `myacr.azurecr.io/myimage:$(build.buildId)` but if the container registry is outside of the subscription/service connection of the task, it won't work.

**Comment by jhonnatanpb** [comment]
> I found a similar thing above working with YAML pipelines/deploys, but I still couldn't get cross-subscription access to work in the task `AzureWebAppContainer@1`. The `imageName` property needs to be something like `myacr.azurecr.io/myimage:$(build.buildId)` but if the container registry is outside of the subscription/service connection of the task, it won't work.

For me it worked adding the service principal created in Azure by the service connection created in azure devops to the other subscription (if in same tenant), because when you create a service connection in ADO, the service principal is added in the role assigments of the main subscription, but if you do the same manually for other subscription, those tasks in pipeline work, or at least in my case I managed to solve some cross subscription issues that way

**Comment by bwateratmsft** [comment]
As far as it pertains to the Docker extension, I don't think there are any changes needed at this point. The experience is a little better now than when @fiveisprime opened it:

![image](https://user-images.githubusercontent.com/36966225/103680125-b5729f80-4f53-11eb-94ba-ff3599942fd9.png)

That message looks decidedly by-design to me (and regardless, is up to Azure, not us). However, unlike in the original screenshots, it now shows the other images/tags in that ACR--rather than blank. If you want to change to a different registry, then the images/tags in the ACR don't matter anymore.

IMO we should keep the ability to deploy cross-subscription. I don't like adding in arbitrary roadblocks to things that mostly work.

Relatedly though is using service principle or MSI to access the ACR, we're tracking that in #1685.
