### ISSUE TITLE
Pressing 'Enter' directly under 'Filter by ID' shows all the task images of the registry

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-docker#750]
**OS:** Windows
**Node.js**: V10.14.1
**Extension Build**: [20190120.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2300)
Repro Steps:
1. Create a build task 'taskhelloworld' according to https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-quick-task.
2. Right click the created task ->'Run Task' ->Make sure there generated a repository named 'helloworld' with images tagged as 'cj*'.
3. Open one other project like 'myExpressApp' in VS Code ->Add Docker file to it.
4. Right click 'Dockerfile' ->Click 'ACR Tasks: Build Image' -> Using the default tag and the same registry -> Select one OS(_It will generate a registry with the image tagged as 'cj*'_).
5. Right click the task 'taskhelloworld' -> 'View Tasks Log' -> Click on any of the text box of the filter and press 'Enter' directly.
6. Check the result.

**Expect**:
Only show all the images tagged as 'cj*'of the task '**taskhelloworld**'.
![image](https://user-images.githubusercontent.com/34729022/51462035-9bf1e080-1d9a-11e9-962f-c57b11da9235.png)

**Actual**:
Show all the images tagged as 'cj*' of the **registry**.
![image](https://user-images.githubusercontent.com/34729022/51462030-98f6f000-1d9a-11e9-81b1-0f99bdeb42cb.png)

**Comment by rosanch** [comment]
Did you open the logs by right-clicking over the task, the task label or the resource group? Could you double check? Because I just tested in different OS and every single one of them gave only the task logs when clicking over the task. 
Actually, to see logs without a task I need to click over the resource group and select show logs. Because if it was, in fact, task log, it should have the task name in the task column.

**Comment by EricJizbaMSFT** [comment]
Closing this as "wont-fix" since filters aren't supported in the [new tree and tasks view](https://github.com/microsoft/vscode-docker/pull/966)
