### ISSUE TITLE
Highlight non-default dockerfiles

### ISSUE THREAD

**Issue by italomaia** [Microsoft/vscode-docker#77]
Add support to highlight dockerfiles with non-standart names, like **Dockerfile-client**

**Comment by chrisdias** [comment]
@italomaia where and why do you want these highlighted?  In a docker-compose file?

I ask because the file name is valid. You can use a `-f` flag to specify the file name and I've seen patterns where people create different versions such as `dockerfile-debug` and `docker-compose-debug.yml` which have different build configurations.

**Comment by lostintangent** [comment]
This has been resolved in `master`, and we'll publish an update to the marketplace this week.
