### ISSUE TITLE
error trying to deploy image from tutorial

### ISSUE THREAD

**Issue by SogoGolf** [Microsoft/vscode-docker#774]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.createWebApp
Error type: Error
Error Message: Azure App service currently only supports running images from Azure Container Registries with admin enabled

Version: 0.5.1
OS: darwin

**Comment by StephenWeatherford** [comment]
@SogoGolf This is https://code.visualstudio.com/tutorials/docker-extension/getting-started I assume?

@fiveisprime @rosanch Thoughts?  The tutorial takes you to https://docs.microsoft.com/en-us/azure/container-registry/container-registry-get-started-portal to create the container registry, but the image there shows admin disabled.

**Comment by StephenWeatherford** [comment]
@rosanch I don't understand your comment?  Both what look good, and in what way?  To me, this is an issue with the tutorial, in that it may need to instruct people to set admin enabled if they're trying to use the extension with it.

**Comment by rosanch** [comment]
sorry, I reply to the email by mistake. I deleted the comment to avoid confusion.
What I meant is that I don't see any issues with the tutorial. I would need to see the exact commands you followed to see what is the issue here. 
But if you can't build an image with docker pull I would recommend trying this tutorial and use our tool to create and deploy the container: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-quick-task
Also, you can use the docker extension to create docker images as well.

**Comment by StephenWeatherford** [comment]
@fiveisprime @rosanch I repeat my comment above:
> The tutorial takes you to https://docs.microsoft.com/en-us/azure/container-registry/container-registry-get-started-portal to create the container registry, but the image there shows admin disabled.

Shouldn't it instruct users to enable admin when creating the container registry, given that the error was `Error Message: Azure App service currently only supports running images from Azure Container Registries with admin enabled`?

**Comment by rosanch** [comment]
As far as I know, enabling admin shouldn't affect running an image. I need to know what was run to get this error. Because I even followed the entirety of the tutorial myself and didn't get any issues. 
From what I see in the error I agree that the solution sounds like it is only enabling the admin feature. However, I still don't see an error with the tutorial.

**Comment by fiveisprime** [comment]
Looks like ACR quickstart has changed quite a bit since the tutorial was created. I'll update the doc to more accurately reflect that admin user is required and how to set it up.

@rosanch when did you go through the tut? I'd also like to skip the `az acr login` step in favor of using the admin credentials once setup. It's a bit smoother to a new user of Azure imo

**Comment by rosanch** [comment]
@fiveisprime I did it last Friday. The only step missing here could be to do an az login to be able to do the az acr login. However, even if you don't do it, I still got a different error prompted.

**Comment by StephenWeatherford** [comment]
@fiveisprime fixed the tutorial.
