### ISSUE TITLE
add support for multi stage docker files

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-docker#80]
probably just need to update the default dockerfile template.

https://codefresh.io/blog/node_docker_multistage/

//cc: @lostintangent 

rough idea...

``` dockerfile
FROM node:latest AS base
WORKDIR /usr/src/app
COPY package.json .

FROM base AS dependencies
RUN npm set progress=false && npm config set depth 0
RUN npm install --only=production
RUN cp -R node_modules prod_node_modules
RUN npm install

FROM dependencies AS build
COPY . .
RUN ./node_modules/.bin/gulp
RUN cp -R client prod_client

FROM base AS release
COPY --from=dependencies /usr/src/app/prod_node_modules ./node_modules
COPY --from=build /usr/src/app/prod_client ./client
COPY . .
EXPOSE 3000
CMD npm run start
```

**Comment by lostintangent** [comment]
Sounds good! We should also do the following as well:

1. Update the in-box [Docker syntax file](https://github.com/Microsoft/vscode/blob/master/extensions/docker/syntaxes/docker.tmLanguage.json) to properly colorize the new `AS` keyword and `--from` flag. This is lower pri, but would be nice to do, since multi-stage builds are likely to become pretty common

2. Update the linter rules to not complain about the `AS foo` clause of the `FROM` directive. Currently, we give false negatives about this, which isn't ideal

Additionally, it would be cool to add auto-completion for the `--from` flag, which should be pretty straightforward to do.

**Comment by lostintangent** [comment]
We should also consider the following enhancements:

1. Update the hover provider to parse out the image name correctly when using an AS clause in the FROM directive. Right now, the hover behavior is broken when using FROM/AS

2. Update the Dockerfile completion provider by displaying a completion list of base image names when typing "--from=" in the COPY directive, and the FROM directive

**Comment by seank-com** [comment]
While you are at it. The warning (green squiggle) there can only be one CMD instruction in a Dockerfile is now wrong.

**Comment by StephenWeatherford** [comment]
Current Node.js template:

FROM node:10.13-alpine
ENV NODE_ENV production
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install --production --silent && mv node_modules ../
COPY . .
EXPOSE 3000
CMD npm start

@lostintangent, @chrisdias Do we need to improve this for better practice?

**Comment by PrashanthCorp** [comment]
@lostintangent @chrisdias  your thoughts?
