### ISSUE TITLE
private registry: self signed certificate in certificate chain error 

### ISSUE THREAD

**Issue by sgreiner** [microsoft/vscode-docker#816]
Repro steps:
- use companies Root CA and add it to Windows trusted root store
- the registries certificate is signed by a sub ca of this root ca (veryfied with browser)
![image](https://user-images.githubusercontent.com/2290942/53744067-82b17900-3e9c-11e9-8fd0-023f015b049f.png)
- open VSC project's projectname.code-workspace file and set 
`
{
    "settings": {
        "docker.importCertificates": true
    }
}
`
- Click on "Connect to a private repository" and enter the data (address and user auth info) for the registry
- Error appears

Action: vscode-docker.connectCustomRegistry
Error type: SELF_SIGNED_CERT_IN_CHAIN
Error Message: self signed certificate in certificate chain

Version: 0.5.2
OS: win32
VS Code: 1.31.1

https://github.com/Microsoft/vscode-docker/issues/483 does not work for me :(

**Comment by bwateratmsft** [comment]
Related but not same as #802

**Comment by bwateratmsft** [comment]
@sgreiner It's possible that this issue is fixed with https://github.com/microsoft/vscode/issues/52880. Can you try turning off `docker.importCertificates`, and ensuring that the built-in VSCode setting is on (the default is on), and then try your scenario?
![image](https://user-images.githubusercontent.com/36966225/67791115-46dfab00-fa4d-11e9-9907-6e42507f0e94.png)

Our plan is to remove `docker.importCertificates` sooner or later, since the VSCode option makes it obsolete. It would be good to know if the VSCode option also fixes this issue.

**Comment by sgreiner** [comment]
@bwateratmsft I can confirm that it worked now. 
`docker.importCertificates` was unset and `http.systemCertificates` was set to true (which is the default)
Perfect!

**Comment by bwateratmsft** [comment]
@sgreiner Awesome! Glad it's working now!
