### ISSUE TITLE
Switch over to azure-sdk-for-js

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-docker#844]
https://github.com/Azure/azure-sdk-for-js/blob/master/documentation/Migration.md

**Comment by rosanch** [comment]
Hi,
Should I make all the changes for the extension or only for the ACR files?

**Comment by bwateratmsft** [comment]
Probably related to #1804.

**Comment by bwateratmsft** [comment]
Blocked on https://github.com/microsoft/vscode-azuretools/issues/510.

**Comment by bwateratmsft** [comment]
At the moment we're pretty stuck. We're blocked on https://github.com/microsoft/vscode-azuretools/issues/510. That in turn is blocked on https://github.com/microsoft/vscode-azure-account/issues/140, which is not a particularly simple problem. The `vscode-azure-account` extension is used by many other extensions, but since it's an extension--not a package--all consumers have to use the same version. It's not realistic for every one of them to ship a new version all at once, which means that at least for some time the account extension has to implement both the old and new interfaces.

**Comment by bwateratmsft** [comment]
No longer blocked.

**Comment by bwateratmsft** [comment]
Now that this is released we have some data on activation time. The code loading time is slightly lower--though we didn't expect a big drop since we were already lazy-loading some of the worst offenders. The activation time is the same. :thumbsup:
