### ISSUE TITLE
Debug not running

### ISSUE THREAD

**Issue by johnardilacelis** [microsoft/vscode-docker#939]
Repro steps:

1.
2.

Action: debugCoreClr
Error type: Error
Error Message: Unable to infer the application project file. Set either the 'appFolder' or 'appProject' property in the Docker debug configuration.

Version: 0.6.2
OS: win32
Product: Visual Studio Code
Product Version: 1.33.1
Language: en

<details>
<summary>Call Stack</summary>

```
DockerDebugConfigurationProvider.inferAppProject extension.bundle.js:263:45299
```

</details>

**Comment by philliphoff** [comment]
@johnardilacelis Can you provide a little more context?  For example, it would help to know what your project structure looks like in order to determine where we should be looking to infer project data?  Also note that you can explicitly set the `appFolder` and `appProject` properties in the debug configuration in those cases where we cannot correctly infer those locations.
